import type { ExampleModule } from './types'

/**
 * Where each component page gets its examples.
 *
 * The map is explicit so a slug can be traced to a file by reading, and so
 * every module stays a separate lazy chunk — a visitor downloads the examples
 * for the one page they opened, not for all of them.
 */
const MODULES: Record<string, () => Promise<{ demos: ExampleModule }>> = {
  'ambient': () => import('./ambient'),
  'app-patterns': () => import('./app-patterns'),
  'canvas': () => import('./canvas'),
  'change': () => import('./change'),
  'charts-advanced': () => import('./charts-advanced'),
  'charts-core': () => import('./charts-core'),
  'collaboration': () => import('./collaboration'),
  'controls': () => import('./controls'),
  'cursor-text': () => import('./cursor-text'),
  'data-display-core': () => import('./data-display-core'),
  'data-display-rich': () => import('./data-display-rich'),
  'data-views': () => import('./data-views'),
  'date-time': () => import('./date-time'),
  'diagrams': () => import('./diagrams'),
  'disclosure': () => import('./disclosure'),
  'essentials': () => import('./essentials'),
  'feedback': () => import('./feedback'),
  'forms-core': () => import('./forms-core'),
  'generative': () => import('./generative'),
  'gestures': () => import('./gestures'),
  'inputs': () => import('./inputs'),
  'insight': () => import('./insight'),
  'integrity': () => import('./integrity'),
  'interactions': () => import('./interactions'),
  'kinetics': () => import('./kinetics'),
  'layout-core': () => import('./layout-core'),
  'layout-regions': () => import('./layout-regions'),
  'motion-core': () => import('./motion-core'),
  'motion-scenes': () => import('./motion-scenes'),
  'narrative': () => import('./narrative'),
  'navigation': () => import('./navigation'),
  'overlays-core': () => import('./overlays-core'),
  'overlays-full': () => import('./overlays-full'),
  'physics': () => import('./physics'),
  'pickers': () => import('./pickers'),
  'play': () => import('./play'),
  'reliability': () => import('./reliability'),
  'sound': () => import('./sound'),
  'spatial': () => import('./spatial'),
  'surfaces': () => import('./surfaces'),
  'text-effects': () => import('./text-effects'),
  'toybox': () => import('./toybox'),
  'trust': () => import('./trust'),
  'utilities': () => import('./utilities'),
}

const OWNER: Record<string, string> = {
  'accordion': 'disclosure',
  'achievement-pop': 'play',
  'action-sheet': 'overlays-full',
  'activity-feed': 'app-patterns',
  'activity-heatmap': 'app-patterns',
  'alert': 'feedback',
  'alert-dialog': 'overlays-full',
  'amount-field': 'forms-core',
  'anchor-nav': 'navigation',
  'animated-beam': 'ambient',
  'animated-number': 'motion-core',
  'app-shell': 'layout-regions',
  'approval-chain': 'change',
  'area-chart': 'charts-advanced',
  'ascii-image': 'generative',
  'audio-visualizer': 'sound',
  'audit-trail': 'trust',
  'aurora-surface': 'ambient',
  'avatar-group': 'data-display-core',
  'back-button': 'controls',
  'banner': 'feedback',
  'bar-chart': 'charts-advanced',
  'bar-list': 'data-views',
  'bento-grid': 'layout-regions',
  'blob-morph': 'kinetics',
  'boids-flock': 'generative',
  'border-beam': 'ambient',
  'breadcrumb': 'navigation',
  'bulk-action-bar': 'essentials',
  'button-group': 'controls',
  'calendar': 'date-time',
  'card': 'layout-core',
  'card-deck': 'layout-regions',
  'carousel': 'layout-regions',
  'category-bar': 'data-views',
  'chart-tooltip': 'charts-core',
  'checkbox-group': 'forms-core',
  'coach-tour': 'app-patterns',
  'code-block': 'data-display-core',
  'collapse': 'disclosure',
  'collapsible': 'disclosure',
  'color-picker': 'pickers',
  'combobox': 'forms-core',
  'command-palette': 'overlays-full',
  'confetti': 'motion-scenes',
  'confirm-dialog': 'overlays-full',
  'connection-banner': 'reliability',
  'consent-manager': 'trust',
  'context-menu': 'overlays-full',
  'copy-button': 'essentials',
  'count-up': 'motion-core',
  'countdown': 'essentials',
  'cover-flow': 'spatial',
  'cropper': 'canvas',
  'cube-carousel': 'kinetics',
  'cursor-aura': 'cursor-text',
  'data-explorer': 'app-patterns',
  'data-freshness': 'integrity',
  'data-table': 'data-display-rich',
  'date-picker': 'date-time',
  'date-range-picker': 'date-time',
  'day-schedule': 'insight',
  'description-list': 'data-display-core',
  'dice-roller': 'physics',
  'diff-summary': 'change',
  'diff-view': 'data-display-rich',
  'dock': 'spatial',
  'donut-chart': 'charts-advanced',
  'dot-globe': 'spatial',
  'drawer': 'overlays-full',
  'dropdown-menu': 'overlays-core',
  'emoji-slider': 'toybox',
  'empty-state': 'feedback',
  'error-state': 'feedback',
  'expandable-text': 'essentials',
  'field': 'forms-core',
  'figure': 'data-display-core',
  'file-upload': 'pickers',
  'filter-bar': 'data-display-core',
  'flip-book': 'toybox',
  'flip-card': 'motion-scenes',
  'focus-trap': 'utilities',
  'form': 'forms-core',
  'funnel-chart': 'data-views',
  'glitch-text': 'cursor-text',
  'gooey-loader': 'kinetics',
  'gradient-text': 'text-effects',
  'gravity-tags': 'physics',
  'hold-to-confirm': 'gestures',
  'holo-card': 'surfaces',
  'hover-card': 'overlays-core',
  'image-compare': 'gestures',
  'import-mapper': 'integrity',
  'inline-edit': 'essentials',
  'inline-message': 'feedback',
  'input-otp': 'forms-core',
  'json-viewer': 'data-views',
  'kanban-board': 'data-display-rich',
  'kinetic-text': 'motion-scenes',
  'knob': 'sound',
  'layer-stack': 'spatial',
  'legend': 'charts-core',
  'lightbox': 'essentials',
  'line-chart': 'charts-advanced',
  'liquid-glass': 'surfaces',
  'list': 'data-display-core',
  'list-item': 'data-display-core',
  'live-chart': 'insight',
  'loading-overlay': 'feedback',
  'magic-tabs': 'interactions',
  'magnetic-button': 'motion-scenes',
  'marquee': 'motion-core',
  'marquee-select': 'canvas',
  'masked-value': 'trust',
  'matrix-rain': 'generative',
  'mention-input': 'inputs',
  'menu': 'overlays-core',
  'metric': 'data-display-core',
  'metric-spotlight': 'app-patterns',
  'mini-map': 'canvas',
  'modal': 'overlays-full',
  'morph-dialog': 'interactions',
  'multi-select': 'forms-core',
  'navbar': 'layout-regions',
  'neon-sign': 'surfaces',
  'notification-center': 'app-patterns',
  'number-input': 'forms-core',
  'odometer': 'motion-core',
  'orbit-ring': 'spatial',
  'page-header': 'layout-regions',
  'page-transition': 'motion-scenes',
  'pagination': 'navigation',
  'pan-zoom': 'canvas',
  'parallax': 'motion-scenes',
  'particle-field': 'ambient',
  'password-input': 'forms-core',
  'password-strength': 'essentials',
  'permission-gate': 'trust',
  'piano-keys': 'sound',
  'pin-pad': 'inputs',
  'pixel-canvas': 'toybox',
  'popover': 'overlays-core',
  'portal': 'utilities',
  'presence': 'motion-core',
  'presence-bar': 'collaboration',
  'presence-cursors': 'collaboration',
  'press-scale': 'motion-core',
  'progress-chart': 'charts-core',
  'promo-banner': 'layout-regions',
  'pull-to-refresh': 'gestures',
  'qr-code': 'pickers',
  'quick-actions': 'app-patterns',
  'radar-chart': 'diagrams',
  'radial-gauge': 'charts-core',
  'radial-menu': 'interactions',
  'radio-group': 'forms-core',
  'range-slider': 'forms-core',
  'rate-limit-meter': 'integrity',
  'rating': 'forms-core',
  'reaction-bar': 'narrative',
  'relative-time': 'data-views',
  'retry-queue': 'reliability',
  'reveal': 'motion-scenes',
  'ripple': 'motion-core',
  'ripple-surface': 'kinetics',
  'rope-cursor': 'physics',
  'rotating-word': 'motion-scenes',
  'sankey-flow': 'diagrams',
  'save-indicator': 'reliability',
  'scratch-card': 'interactions',
  'scroll-list': 'data-display-core',
  'scroll-progress': 'interactions',
  'scroll-velocity': 'cursor-text',
  'search-field': 'forms-core',
  'segmented-control': 'controls',
  'select': 'forms-core',
  'session-timeout': 'reliability',
  'shimmer-button': 'ambient',
  'shortcut-recorder': 'inputs',
  'sidebar': 'layout-regions',
  'sidebar-rail': 'layout-regions',
  'signature-pad': 'canvas',
  'slot-reels': 'physics',
  'sortable-list': 'gestures',
  'sparkline': 'charts-core',
  'split-button': 'essentials',
  'split-flap': 'motion-scenes',
  'split-pane': 'essentials',
  'spotlight': 'motion-scenes',
  'stacked-cards': 'narrative',
  'stagger': 'motion-scenes',
  'star-field': 'generative',
  'stat-card': 'data-display-core',
  'state-view': 'app-patterns',
  'status-strip': 'insight',
  'stepper': 'navigation',
  'sticker-peel': 'surfaces',
  'story-progress': 'narrative',
  'streak-counter': 'play',
  'success-mark': 'feedback',
  'swipe-deck': 'interactions',
  'swipe-row': 'gestures',
  'tab-bar': 'navigation',
  'table': 'data-display-core',
  'tabs': 'navigation',
  'tag-input': 'forms-core',
  'terminal': 'toybox',
  'text-reveal': 'text-effects',
  'text-scramble': 'motion-scenes',
  'ticker': 'motion-core',
  'tilt-card': 'motion-scenes',
  'time-picker': 'date-time',
  'timeline': 'data-display-core',
  'toast': 'overlays-full',
  'toggle-group': 'essentials',
  'toolbar': 'controls',
  'tooltip': 'overlays-core',
  'tree-map': 'insight',
  'tree-view': 'data-display-rich',
  'typewriter': 'text-effects',
  'typing-indicator': 'collaboration',
  'undo-stack': 'change',
  'validation-summary': 'change',
  'vibe-poll': 'play',
  'virtual-list': 'data-views',
  'waveform': 'ambient',
  'xp-bar': 'play',
}

const cache = new Map<string, ExampleModule>()

/** The examples for one component, or undefined when its page is hand-written. */
export async function loadExamples(slug: string) {
  const owner = OWNER[slug]
  if (!owner) return undefined

  let module = cache.get(owner)
  if (!module) {
    module = (await MODULES[owner]()).demos
    cache.set(owner, module)
  }
  return module[slug]
}

