import type { ExampleModule } from './types'

/**
 * Where each component page gets its examples.
 *
 * The map is explicit so a slug can be traced to a file by reading, and so
 * every module stays a separate lazy chunk — a visitor downloads the examples
 * for the one page they opened, not for all of them.
 */
const MODULES: Record<string, () => Promise<{ demos: ExampleModule }>> = {
  'ambient': () => import('./ambient'),
  'app-patterns': () => import('./app-patterns'),
  'canvas': () => import('./canvas'),
  'change': () => import('./change'),
  'charts-advanced': () => import('./charts-advanced'),
  'charts-core': () => import('./charts-core'),
  'collaboration': () => import('./collaboration'),
  'controls': () => import('./controls'),
  'cursor-text': () => import('./cursor-text'),
  'data-display-core': () => import('./data-display-core'),
  'data-display-rich': () => import('./data-display-rich'),
  'data-views': () => import('./data-views'),
  'date-time': () => import('./date-time'),
  'diagrams': () => import('./diagrams'),
  'disclosure': () => import('./disclosure'),
  'essentials': () => import('./essentials'),
  'feedback': () => import('./feedback'),
  'forms-core': () => import('./forms-core'),
  'generative': () => import('./generative'),
  'gestures': () => import('./gestures'),
  'inputs': () => import('./inputs'),
  'insight': () => import('./insight'),
  'integrity': () => import('./integrity'),
  'interactions': () => import('./interactions'),
  'kinetics': () => import('./kinetics'),
  'layout-core': () => import('./layout-core'),
  'layout-regions': () => import('./layout-regions'),
  'motion-core': () => import('./motion-core'),
  'motion-scenes': () => import('./motion-scenes'),
  'narrative': () => import('./narrative'),
  'navigation': () => import('./navigation'),
  'overlays-core': () => import('./overlays-core'),
  'overlays-full': () => import('./overlays-full'),
  'physics': () => import('./physics'),
  'pickers': () => import('./pickers'),
  'play': () => import('./play'),
  'reliability': () => import('./reliability'),
  'sound': () => import('./sound'),
  'spatial': () => import('./spatial'),
  'surfaces': () => import('./surfaces'),
  'text-effects': () => import('./text-effects'),
  'theming': () => import('./theming'),
  'toybox': () => import('./toybox'),
  'trust': () => import('./trust'),
  'utilities': () => import('./utilities'),
  'saas-auth': () => import('./saas-auth'),
  'saas-billing': () => import('./saas-billing'),
  'saas-data': () => import('./saas-data'),
  'saas-engagement': () => import('./saas-engagement'),
  'saas-marketing': () => import('./saas-marketing'),
  'saas-pricing': () => import('./saas-pricing'),
  'saas-security': () => import('./saas-security'),
  'saas-settings': () => import('./saas-settings'),
  'saas-workspace': () => import('./saas-workspace'),
  'charts-analytics': () => import('./charts-analytics'),
  'collab-trust': () => import('./collab-trust'),
  'data-audio-games': () => import('./data-audio-games'),
  'developer-parsers': () => import('./developer-parsers'),
  'diagrams-scheduling': () => import('./diagrams-scheduling'),
  'image-files': () => import('./image-files'),
  'text-search-state': () => import('./text-search-state'),
  'canvas-interaction': () => import('./canvas-interaction'),
  'charts-diagrams': () => import('./charts-diagrams'),
  'developer-tools': () => import('./developer-tools'),
  'editors-input': () => import('./editors-input'),
  'games-documents': () => import('./games-documents'),
  'media-capture': () => import('./media-capture'),
  'utilities-layout': () => import('./utilities-layout'),
  'charts-graph': () => import('./charts-graph'),
  'feedback-overlays': () => import('./feedback-overlays'),
  'forms-data': () => import('./forms-data'),
  'foundation-layout-nav': () => import('./foundation-layout-nav'),
  'motion-interaction-play': () => import('./motion-interaction-play'),
  'nav-actions-forms': () => import('./nav-actions-forms'),
  'play-saas': () => import('./play-saas'),
  'charts-progress': () => import('./charts-progress'),
  'data-media': () => import('./data-media'),
  'dialogs-saas': () => import('./dialogs-saas'),
  'forms-advanced': () => import('./forms-advanced'),
  'layout-motion-extras': () => import('./layout-motion-extras'),
  'charts-statistical': () => import('./charts-statistical'),
  'commerce-records': () => import('./commerce-records'),
  'conversation-settings': () => import('./conversation-settings'),
  'forms-extras': () => import('./forms-extras'),
  'structure-extras': () => import('./structure-extras'),
}

const OWNER: Record<string, string> = {
  'a11y-inspector': 'developer-tools',
  'access-denied-state': 'feedback-overlays',
  'access-explainer': 'developer-tools',
  'access-requests': 'dialogs-saas',
  'accordion': 'disclosure',
  'achievement-pop': 'play',
  'action-sheet': 'overlays-full',
  'activity-feed': 'app-patterns',
  'activity-heatmap': 'app-patterns',
  'add-to-calendar': 'nav-actions-forms',
  'address-input': 'forms-advanced',
  'agenda-list': 'data-media',
  'alert': 'feedback',
  'alert-dialog': 'overlays-full',
  'alphabet-index': 'nav-actions-forms',
  'amount-field': 'forms-core',
  'anchor-nav': 'navigation',
  'animated-beam': 'ambient',
  'animated-grid': 'charts-graph',
  'animated-list': 'layout-motion-extras',
  'animated-number': 'motion-core',
  'ansi-output': 'developer-parsers',
  'api-key-manager': 'saas-settings',
  'app-shell': 'layout-regions',
  'approval-chain': 'change',
  'area-chart': 'charts-advanced',
  'article-pager': 'layout-motion-extras',
  'ascii-image': 'generative',
  'aspect-ratio': 'structure-extras',
  'attention-shake': 'motion-interaction-play',
  'audio-player': 'data-media',
  'audio-trimmer': 'media-capture',
  'audio-visualizer': 'sound',
  'audit-trail': 'trust',
  'aurora-surface': 'ambient',
  'auth-card': 'saas-auth',
  'avatar-group': 'data-display-core',
  'avatar-upload': 'forms-advanced',
  'back-button': 'controls',
  'back-to-top': 'structure-extras',
  'banner': 'feedback',
  'bar-chart': 'charts-advanced',
  'bar-list': 'data-views',
  'beeswarm-chart': 'charts-graph',
  'bento-grid': 'layout-regions',
  'billing-toggle': 'saas-pricing',
  'blob-morph': 'kinetics',
  'blur-hash-image': 'media-capture',
  'boids-flock': 'generative',
  'border-beam': 'ambient',
  'box-plot': 'charts-statistical',
  'bpm-detector': 'data-audio-games',
  'branding-settings': 'play-saas',
  'breadcrumb': 'navigation',
  'bulk-action-bar': 'essentials',
  'bullet-chart': 'charts-statistical',
  'button-group': 'controls',
  'calendar': 'date-time',
  'call-grid': 'canvas-interaction',
  'camera-capture': 'media-capture',
  'cancellation-flow': 'dialogs-saas',
  'candlestick-chart': 'charts-statistical',
  'caption-editor': 'media-capture',
  'card': 'layout-core',
  'card-deck': 'layout-regions',
  'carousel': 'layout-regions',
  'cascade-select': 'forms-advanced',
  'category-bar': 'data-views',
  'changelog-list': 'saas-settings',
  'chart-tooltip': 'charts-core',
  'chat-thread': 'conversation-settings',
  'checkbox-group': 'forms-core',
  'checklist-popover': 'feedback-overlays',
  'checkout-summary': 'saas-billing',
  'chess-board': 'data-audio-games',
  'choice-card-group': 'forms-extras',
  'chord-diagram': 'charts-diagrams',
  'choropleth-map': 'charts-diagrams',
  'circular-text': 'motion-interaction-play',
  'click-heatmap': 'charts-diagrams',
  'coach-tour': 'app-patterns',
  'code-block': 'data-display-core',
  'code-editor': 'forms-data',
  'code-tabs': 'data-media',
  'cohort-retention': 'charts-graph',
  'collaborative-text': 'collab-trust',
  'collapse': 'disclosure',
  'collapsible': 'disclosure',
  'color-picker': 'pickers',
  'color-swatch-picker': 'forms-advanced',
  'combobox': 'forms-core',
  'command-palette': 'overlays-full',
  'comment-anchors': 'collab-trust',
  'comment-thread': 'conversation-settings',
  'commit-graph': 'charts-diagrams',
  'confetti': 'motion-scenes',
  'confirm-dialog': 'overlays-full',
  'confirm-popover': 'commerce-records',
  'connection-banner': 'reliability',
  'consent-manager': 'trust',
  'container': 'layout-motion-extras',
  'context-menu': 'overlays-full',
  'contour-plot': 'charts-analytics',
  'control-chart': 'charts-analytics',
  'cookie-banner': 'saas-engagement',
  'copy-button': 'essentials',
  'count-up': 'motion-core',
  'countdown': 'essentials',
  'cover-flow': 'spatial',
  'credit-card-input': 'forms-extras',
  'cron-editor': 'developer-parsers',
  'cropper': 'canvas',
  'crossword': 'games-documents',
  'csp-evaluator': 'developer-parsers',
  'csv-import': 'developer-parsers',
  'cta-section': 'saas-marketing',
  'cube-carousel': 'kinetics',
  'curl-converter': 'developer-parsers',
  'cursor-aura': 'cursor-text',
  'danger-zone': 'saas-settings',
  'dashboard-grid': 'foundation-layout-nav',
  'data-explorer': 'app-patterns',
  'data-export-panel': 'dialogs-saas',
  'data-freshness': 'integrity',
  'data-profile': 'developer-tools',
  'data-table': 'data-display-rich',
  'date-picker': 'date-time',
  'date-range-picker': 'date-time',
  'date-time-picker': 'forms-advanced',
  'day-schedule': 'insight',
  'dendrogram': 'diagrams-scheduling',
  'description-list': 'data-display-core',
  'dice-roller': 'physics',
  'dictation-button': 'media-capture',
  'diff-summary': 'change',
  'diff-view': 'data-display-rich',
  'dock': 'spatial',
  'dock-layout': 'text-search-state',
  'document-scanner': 'image-files',
  'domain-setup': 'dialogs-saas',
  'donut-chart': 'charts-advanced',
  'dot-globe': 'spatial',
  'download-button': 'layout-motion-extras',
  'draft-recovery': 'text-search-state',
  'drawer': 'overlays-full',
  'drop-overlay': 'motion-interaction-play',
  'dropdown-menu': 'overlays-core',
  'dumbbell-chart': 'charts-progress',
  'duration-input': 'forms-advanced',
  'easing-editor': 'editors-input',
  'editable-table': 'data-media',
  'email-verification': 'play-saas',
  'email-viewer': 'developer-tools',
  'emoji-picker': 'forms-extras',
  'emoji-slider': 'toybox',
  'empty-state': 'feedback',
  'equalizer': 'data-audio-games',
  'error-boundary': 'utilities-layout',
  'error-budget': 'charts-analytics',
  'error-state': 'feedback',
  'event-calendar': 'data-media',
  'exif-viewer': 'image-files',
  'expandable-text': 'essentials',
  'expense-splitter': 'collab-trust',
  'experiment-results': 'developer-tools',
  'faq-section': 'play-saas',
  'feature-beacon': 'feedback-overlays',
  'feature-comparison': 'saas-pricing',
  'feature-flags': 'conversation-settings',
  'feature-grid': 'saas-marketing',
  'feedback-widget': 'saas-engagement',
  'field': 'forms-core',
  'figure': 'data-display-core',
  'file-list': 'commerce-records',
  'file-upload': 'pickers',
  'filter-bar': 'data-display-core',
  'filter-builder': 'saas-data',
  'find-in-page': 'utilities-layout',
  'fit-text': 'utilities-layout',
  'flame-graph': 'charts-analytics',
  'flip-book': 'toybox',
  'flip-card': 'motion-scenes',
  'floating-panel': 'feedback-overlays',
  'flow-diagram': 'diagrams-scheduling',
  'flow-field': 'motion-interaction-play',
  'focus-trap': 'utilities',
  'follow-button': 'nav-actions-forms',
  'forecast-chart': 'charts-analytics',
  'form': 'forms-core',
  'formula-editor': 'editors-input',
  'fractal-explorer': 'games-documents',
  'full-text-search': 'text-search-state',
  'fullscreen-dialog': 'feedback-overlays',
  'funnel-chart': 'data-views',
  'fuzzy-finder': 'text-search-state',
  'game-of-life': 'charts-progress',
  'game-2048': 'data-audio-games',
  'gantt-chart': 'charts-progress',
  'geo-coordinate-input': 'developer-parsers',
  'gif-recorder': 'image-files',
  'glitch-text': 'cursor-text',
  'gooey-loader': 'kinetics',
  'gradient-text': 'text-effects',
  'gravity-tags': 'physics',
  'grid': 'foundation-layout-nav',
  'help-panel': 'saas-settings',
  'hero-section': 'saas-marketing',
  'hex-viewer': 'developer-tools',
  'hexbin-chart': 'charts-analytics',
  'highlight-match': 'foundation-layout-nav',
  'histogram': 'charts-statistical',
  'hold-to-confirm': 'gestures',
  'holo-card': 'surfaces',
  'hotkeys': 'utilities-layout',
  'hover-card': 'overlays-core',
  'image-adjust': 'image-files',
  'image-annotator': 'data-media',
  'image-compare': 'gestures',
  'image-diff': 'charts-diagrams',
  'image-gallery': 'commerce-records',
  'import-mapper': 'integrity',
  'incident-timeline': 'charts-statistical',
  'infinite-scroll': 'layout-motion-extras',
  'inline-completion': 'editors-input',
  'inline-edit': 'essentials',
  'inline-message': 'feedback',
  'input-group': 'forms-extras',
  'input-otp': 'forms-core',
  'integration-card': 'saas-settings',
  'invite-members': 'saas-workspace',
  'invoice-list': 'saas-billing',
  'ip-allowlist': 'play-saas',
  'joystick': 'canvas-interaction',
  'json-diff': 'developer-parsers',
  'json-query': 'developer-parsers',
  'json-viewer': 'data-views',
  'justified-text': 'text-search-state',
  'jwt-inspector': 'collab-trust',
  'kanban-board': 'data-display-rich',
  'kaplan-meier-chart': 'charts-analytics',
  'keyboard-shortcuts-dialog': 'dialogs-saas',
  'kinetic-text': 'motion-scenes',
  'knob': 'sound',
  'kpi-strip': 'forms-data',
  'language-switcher': 'layout-motion-extras',
  'layer-stack': 'spatial',
  'lazy-mount': 'utilities-layout',
  'leaderboard': 'data-media',
  'legend': 'charts-core',
  'lightbox': 'essentials',
  'like-button': 'layout-motion-extras',
  'likert-scale': 'forms-data',
  'line-chart': 'charts-advanced',
  'link-preview': 'feedback-overlays',
  'liquid-glass': 'surfaces',
  'list': 'data-display-core',
  'list-item': 'data-display-core',
  'live-chart': 'insight',
  'live-region': 'foundation-layout-nav',
  'loading-overlay': 'feedback',
  'locale-settings': 'dialogs-saas',
  'log-patterns': 'data-audio-games',
  'log-viewer': 'forms-data',
  'logo-cloud': 'saas-marketing',
  'loudness-meter': 'data-audio-games',
  'magic-tabs': 'interactions',
  'magnetic-button': 'motion-scenes',
  'magnifier': 'media-capture',
  'maintenance-notice': 'feedback-overlays',
  'markdown-editor': 'forms-advanced',
  'marker-highlight': 'layout-motion-extras',
  'marquee': 'motion-core',
  'marquee-select': 'canvas',
  'masked-value': 'trust',
  'masonry': 'structure-extras',
  'master-detail': 'foundation-layout-nav',
  'math-formula': 'games-documents',
  'matrix-heatmap': 'charts-progress',
  'matrix-rain': 'generative',
  'measure-tool': 'image-files',
  'mega-menu': 'structure-extras',
  'member-list': 'saas-workspace',
  'memory-game': 'dialogs-saas',
  'mention-input': 'inputs',
  'menu': 'overlays-core',
  'menubar': 'structure-extras',
  'message-composer': 'conversation-settings',
  'message-format': 'text-search-state',
  'meteors': 'charts-graph',
  'metric': 'data-display-core',
  'metric-spotlight': 'app-patterns',
  'metronome': 'motion-interaction-play',
  'middle-truncate': 'utilities-layout',
  'mind-map': 'diagrams-scheduling',
  'minesweeper': 'games-documents',
  'mini-map': 'canvas',
  'modal': 'overlays-full',
  'model-viewer': 'image-files',
  'month-picker': 'forms-extras',
  'morph-dialog': 'interactions',
  'morphing-text': 'motion-interaction-play',
  'multi-select': 'forms-core',
  'natural-date-input': 'editors-input',
  'navbar': 'layout-regions',
  'navigation-progress': 'foundation-layout-nav',
  'neon-sign': 'surfaces',
  'network-graph': 'charts-graph',
  'newsletter-signup': 'play-saas',
  'node-editor': 'canvas-interaction',
  'not-found-state': 'feedback-overlays',
  'notification-center': 'app-patterns',
  'notification-preferences': 'conversation-settings',
  'nps-survey': 'conversation-settings',
  'number-input': 'forms-core',
  'oauth-consent': 'play-saas',
  'odometer': 'motion-core',
  'onboarding-wizard': 'saas-auth',
  'open-api-reference': 'developer-tools',
  'orbit-ring': 'spatial',
  'order-tracker': 'commerce-records',
  'org-chart': 'charts-graph',
  'page-header': 'layout-regions',
  'page-transition': 'motion-scenes',
  'paged-document': 'games-documents',
  'pagination': 'navigation',
  'pairwise-ranker': 'text-search-state',
  'palette-extractor': 'image-files',
  'pan-zoom': 'canvas',
  'panorama-viewer': 'media-capture',
  'parallax': 'motion-scenes',
  'parallel-coordinates': 'charts-diagrams',
  'pareto-chart': 'charts-progress',
  'particle-field': 'ambient',
  'passkey-manager': 'developer-tools',
  'password-input': 'forms-core',
  'password-strength': 'essentials',
  'path-editor': 'image-files',
  'pattern-lock': 'editors-input',
  'payment-method-card': 'saas-billing',
  'peer-link': 'collab-trust',
  'permission-gate': 'trust',
  'permission-prompt': 'games-documents',
  'phone-input': 'forms-extras',
  'piano-keys': 'sound',
  'picture-in-picture': 'canvas-interaction',
  'pin-pad': 'inputs',
  'pitch-tuner': 'media-capture',
  'pivot-table': 'charts-diagrams',
  'pixel-canvas': 'toybox',
  'plan-summary': 'saas-billing',
  'popover': 'overlays-core',
  'portal': 'utilities',
  'presence': 'motion-core',
  'presence-bar': 'collaboration',
  'presence-cursors': 'collaboration',
  'press-scale': 'motion-core',
  'pricing-card': 'saas-pricing',
  'pricing-table': 'saas-pricing',
  'priority-nav': 'foundation-layout-nav',
  'product-card': 'commerce-records',
  'product-variant-picker': 'editors-input',
  'profile-card': 'commerce-records',
  'progress-chart': 'charts-core',
  'promo-banner': 'layout-regions',
  'prompt-dialog': 'dialogs-saas',
  'pull-to-refresh': 'gestures',
  'qr-code': 'pickers',
  'query-bar': 'text-search-state',
  'question-queue': 'motion-interaction-play',
  'quick-actions': 'app-patterns',
  'radar-chart': 'diagrams',
  'radial-bar-chart': 'charts-progress',
  'radial-gauge': 'charts-core',
  'radial-menu': 'interactions',
  'radio-group': 'forms-core',
  'range-slider': 'forms-core',
  'ranked-choice-results': 'diagrams-scheduling',
  'rate-limit-meter': 'integrity',
  'rating': 'forms-core',
  'reaction-bar': 'narrative',
  'read-aloud': 'media-capture',
  'readability-meter': 'collab-trust',
  'receipt': 'forms-data',
  'recent-items': 'nav-actions-forms',
  'record-merge': 'data-audio-games',
  'recurrence-editor': 'forms-data',
  'redactor': 'collab-trust',
  'referral-card': 'conversation-settings',
  'regex-tester': 'developer-parsers',
  'relative-time': 'data-views',
  'release-notes-modal': 'dialogs-saas',
  'remote-selections': 'canvas-interaction',
  'repeater-field': 'forms-advanced',
  'resizable-box': 'data-media',
  'resource-scheduler': 'diagrams-scheduling',
  'retry-queue': 'reliability',
  'reveal': 'motion-scenes',
  'review-summary': 'commerce-records',
  'rich-text-editor': 'editors-input',
  'ripple': 'motion-core',
  'ripple-surface': 'kinetics',
  'roadmap-board': 'play-saas',
  'role-permissions': 'saas-workspace',
  'rope-cursor': 'physics',
  'rotating-word': 'motion-scenes',
  'sankey-flow': 'diagrams',
  'save-indicator': 'reliability',
  'saved-views': 'saas-data',
  'scatter-chart': 'charts-statistical',
  'schema-form': 'editors-input',
  'scoped-search': 'nav-actions-forms',
  'scratch-card': 'interactions',
  'scroll-area': 'structure-extras',
  'scroll-progress': 'interactions',
  'scroll-sequence': 'canvas-interaction',
  'scroll-story': 'motion-interaction-play',
  'scroll-sync': 'utilities-layout',
  'scroll-velocity': 'cursor-text',
  'search-field': 'forms-core',
  'searchable-checkbox-list': 'forms-data',
  'seat-map': 'editors-input',
  'seat-selector': 'dialogs-saas',
  'section-heading': 'saas-marketing',
  'segmented-control': 'controls',
  'select': 'forms-core',
  'selection-toolbar': 'forms-advanced',
  'semver-range': 'developer-parsers',
  'sequence-diagram': 'charts-diagrams',
  'session-list': 'saas-security',
  'session-timeout': 'reliability',
  'settings-section': 'saas-settings',
  'setup-checklist': 'saas-auth',
  'shader-canvas': 'canvas-interaction',
  'share-menu': 'commerce-records',
  'share-permissions': 'motion-interaction-play',
  'shimmer-button': 'ambient',
  'shimmer-text': 'charts-progress',
  'shortcut-recorder': 'inputs',
  'show-more-list': 'foundation-layout-nav',
  'sidebar': 'layout-regions',
  'sidebar-rail': 'layout-regions',
  'sidenotes': 'utilities-layout',
  'signal-strength': 'charts-graph',
  'signature-pad': 'canvas',
  'site-footer': 'saas-marketing',
  'site-header': 'saas-marketing',
  'sla-timer': 'diagrams-scheduling',
  'slide-deck': 'collab-trust',
  'sliding-puzzle': 'games-documents',
  'slope-chart': 'charts-progress',
  'slot-reels': 'physics',
  'smart-crop': 'image-files',
  'snake-game': 'games-documents',
  'snap-guides': 'diagrams-scheduling',
  'social-login-buttons': 'nav-actions-forms',
  'solitaire': 'data-audio-games',
  'sortable-list': 'gestures',
  'sortable-tree': 'canvas-interaction',
  'spaced-repetition': 'data-audio-games',
  'sparkline': 'charts-core',
  'spatial-navigation': 'utilities-layout',
  'spin-wheel': 'play-saas',
  'split-button': 'essentials',
  'split-flap': 'motion-scenes',
  'split-pane': 'essentials',
  'spotlight': 'motion-scenes',
  'sql-builder': 'collab-trust',
  'sso-setup': 'saas-security',
  'stack': 'layout-motion-extras',
  'stack-trace': 'developer-tools',
  'stacked-cards': 'narrative',
  'stagger': 'motion-scenes',
  'star-field': 'generative',
  'stat-card': 'data-display-core',
  'state-view': 'app-patterns',
  'status-strip': 'insight',
  'step-loader': 'charts-progress',
  'stepper': 'navigation',
  'sticker-peel': 'surfaces',
  'sticky': 'foundation-layout-nav',
  'story-progress': 'narrative',
  'streak-counter': 'play',
  'stream-graph': 'charts-graph',
  'stroke-gestures': 'diagrams-scheduling',
  'success-mark': 'feedback',
  'sudoku': 'games-documents',
  'sunburst-chart': 'charts-graph',
  'swipe-deck': 'interactions',
  'swipe-row': 'gestures',
  'swipe-to-confirm': 'feedback-overlays',
  'tab-bar': 'navigation',
  'tab-coordinator': 'text-search-state',
  'table': 'data-display-core',
  'tabs': 'navigation',
  'tag-input': 'forms-core',
  'terminal': 'toybox',
  'testimonial-card': 'saas-marketing',
  'text-link': 'foundation-layout-nav',
  'text-reveal': 'text-effects',
  'text-scramble': 'motion-scenes',
  'theme-scope': 'theming',
  'three-way-merge': 'collab-trust',
  'tic-tac-toe': 'play-saas',
  'ticker': 'motion-core',
  'tilt-card': 'motion-scenes',
  'time-picker': 'date-time',
  'time-range-picker': 'forms-data',
  'time-series-explorer': 'charts-analytics',
  'time-slot-picker': 'forms-extras',
  'timeline': 'data-display-core',
  'timezone-planner': 'games-documents',
  'toast': 'overlays-full',
  'toggle-button': 'structure-extras',
  'toggle-group': 'essentials',
  'toggletip': 'conversation-settings',
  'toolbar': 'controls',
  'tooltip': 'overlays-core',
  'tournament-bracket': 'diagrams-scheduling',
  'trace-waterfall': 'charts-analytics',
  'track-changes': 'editors-input',
  'transcript-view': 'charts-graph',
  'transfer-list': 'forms-extras',
  'transform-box': 'diagrams-scheduling',
  'tree-map': 'insight',
  'tree-select': 'forms-advanced',
  'tree-table': 'data-media',
  'tree-view': 'data-display-rich',
  'trend-delta': 'forms-data',
  'two-factor-setup': 'saas-security',
  'typewriter': 'text-effects',
  'typing-indicator': 'collaboration',
  'undo-stack': 'change',
  'unit-input': 'nav-actions-forms',
  'unsaved-changes-bar': 'nav-actions-forms',
  'update-available': 'feedback-overlays',
  'upgrade-prompt': 'saas-billing',
  'upload-queue': 'charts-progress',
  'url-state': 'text-search-state',
  'usage-meter': 'saas-billing',
  'usage-pricing-calculator': 'play-saas',
  'user-menu': 'saas-workspace',
  'validation-summary': 'change',
  'venn-diagram': 'charts-diagrams',
  'version-history': 'motion-interaction-play',
  'version-switcher': 'layout-motion-extras',
  'vibe-poll': 'play',
  'video-player': 'data-media',
  'violin-plot': 'charts-analytics',
  'virtual-list': 'data-views',
  'vision-simulator': 'utilities-layout',
  'voice-recorder': 'media-capture',
  'voronoi-field': 'canvas-interaction',
  'vote-buttons': 'nav-actions-forms',
  'waterfall-chart': 'charts-statistical',
  'waveform': 'ambient',
  'web-vitals': 'developer-tools',
  'webhook-deliveries': 'saas-settings',
  'webhook-endpoints': 'saas-settings',
  'week-view': 'forms-data',
  'weekday-picker': 'nav-actions-forms',
  'whiteboard': 'canvas-interaction',
  'word-cloud': 'charts-diagrams',
  'word-guess': 'data-audio-games',
  'workspace-switcher': 'saas-workspace',
  'xp-bar': 'play',
  'zip-browser': 'image-files',
}

const cache = new Map<string, ExampleModule>()

/** The examples for one component, or undefined when its page is hand-written. */
export async function loadExamples(slug: string) {
  const owner = OWNER[slug]
  if (!owner) return undefined

  let module = cache.get(owner)
  if (!module) {
    module = (await MODULES[owner]()).demos
    cache.set(owner, module)
  }
  return module[slug]
}

