// GENERATED by scripts/generate-metadata.mjs - do not edit.
//
// The ARIA roles each component renders itself, read off its source. Roles that
// arrive only through a child component are listed on that child, not here.

export const ariaRoles: Record<string, string[]> = {
  "AchievementPop": [
    "alert"
  ],
  "ActivityHeatmap": [
    "grid",
    "gridcell",
    "row"
  ],
  "Alert": [
    "alert"
  ],
  "AlertDialog": [
    "alertdialog"
  ],
  "ApprovalChain": [
    "group",
    "status"
  ],
  "AudioVisualizer": [
    "status"
  ],
  "AvatarGroup": [
    "group"
  ],
  "BulkActionBar": [
    "group",
    "status"
  ],
  "ButtonGroup": [
    "group"
  ],
  "Calendar": [
    "grid",
    "gridcell"
  ],
  "Carousel": [
    "group"
  ],
  "CartesianChart": [
    "img",
    "status"
  ],
  "CategoryBar": [
    "img"
  ],
  "CoachTour": [
    "dialog",
    "modal",
    "status"
  ],
  "CodeBlock": [
    "status"
  ],
  "ColorPicker": [
    "group"
  ],
  "Combobox": [
    "combobox",
    "listbox",
    "option"
  ],
  "CommandPalette": [
    "combobox",
    "dialog",
    "listbox",
    "modal",
    "option"
  ],
  "ConnectionBanner": [
    "status"
  ],
  "ConsentManager": [
    "group",
    "status"
  ],
  "ContextMenu": [
    "menu",
    "menuitem"
  ],
  "CopyButton": [
    "status"
  ],
  "Countdown": [
    "timer"
  ],
  "CoverFlow": [
    "listbox",
    "option"
  ],
  "Cropper": [
    "group"
  ],
  "CubeCarousel": [
    "group"
  ],
  "DataFreshness": [
    "status"
  ],
  "DataTable": [
    "status"
  ],
  "DatePicker": [
    "combobox"
  ],
  "DateRangePicker": [
    "combobox"
  ],
  "DaySchedule": [
    "group"
  ],
  "DiceRoller": [
    "status"
  ],
  "DiffSummary": [
    "group",
    "status"
  ],
  "Dock": [
    "toolbar"
  ],
  "DonutChart": [
    "img"
  ],
  "Drawer": [
    "dialog",
    "modal"
  ],
  "EmojiSlider": [
    "slider"
  ],
  "ErrorState": [
    "alert"
  ],
  "FileUpload": [
    "alert"
  ],
  "FilterBar": [
    "search",
    "status"
  ],
  "FlipBook": [
    "group"
  ],
  "GooeyLoader": [
    "status"
  ],
  "HoldToConfirm": [
    "status"
  ],
  "HoverCard": [
    "dialog"
  ],
  "ImageCompare": [
    "slider"
  ],
  "ImportMapper": [
    "group",
    "status"
  ],
  "InlineMessage": [
    "status"
  ],
  "InputOTP": [
    "group"
  ],
  "KanbanBoard": [
    "group",
    "status"
  ],
  "Knob": [
    "slider"
  ],
  "LayerStack": [
    "radio",
    "radiogroup"
  ],
  "Lightbox": [
    "dialog",
    "modal",
    "status"
  ],
  "LiveChart": [
    "status"
  ],
  "LoadingOverlay": [
    "status"
  ],
  "MagicTabs": [
    "tab",
    "tablist"
  ],
  "MarqueeSelect": [
    "group",
    "status"
  ],
  "MaskedValue": [
    "status"
  ],
  "MentionInput": [
    "listbox",
    "option"
  ],
  "Menu": [
    "menu",
    "menuitem"
  ],
  "Meter": [
    "progressbar"
  ],
  "MetricSpotlight": [
    "radio",
    "radiogroup"
  ],
  "MiniMap": [
    "group"
  ],
  "Modal": [
    "modal"
  ],
  "MorphDialog": [
    "dialog",
    "modal"
  ],
  "MultiSelect": [
    "listbox"
  ],
  "NotificationCenter": [
    "status"
  ],
  "OrbitRing": [
    "group"
  ],
  "Pagination": [
    "status"
  ],
  "PanZoom": [
    "application"
  ],
  "PasswordStrength": [
    "status"
  ],
  "PermissionGate": [
    "note"
  ],
  "PianoKeys": [
    "group",
    "status"
  ],
  "PinPad": [
    "group",
    "status"
  ],
  "PixelCanvas": [
    "group"
  ],
  "Popover": [
    "dialog"
  ],
  "PresenceBar": [
    "group",
    "status"
  ],
  "Progress": [
    "progressbar"
  ],
  "ProgressChart": [
    "img"
  ],
  "ProgressRing": [
    "progressbar"
  ],
  "PullToRefresh": [
    "status"
  ],
  "QRCode": [
    "img"
  ],
  "QuickActions": [
    "list"
  ],
  "RadarChart": [
    "img"
  ],
  "RadialMenu": [
    "menu",
    "menuitem"
  ],
  "RateLimitMeter": [
    "progressbar",
    "status"
  ],
  "Rating": [
    "img",
    "radiogroup"
  ],
  "ReactionBar": [
    "group"
  ],
  "RetryQueue": [
    "status"
  ],
  "RotatingWord": [
    "status"
  ],
  "SankeyFlow": [
    "img"
  ],
  "SaveIndicator": [
    "status"
  ],
  "ScrollProgress": [
    "progressbar"
  ],
  "SegmentedControl": [
    "radio",
    "radiogroup"
  ],
  "Select": [
    "combobox",
    "listbox",
    "option"
  ],
  "SessionTimeout": [
    "alertdialog",
    "modal"
  ],
  "ShortcutRecorder": [
    "status"
  ],
  "SignaturePad": [
    "img",
    "status"
  ],
  "SlotReels": [
    "status"
  ],
  "SortableList": [
    "status"
  ],
  "Sparkline": [
    "img"
  ],
  "Spinner": [
    "status"
  ],
  "SplitPane": [
    "separator"
  ],
  "StatusStrip": [
    "img"
  ],
  "StoryProgress": [
    "progressbar"
  ],
  "SuccessMark": [
    "status"
  ],
  "SwipeDeck": [
    "group"
  ],
  "Switch": [
    "switch"
  ],
  "Tabs": [
    "tab",
    "tablist",
    "tabpanel"
  ],
  "TagInput": [
    "status"
  ],
  "Ticker": [
    "status"
  ],
  "TimePicker": [
    "combobox",
    "listbox",
    "option"
  ],
  "Toast": [
    "region",
    "status"
  ],
  "ToggleGroup": [
    "group"
  ],
  "Toolbar": [
    "toolbar"
  ],
  "Tooltip": [
    "tooltip"
  ],
  "TreeMap": [
    "group"
  ],
  "TreeView": [
    "tree",
    "treeitem"
  ],
  "UndoStack": [
    "group",
    "menu",
    "menuitem",
    "status"
  ],
  "ValidationSummary": [
    "alert"
  ],
  "VibePoll": [
    "group",
    "status"
  ],
  "VirtualList": [
    "list",
    "listitem",
    "presentation"
  ],
  "Waveform": [
    "img"
  ],
  "XPBar": [
    "progressbar",
    "status"
  ]
}
