// GENERATED by scripts/generate-metadata.mjs - do not edit.
//
// The ARIA roles each component renders itself, read off its source. Roles that
// arrive only through a child component are listed on that child, not here.

export const ariaRoles: Record<string, string[]> = {
  "A11yInspector": [
    "button",
    "checkbox",
    "combobox",
    "heading",
    "img",
    "link",
    "radio",
    "searchbox",
    "slider",
    "spinbutton",
    "status",
    "switch",
    "textbox"
  ],
  "AccessDeniedState": [
    "alert",
    "status"
  ],
  "AccessExplainer": [
    "status"
  ],
  "AchievementPop": [
    "alert"
  ],
  "ActivityHeatmap": [
    "grid",
    "gridcell",
    "row"
  ],
  "AddToCalendar": [
    "menu",
    "menuitem"
  ],
  "AddressInput": [
    "combobox",
    "listbox",
    "option",
    "status"
  ],
  "AgendaList": [
    "region"
  ],
  "Alert": [
    "alert"
  ],
  "AlertDialog": [
    "alertdialog"
  ],
  "AlphabetIndex": [
    "toolbar"
  ],
  "AnsiOutput": [
    "log"
  ],
  "ApiKeyManager": [
    "status"
  ],
  "ApprovalChain": [
    "group",
    "status"
  ],
  "AudioPlayer": [
    "group"
  ],
  "AudioTrimmer": [
    "slider"
  ],
  "AudioVisualizer": [
    "status"
  ],
  "AuthCard": [
    "separator"
  ],
  "AvatarGroup": [
    "group"
  ],
  "AvatarUpload": [
    "alert",
    "group",
    "status"
  ],
  "Banner": [
    "region"
  ],
  "BeeswarmChart": [
    "img"
  ],
  "BoxPlot": [
    "img"
  ],
  "BpmDetector": [
    "alert",
    "img",
    "status"
  ],
  "BulkActionBar": [
    "group",
    "status"
  ],
  "BulletChart": [
    "img"
  ],
  "ButtonGroup": [
    "group"
  ],
  "Calendar": [
    "grid",
    "gridcell"
  ],
  "CameraCapture": [
    "group",
    "status"
  ],
  "CandlestickChart": [
    "img"
  ],
  "CaptionEditor": [
    "alert"
  ],
  "Carousel": [
    "group"
  ],
  "CartesianChart": [
    "img",
    "status"
  ],
  "CascadeSelect": [
    "combobox",
    "listbox",
    "option",
    "status"
  ],
  "CategoryBar": [
    "img"
  ],
  "ChatThread": [
    "log",
    "separator"
  ],
  "ChessBoard": [
    "dialog",
    "grid",
    "gridcell",
    "group",
    "row",
    "status"
  ],
  "ChordDiagram": [
    "img"
  ],
  "ChoroplethMap": [
    "img"
  ],
  "ClickHeatmap": [
    "img"
  ],
  "CoachTour": [
    "dialog",
    "modal",
    "status"
  ],
  "CodeBlock": [
    "status"
  ],
  "CodeTabs": [
    "tab",
    "tablist",
    "tabpanel"
  ],
  "CohortRetention": [
    "grid"
  ],
  "ColorPicker": [
    "group"
  ],
  "ColorSwatchPicker": [
    "radio",
    "radiogroup"
  ],
  "Combobox": [
    "combobox",
    "listbox",
    "option"
  ],
  "CommandPalette": [
    "combobox",
    "dialog",
    "listbox",
    "modal",
    "option"
  ],
  "CommentAnchors": [
    "region"
  ],
  "CommitGraph": [
    "listbox",
    "option"
  ],
  "ConfirmPopover": [
    "alert"
  ],
  "ConnectionBanner": [
    "status"
  ],
  "ConsentManager": [
    "group",
    "status"
  ],
  "ContextMenu": [
    "menu",
    "menuitem"
  ],
  "ContourPlot": [
    "img"
  ],
  "ControlChart": [
    "img"
  ],
  "CookieBanner": [
    "region"
  ],
  "CopyButton": [
    "status"
  ],
  "Countdown": [
    "timer"
  ],
  "CoverFlow": [
    "listbox",
    "option"
  ],
  "CreditCardInput": [
    "group",
    "status"
  ],
  "CronEditor": [
    "group"
  ],
  "Cropper": [
    "group"
  ],
  "Crossword": [
    "grid",
    "gridcell",
    "group",
    "row",
    "status"
  ],
  "CspEvaluator": [
    "region",
    "status"
  ],
  "CsvImport": [
    "alert",
    "progressbar",
    "region",
    "status"
  ],
  "CubeCarousel": [
    "group"
  ],
  "DashboardGrid": [
    "group"
  ],
  "DataFreshness": [
    "status"
  ],
  "DataProfile": [
    "img"
  ],
  "DataTable": [
    "status"
  ],
  "DatePicker": [
    "combobox",
    "grid"
  ],
  "DateRangePicker": [
    "combobox",
    "grid"
  ],
  "DateTimePicker": [
    "alert",
    "grid"
  ],
  "DaySchedule": [
    "group"
  ],
  "Dendrogram": [
    "img",
    "slider"
  ],
  "DiceRoller": [
    "status"
  ],
  "DictationButton": [
    "alert"
  ],
  "DiffSummary": [
    "group",
    "status"
  ],
  "Dock": [
    "toolbar"
  ],
  "DockLayout": [
    "region",
    "separator",
    "tab",
    "tablist",
    "tabpanel"
  ],
  "DocumentScanner": [
    "button",
    "group",
    "img",
    "status"
  ],
  "DomainSetup": [
    "status"
  ],
  "DonutChart": [
    "img"
  ],
  "DownloadButton": [
    "progressbar",
    "status"
  ],
  "DraftRecovery": [
    "region"
  ],
  "Drawer": [
    "dialog",
    "modal"
  ],
  "DumbbellChart": [
    "img"
  ],
  "DurationInput": [
    "group",
    "spinbutton"
  ],
  "EasingEditor": [
    "group",
    "slider"
  ],
  "EditableTable": [
    "alert",
    "columnheader",
    "grid",
    "gridcell"
  ],
  "EmailViewer": [
    "status"
  ],
  "EmojiPicker": [
    "grid",
    "gridcell",
    "group",
    "row",
    "status",
    "tab",
    "tablist",
    "tabpanel"
  ],
  "EmojiSlider": [
    "slider"
  ],
  "Equalizer": [
    "group",
    "img",
    "slider",
    "status"
  ],
  "ErrorBoundary": [
    "alert"
  ],
  "ErrorBudget": [
    "img"
  ],
  "ErrorState": [
    "alert"
  ],
  "EventCalendar": [
    "columnheader",
    "grid",
    "gridcell",
    "row"
  ],
  "ExifViewer": [
    "alert",
    "status"
  ],
  "ExperimentResults": [
    "status"
  ],
  "FaqSection": [
    "status"
  ],
  "FeatureFlags": [
    "status"
  ],
  "FeedbackWidget": [
    "status"
  ],
  "FileList": [
    "alert"
  ],
  "FileUpload": [
    "alert"
  ],
  "FilterBar": [
    "search",
    "status"
  ],
  "FilterBuilder": [
    "group"
  ],
  "FindInPage": [
    "search",
    "status"
  ],
  "FlameGraph": [
    "img"
  ],
  "FlipBook": [
    "group"
  ],
  "FloatingPanel": [
    "dialog",
    "modal"
  ],
  "FlowDiagram": [
    "img"
  ],
  "FlowField": [
    "img"
  ],
  "ForecastChart": [
    "img"
  ],
  "FormulaEditor": [
    "combobox",
    "listbox",
    "option",
    "status"
  ],
  "FractalExplorer": [
    "application",
    "status"
  ],
  "FullTextSearch": [
    "combobox",
    "listbox",
    "option",
    "status"
  ],
  "FullscreenDialog": [
    "dialog",
    "modal"
  ],
  "FuzzyFinder": [
    "combobox",
    "listbox",
    "option",
    "status"
  ],
  "Game2048": [
    "group",
    "status"
  ],
  "GameOfLife": [
    "application",
    "status"
  ],
  "GanttChart": [
    "img"
  ],
  "GifRecorder": [
    "progressbar",
    "status"
  ],
  "GooeyLoader": [
    "status"
  ],
  "HelpPanel": [
    "status"
  ],
  "HexViewer": [
    "alert",
    "grid",
    "gridcell",
    "presentation",
    "row",
    "rowgroup",
    "rowheader",
    "status"
  ],
  "HexbinChart": [
    "img"
  ],
  "Histogram": [
    "img"
  ],
  "HoldToConfirm": [
    "status"
  ],
  "HoverCard": [
    "dialog"
  ],
  "ImageAdjust": [
    "button",
    "group",
    "img"
  ],
  "ImageAnnotator": [
    "application",
    "status"
  ],
  "ImageCompare": [
    "slider"
  ],
  "ImageDiff": [
    "group",
    "img"
  ],
  "ImageGallery": [
    "tab",
    "tablist",
    "tabpanel"
  ],
  "ImportMapper": [
    "group",
    "status"
  ],
  "InfiniteScroll": [
    "status"
  ],
  "InlineCompletion": [
    "status"
  ],
  "InlineMessage": [
    "status"
  ],
  "InputOTP": [
    "group"
  ],
  "Joystick": [
    "application"
  ],
  "JsonDiff": [
    "status"
  ],
  "JsonQuery": [
    "group",
    "region",
    "status"
  ],
  "JwtInspector": [
    "alert",
    "status"
  ],
  "KanbanBoard": [
    "group",
    "status"
  ],
  "KaplanMeierChart": [
    "img"
  ],
  "KeyboardShortcutsDialog": [
    "status"
  ],
  "Knob": [
    "slider"
  ],
  "LanguageSwitcher": [
    "listbox",
    "option",
    "status"
  ],
  "LayerStack": [
    "radio",
    "radiogroup"
  ],
  "Lightbox": [
    "dialog",
    "modal",
    "status"
  ],
  "LikertScale": [
    "group",
    "radiogroup"
  ],
  "LinkPreview": [
    "tooltip"
  ],
  "LiveChart": [
    "status"
  ],
  "LoadingOverlay": [
    "status"
  ],
  "LocaleSettings": [
    "status"
  ],
  "LogViewer": [
    "group",
    "list",
    "listitem",
    "region",
    "status"
  ],
  "LogoCloud": [
    "img"
  ],
  "LoudnessMeter": [
    "alert",
    "group",
    "slider",
    "status"
  ],
  "MagicTabs": [
    "tab",
    "tablist"
  ],
  "Magnifier": [
    "group"
  ],
  "MaintenanceNotice": [
    "status"
  ],
  "MarkdownEditor": [
    "toolbar"
  ],
  "MarqueeSelect": [
    "group",
    "status"
  ],
  "MaskedValue": [
    "status"
  ],
  "MathFormula": [
    "math"
  ],
  "MatrixHeatmap": [
    "img"
  ],
  "MeasureTool": [
    "application",
    "button",
    "status"
  ],
  "MemberList": [
    "status"
  ],
  "MemoryGame": [
    "grid",
    "gridcell",
    "row",
    "status"
  ],
  "MentionInput": [
    "listbox",
    "option"
  ],
  "Menu": [
    "menu",
    "menuitem"
  ],
  "Menubar": [
    "checkbox",
    "menu",
    "menubar",
    "menuitem",
    "menuitemcheckbox",
    "none",
    "separator"
  ],
  "Meter": [
    "progressbar"
  ],
  "MetricSpotlight": [
    "radio",
    "radiogroup"
  ],
  "Metronome": [
    "combobox",
    "group",
    "listbox",
    "status"
  ],
  "MindMap": [
    "tree",
    "treeitem"
  ],
  "Minesweeper": [
    "grid",
    "gridcell",
    "row",
    "status"
  ],
  "MiniMap": [
    "group"
  ],
  "Modal": [
    "modal"
  ],
  "ModelViewer": [
    "alert",
    "application"
  ],
  "MonthPicker": [
    "grid",
    "gridcell",
    "row"
  ],
  "MorphDialog": [
    "dialog",
    "modal"
  ],
  "MorphingText": [
    "status"
  ],
  "MultiSelect": [
    "listbox"
  ],
  "NaturalDateInput": [
    "grid",
    "status"
  ],
  "NavigationProgress": [
    "progressbar"
  ],
  "NetworkGraph": [
    "img"
  ],
  "NewsletterSignup": [
    "status"
  ],
  "NodeEditor": [
    "group"
  ],
  "NotificationCenter": [
    "status"
  ],
  "NotificationPreferences": [
    "status"
  ],
  "NpsSurvey": [
    "status"
  ],
  "OrbitRing": [
    "group"
  ],
  "OrgChart": [
    "tree",
    "treeitem"
  ],
  "Pagination": [
    "status"
  ],
  "PairwiseRanker": [
    "group"
  ],
  "PanZoom": [
    "application"
  ],
  "PanoramaViewer": [
    "application",
    "status"
  ],
  "ParallelCoordinates": [
    "group",
    "img"
  ],
  "ParetoChart": [
    "img"
  ],
  "PasskeyManager": [
    "alert",
    "status"
  ],
  "PasswordStrength": [
    "status"
  ],
  "PathEditor": [
    "alert",
    "button",
    "group",
    "status"
  ],
  "PatternLock": [
    "application",
    "status"
  ],
  "PeerLink": [
    "alert",
    "log",
    "status"
  ],
  "PermissionGate": [
    "note"
  ],
  "PermissionPrompt": [
    "group",
    "status"
  ],
  "PianoKeys": [
    "group",
    "status"
  ],
  "PictureInPicture": [
    "note",
    "status"
  ],
  "PinPad": [
    "group",
    "status"
  ],
  "PitchTuner": [
    "group",
    "meter",
    "status"
  ],
  "PivotTable": [
    "region"
  ],
  "PixelCanvas": [
    "group"
  ],
  "Popover": [
    "dialog"
  ],
  "PresenceBar": [
    "group",
    "status"
  ],
  "PricingTable": [
    "status"
  ],
  "ProductCard": [
    "radiogroup",
    "status"
  ],
  "ProductVariantPicker": [
    "radio",
    "radiogroup",
    "status"
  ],
  "Progress": [
    "progressbar"
  ],
  "ProgressChart": [
    "img"
  ],
  "ProgressRing": [
    "progressbar"
  ],
  "PullToRefresh": [
    "status"
  ],
  "QRCode": [
    "img"
  ],
  "QueryBar": [
    "combobox",
    "listbox",
    "option"
  ],
  "QuestionQueue": [
    "status"
  ],
  "QuickActions": [
    "list"
  ],
  "RadarChart": [
    "img"
  ],
  "RadialBarChart": [
    "img"
  ],
  "RadialMenu": [
    "menu",
    "menuitem",
    "none"
  ],
  "RateLimitMeter": [
    "progressbar",
    "status"
  ],
  "Rating": [
    "img",
    "radiogroup"
  ],
  "ReactionBar": [
    "group"
  ],
  "ReadAloud": [
    "group"
  ],
  "ReadabilityMeter": [
    "status"
  ],
  "RecentItems": [
    "status"
  ],
  "RecordMerge": [
    "status"
  ],
  "RecurrenceEditor": [
    "group",
    "radiogroup"
  ],
  "Redactor": [
    "group",
    "status"
  ],
  "RegexTester": [
    "group",
    "region",
    "status"
  ],
  "ReleaseNotesModal": [
    "status"
  ],
  "RepeaterField": [
    "group",
    "status"
  ],
  "ResizableBox": [
    "separator"
  ],
  "ResourceScheduler": [
    "group"
  ],
  "RetryQueue": [
    "status"
  ],
  "ReviewSummary": [
    "img"
  ],
  "RichTextEditor": [
    "textbox",
    "toolbar"
  ],
  "RoadmapBoard": [
    "status"
  ],
  "RotatingWord": [
    "status"
  ],
  "SankeyFlow": [
    "img"
  ],
  "SaveIndicator": [
    "status"
  ],
  "SavedViews": [
    "status"
  ],
  "ScatterChart": [
    "img"
  ],
  "SchemaForm": [
    "status"
  ],
  "ScopedSearch": [
    "combobox",
    "listbox",
    "option",
    "search",
    "status"
  ],
  "ScrollArea": [
    "region"
  ],
  "ScrollProgress": [
    "progressbar"
  ],
  "ScrollSequence": [
    "img",
    "progressbar"
  ],
  "ScrollSync": [
    "region"
  ],
  "SearchableCheckboxList": [
    "group"
  ],
  "SeatMap": [
    "checkbox",
    "group",
    "status"
  ],
  "SeatSelector": [
    "status"
  ],
  "SegmentedControl": [
    "radio",
    "radiogroup"
  ],
  "Select": [
    "combobox",
    "listbox",
    "option"
  ],
  "SelectionToolbar": [
    "status",
    "toolbar"
  ],
  "SemverRange": [
    "status"
  ],
  "SequenceDiagram": [
    "img"
  ],
  "SessionTimeout": [
    "alertdialog",
    "modal"
  ],
  "SettingsSection": [
    "status"
  ],
  "ShaderCanvas": [
    "alert",
    "img"
  ],
  "ShareMenu": [
    "menu",
    "menuitem",
    "status"
  ],
  "SharePermissions": [
    "status"
  ],
  "ShortcutRecorder": [
    "status"
  ],
  "Sidenotes": [
    "note"
  ],
  "SignalStrength": [
    "img"
  ],
  "SignaturePad": [
    "img",
    "status"
  ],
  "SlaTimer": [
    "alert",
    "meter"
  ],
  "SlideDeck": [
    "group",
    "status"
  ],
  "SlidingPuzzle": [
    "group",
    "status"
  ],
  "SlopeChart": [
    "img"
  ],
  "SlotReels": [
    "status"
  ],
  "SmartCrop": [
    "group",
    "status"
  ],
  "SnakeGame": [
    "application",
    "status"
  ],
  "SnapGuides": [
    "group"
  ],
  "SocialLoginButtons": [
    "group"
  ],
  "Solitaire": [
    "button",
    "group",
    "status"
  ],
  "SortableList": [
    "status"
  ],
  "SortableTree": [
    "tree",
    "treeitem"
  ],
  "SpacedRepetition": [
    "group",
    "status"
  ],
  "Sparkline": [
    "img"
  ],
  "SpatialNavigation": [
    "combobox",
    "grid",
    "group",
    "listbox",
    "menu",
    "menubar",
    "radiogroup",
    "slider",
    "spinbutton",
    "tablist",
    "textbox",
    "tree"
  ],
  "SpinWheel": [
    "img",
    "status"
  ],
  "Spinner": [
    "status"
  ],
  "SplitPane": [
    "separator"
  ],
  "SqlBuilder": [
    "region",
    "status"
  ],
  "StackTrace": [
    "status"
  ],
  "StatusStrip": [
    "img"
  ],
  "StepLoader": [
    "status"
  ],
  "StoryProgress": [
    "progressbar"
  ],
  "StreamGraph": [
    "img"
  ],
  "StrokeGestures": [
    "img",
    "status"
  ],
  "SuccessMark": [
    "status"
  ],
  "Sudoku": [
    "grid",
    "gridcell",
    "group",
    "row",
    "status"
  ],
  "SunburstChart": [
    "img"
  ],
  "SwipeDeck": [
    "group"
  ],
  "SwipeToConfirm": [
    "slider",
    "status"
  ],
  "Switch": [
    "switch"
  ],
  "TabCoordinator": [
    "log",
    "status"
  ],
  "Tabs": [
    "tab",
    "tablist",
    "tabpanel"
  ],
  "TagInput": [
    "status"
  ],
  "TestimonialCard": [
    "img"
  ],
  "TextLink": [
    "link"
  ],
  "ThreeWayMerge": [
    "group",
    "region",
    "status"
  ],
  "TicTacToe": [
    "grid",
    "gridcell",
    "row",
    "status"
  ],
  "Ticker": [
    "status"
  ],
  "TimePicker": [
    "combobox",
    "listbox",
    "option"
  ],
  "TimeRangePicker": [
    "group"
  ],
  "TimeSeriesExplorer": [
    "img",
    "slider"
  ],
  "TimeSlotPicker": [
    "group",
    "radio",
    "radiogroup"
  ],
  "TimezonePlanner": [
    "slider",
    "status"
  ],
  "Toast": [
    "region",
    "status"
  ],
  "ToggleGroup": [
    "group"
  ],
  "Toggletip": [
    "status"
  ],
  "Toolbar": [
    "toolbar"
  ],
  "Tooltip": [
    "tooltip"
  ],
  "TournamentBracket": [
    "group",
    "status"
  ],
  "TraceWaterfall": [
    "tree",
    "treeitem"
  ],
  "TrackChanges": [
    "button",
    "group",
    "status"
  ],
  "TranscriptView": [
    "status"
  ],
  "TransferList": [
    "group",
    "listbox",
    "option",
    "status"
  ],
  "TransformBox": [
    "group"
  ],
  "TreeMap": [
    "group"
  ],
  "TreeSelect": [
    "combobox",
    "tree",
    "treeitem"
  ],
  "TreeTable": [
    "columnheader",
    "gridcell",
    "treegrid"
  ],
  "TreeView": [
    "tree",
    "treeitem"
  ],
  "UndoStack": [
    "group",
    "menu",
    "menuitem",
    "status"
  ],
  "UnitInput": [
    "spinbutton"
  ],
  "UnsavedChangesBar": [
    "alert",
    "dialog",
    "region",
    "status"
  ],
  "UpdateAvailable": [
    "status"
  ],
  "UploadQueue": [
    "status"
  ],
  "UsageMeter": [
    "progressbar"
  ],
  "UsagePricingCalculator": [
    "status"
  ],
  "UserMenu": [
    "menu",
    "menuitem"
  ],
  "ValidationSummary": [
    "alert"
  ],
  "VennDiagram": [
    "img"
  ],
  "VersionSwitcher": [
    "listbox",
    "note",
    "option"
  ],
  "VibePoll": [
    "group",
    "status"
  ],
  "VideoPlayer": [
    "group",
    "status"
  ],
  "ViolinPlot": [
    "img"
  ],
  "VirtualList": [
    "list",
    "listitem",
    "presentation"
  ],
  "VoiceRecorder": [
    "group",
    "status"
  ],
  "VoteButtons": [
    "group"
  ],
  "WaterfallChart": [
    "img"
  ],
  "Waveform": [
    "img"
  ],
  "WebVitals": [
    "status"
  ],
  "WeekView": [
    "group",
    "region"
  ],
  "WeekdayPicker": [
    "group"
  ],
  "Whiteboard": [
    "application",
    "toolbar"
  ],
  "WordCloud": [
    "img"
  ],
  "WordGuess": [
    "group",
    "status"
  ],
  "WorkspaceSwitcher": [
    "listbox",
    "option"
  ],
  "XPBar": [
    "progressbar",
    "status"
  ],
  "ZipBrowser": [
    "alert",
    "tree",
    "treeitem"
  ]
}
