// GENERATED by scripts/generate-metadata.mjs - do not edit.
//
// Direct edges only; the transitive set is resolved by `dependenciesOf`. Kept
// as edges rather than closures so the file stays readable and small.

export interface ComponentDependencies {
  /** Files this component is made of, relative to the library root. */
  files: string[]
  /** Sibling components it imports. */
  internal: string[]
  /** Shared modules it imports, relative to the library root. */
  shared: string[]
  /** npm packages it imports. */
  external: string[]
}

export const dependencies: Record<string, ComponentDependencies> = {
  "Accordion": {
    "files": [
      "components/Accordion/Accordion.tsx",
      "components/Accordion/index.ts"
    ],
    "internal": [
      "Collapsible"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "AchievementPop": {
    "files": [
      "components/AchievementPop/AchievementPop.tsx",
      "components/AchievementPop/index.ts"
    ],
    "internal": [
      "Portal",
      "Text"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "ActionSheet": {
    "files": [
      "components/ActionSheet/ActionSheet.tsx",
      "components/ActionSheet/index.ts"
    ],
    "internal": [
      "Divider",
      "Drawer",
      "Text"
    ],
    "shared": [
      "lib/cn.ts",
      "lib/types.ts"
    ],
    "external": []
  },
  "ActivityFeed": {
    "files": [
      "components/ActivityFeed/ActivityFeed.tsx",
      "components/ActivityFeed/index.ts"
    ],
    "internal": [
      "Avatar",
      "Collapse",
      "DescriptionList",
      "IconTile",
      "List",
      "ListItem",
      "Text"
    ],
    "shared": [
      "components/internal/icons.tsx",
      "lib/cn.ts",
      "lib/types.ts"
    ],
    "external": [
      "react"
    ]
  },
  "ActivityHeatmap": {
    "files": [
      "components/ActivityHeatmap/ActivityHeatmap.tsx",
      "components/ActivityHeatmap/index.ts"
    ],
    "internal": [
      "Text",
      "Tooltip",
      "VisuallyHidden"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "Alert": {
    "files": [
      "components/Alert/Alert.tsx",
      "components/Alert/index.ts"
    ],
    "internal": [
      "IconButton",
      "Text"
    ],
    "shared": [
      "components/internal/icons.tsx",
      "lib/cn.ts",
      "lib/types.ts"
    ],
    "external": [
      "react"
    ]
  },
  "AlertDialog": {
    "files": [
      "components/AlertDialog/AlertDialog.tsx",
      "components/AlertDialog/index.ts"
    ],
    "internal": [
      "Button",
      "Modal"
    ],
    "shared": [],
    "external": [
      "react"
    ]
  },
  "AmountField": {
    "files": [
      "components/AmountField/AmountField.tsx",
      "components/AmountField/index.ts"
    ],
    "internal": [
      "Input",
      "Select",
      "Surface",
      "Text"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "AnchorNav": {
    "files": [
      "components/AnchorNav/AnchorNav.tsx",
      "components/AnchorNav/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "AnimatedBeam": {
    "files": [
      "components/AnimatedBeam/AnimatedBeam.tsx",
      "components/AnimatedBeam/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "AnimatedNumber": {
    "files": [
      "components/AnimatedNumber/AnimatedNumber.tsx",
      "components/AnimatedNumber/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "AppShell": {
    "files": [
      "components/AppShell/AppShell.tsx",
      "components/AppShell/index.ts"
    ],
    "internal": [
      "SkipLink"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "ApprovalChain": {
    "files": [
      "components/ApprovalChain/ApprovalChain.tsx",
      "components/ApprovalChain/index.ts"
    ],
    "internal": [
      "Avatar",
      "Button",
      "Meter",
      "StatusDot",
      "Text"
    ],
    "shared": [
      "lib/cn.ts",
      "lib/time.ts"
    ],
    "external": []
  },
  "AreaChart": {
    "files": [
      "components/AreaChart/AreaChart.tsx",
      "components/AreaChart/index.ts"
    ],
    "internal": [
      "CartesianChart"
    ],
    "shared": [],
    "external": [
      "react"
    ]
  },
  "AsciiImage": {
    "files": [
      "components/AsciiImage/AsciiImage.tsx",
      "components/AsciiImage/index.ts"
    ],
    "internal": [
      "VisuallyHidden"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "AudioVisualizer": {
    "files": [
      "components/AudioVisualizer/AudioVisualizer.tsx",
      "components/AudioVisualizer/index.ts"
    ],
    "internal": [
      "Text",
      "VisuallyHidden"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "AuditTrail": {
    "files": [
      "components/AuditTrail/AuditTrail.tsx",
      "components/AuditTrail/index.ts"
    ],
    "internal": [
      "Avatar",
      "Collapse",
      "Text"
    ],
    "shared": [
      "lib/cn.ts",
      "lib/time.ts"
    ],
    "external": [
      "react"
    ]
  },
  "AuroraSurface": {
    "files": [
      "components/AuroraSurface/AuroraSurface.tsx",
      "components/AuroraSurface/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "Avatar": {
    "files": [
      "components/Avatar/Avatar.tsx",
      "components/Avatar/index.ts"
    ],
    "internal": [
      "VisuallyHidden"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "AvatarGroup": {
    "files": [
      "components/AvatarGroup/AvatarGroup.tsx",
      "components/AvatarGroup/index.ts"
    ],
    "internal": [
      "Avatar",
      "VisuallyHidden"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": []
  },
  "BackButton": {
    "files": [
      "components/BackButton/BackButton.tsx",
      "components/BackButton/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts"
    ],
    "external": []
  },
  "Badge": {
    "files": [
      "components/Badge/Badge.tsx",
      "components/Badge/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "Banner": {
    "files": [
      "components/Banner/Banner.tsx",
      "components/Banner/index.ts"
    ],
    "internal": [
      "IconButton",
      "Text"
    ],
    "shared": [
      "components/internal/icons.tsx",
      "lib/cn.ts",
      "lib/types.ts"
    ],
    "external": [
      "react"
    ]
  },
  "BarChart": {
    "files": [
      "components/BarChart/BarChart.tsx",
      "components/BarChart/index.ts"
    ],
    "internal": [
      "CartesianChart"
    ],
    "shared": [],
    "external": []
  },
  "BarList": {
    "files": [
      "components/BarList/BarList.tsx",
      "components/BarList/index.ts"
    ],
    "internal": [
      "Text"
    ],
    "shared": [
      "lib/cn.ts",
      "lib/types.ts"
    ],
    "external": []
  },
  "BentoGrid": {
    "files": [
      "components/BentoGrid/BentoGrid.tsx",
      "components/BentoGrid/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "BlobMorph": {
    "files": [
      "components/BlobMorph/BlobMorph.tsx",
      "components/BlobMorph/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts",
      "lib/motion.ts"
    ],
    "external": [
      "react"
    ]
  },
  "BoidsFlock": {
    "files": [
      "components/BoidsFlock/BoidsFlock.tsx",
      "components/BoidsFlock/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts",
      "lib/motion.ts"
    ],
    "external": [
      "react"
    ]
  },
  "BorderBeam": {
    "files": [
      "components/BorderBeam/BorderBeam.tsx",
      "components/BorderBeam/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "Breadcrumb": {
    "files": [
      "components/Breadcrumb/Breadcrumb.tsx",
      "components/Breadcrumb/index.ts"
    ],
    "internal": [
      "Text"
    ],
    "shared": [
      "components/internal/icons.tsx",
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "BulkActionBar": {
    "files": [
      "components/BulkActionBar/BulkActionBar.tsx",
      "components/BulkActionBar/index.ts"
    ],
    "internal": [
      "Button",
      "Surface",
      "Text",
      "VisuallyHidden"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "Button": {
    "files": [
      "components/Button/Button.tsx",
      "components/Button/index.ts"
    ],
    "internal": [
      "Spinner"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "ButtonGroup": {
    "files": [
      "components/ButtonGroup/ButtonGroup.tsx",
      "components/ButtonGroup/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "Calendar": {
    "files": [
      "components/Calendar/Calendar.tsx",
      "components/Calendar/index.ts"
    ],
    "internal": [
      "IconButton",
      "Text",
      "VisuallyHidden"
    ],
    "shared": [
      "components/internal/icons.tsx",
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "Card": {
    "files": [
      "components/Card/Card.tsx",
      "components/Card/index.ts"
    ],
    "internal": [
      "Surface",
      "Text"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "CardDeck": {
    "files": [
      "components/CardDeck/CardDeck.tsx",
      "components/CardDeck/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "Carousel": {
    "files": [
      "components/Carousel/Carousel.tsx",
      "components/Carousel/index.ts",
      "components/Carousel/useCarousel.ts"
    ],
    "internal": [
      "IconButton"
    ],
    "shared": [
      "components/internal/icons.tsx",
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "CartesianChart": {
    "files": [
      "components/CartesianChart/CartesianChart.tsx",
      "components/CartesianChart/index.ts"
    ],
    "internal": [
      "ChartTooltip",
      "Legend",
      "Text",
      "VisuallyHidden"
    ],
    "shared": [
      "lib/chart.ts",
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "CategoryBar": {
    "files": [
      "components/CategoryBar/CategoryBar.tsx",
      "components/CategoryBar/index.ts"
    ],
    "internal": [
      "Legend",
      "Text"
    ],
    "shared": [
      "lib/chart.ts",
      "lib/cn.ts"
    ],
    "external": []
  },
  "ChartTooltip": {
    "files": [
      "components/ChartTooltip/ChartTooltip.tsx",
      "components/ChartTooltip/index.ts"
    ],
    "internal": [
      "Text"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": []
  },
  "Checkbox": {
    "files": [
      "components/Checkbox/Checkbox.tsx",
      "components/Checkbox/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "CheckboxGroup": {
    "files": [
      "components/CheckboxGroup/CheckboxGroup.tsx",
      "components/CheckboxGroup/index.ts"
    ],
    "internal": [
      "Checkbox",
      "InlineMessage",
      "Text"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "Chip": {
    "files": [
      "components/Chip/Chip.tsx",
      "components/Chip/index.ts"
    ],
    "internal": [
      "VisuallyHidden"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "CoachTour": {
    "files": [
      "components/CoachTour/CoachTour.tsx",
      "components/CoachTour/index.ts"
    ],
    "internal": [
      "Button",
      "FocusTrap",
      "Portal",
      "Text"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "CodeBlock": {
    "files": [
      "components/CodeBlock/CodeBlock.tsx",
      "components/CodeBlock/highlight.ts",
      "components/CodeBlock/index.ts"
    ],
    "internal": [
      "Surface",
      "Tag",
      "Text"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "Collapse": {
    "files": [
      "components/Collapse/Collapse.tsx",
      "components/Collapse/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "Collapsible": {
    "files": [
      "components/Collapsible/Collapsible.tsx",
      "components/Collapsible/index.ts"
    ],
    "internal": [
      "Collapse",
      "Text"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "ColorPicker": {
    "files": [
      "components/ColorPicker/ColorPicker.tsx",
      "components/ColorPicker/index.ts"
    ],
    "internal": [
      "Input",
      "Popover",
      "Text"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "Combobox": {
    "files": [
      "components/Combobox/Combobox.tsx",
      "components/Combobox/index.ts"
    ],
    "internal": [
      "Input",
      "Popover",
      "Portal",
      "Select",
      "Text"
    ],
    "shared": [
      "components/internal/icons.tsx",
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "CommandPalette": {
    "files": [
      "components/CommandPalette/CommandPalette.tsx",
      "components/CommandPalette/index.ts"
    ],
    "internal": [
      "EmptyState",
      "FocusTrap",
      "Input",
      "Kbd",
      "Portal",
      "Text"
    ],
    "shared": [
      "components/internal/icons.tsx",
      "lib/cn.ts",
      "lib/types.ts"
    ],
    "external": [
      "react"
    ]
  },
  "Confetti": {
    "files": [
      "components/Confetti/Confetti.tsx",
      "components/Confetti/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts",
      "lib/motion.ts"
    ],
    "external": [
      "react"
    ]
  },
  "ConfirmDialog": {
    "files": [
      "components/ConfirmDialog/ConfirmDialog.tsx",
      "components/ConfirmDialog/index.ts"
    ],
    "internal": [
      "AlertDialog",
      "Input",
      "Text"
    ],
    "shared": [],
    "external": [
      "react"
    ]
  },
  "ConnectionBanner": {
    "files": [
      "components/ConnectionBanner/ConnectionBanner.tsx",
      "components/ConnectionBanner/index.ts"
    ],
    "internal": [
      "Spinner",
      "Text"
    ],
    "shared": [
      "lib/cn.ts",
      "lib/time.ts"
    ],
    "external": [
      "react"
    ]
  },
  "ConsentManager": {
    "files": [
      "components/ConsentManager/ConsentManager.tsx",
      "components/ConsentManager/index.ts"
    ],
    "internal": [
      "Button",
      "Surface",
      "Switch",
      "Text"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": []
  },
  "ContextMenu": {
    "files": [
      "components/ContextMenu/ContextMenu.tsx",
      "components/ContextMenu/index.ts"
    ],
    "internal": [
      "Divider",
      "Menu",
      "Portal",
      "Surface",
      "Text"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "CopyButton": {
    "files": [
      "components/CopyButton/CopyButton.tsx",
      "components/CopyButton/index.ts"
    ],
    "internal": [
      "Button",
      "IconButton",
      "VisuallyHidden"
    ],
    "shared": [
      "components/internal/icons.tsx"
    ],
    "external": [
      "react"
    ]
  },
  "CountUp": {
    "files": [
      "components/CountUp/CountUp.tsx",
      "components/CountUp/index.ts"
    ],
    "internal": [
      "AnimatedNumber"
    ],
    "shared": [],
    "external": [
      "react"
    ]
  },
  "Countdown": {
    "files": [
      "components/Countdown/Countdown.tsx",
      "components/Countdown/index.ts"
    ],
    "internal": [
      "Text"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "CoverFlow": {
    "files": [
      "components/CoverFlow/CoverFlow.tsx",
      "components/CoverFlow/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "Cropper": {
    "files": [
      "components/Cropper/Cropper.tsx",
      "components/Cropper/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "CubeCarousel": {
    "files": [
      "components/CubeCarousel/CubeCarousel.tsx",
      "components/CubeCarousel/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "CursorAura": {
    "files": [
      "components/CursorAura/CursorAura.tsx",
      "components/CursorAura/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "DataExplorer": {
    "files": [
      "components/DataExplorer/DataExplorer.tsx",
      "components/DataExplorer/index.ts"
    ],
    "internal": [
      "Card",
      "DataTable",
      "FilterBar",
      "SearchField",
      "Skeleton",
      "StateView",
      "Surface"
    ],
    "shared": [
      "lib/cn.ts",
      "lib/types.ts"
    ],
    "external": [
      "react"
    ]
  },
  "DataFreshness": {
    "files": [
      "components/DataFreshness/DataFreshness.tsx",
      "components/DataFreshness/index.ts"
    ],
    "internal": [
      "Spinner",
      "StatusDot",
      "Text"
    ],
    "shared": [
      "lib/cn.ts",
      "lib/time.ts"
    ],
    "external": []
  },
  "DataTable": {
    "files": [
      "components/DataTable/DataTable.tsx",
      "components/DataTable/index.ts"
    ],
    "internal": [
      "Checkbox",
      "EmptyState",
      "Pagination",
      "Table",
      "Text"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "DatePicker": {
    "files": [
      "components/DatePicker/DatePicker.tsx",
      "components/DatePicker/index.ts"
    ],
    "internal": [
      "Calendar",
      "Input",
      "Popover",
      "Surface"
    ],
    "shared": [],
    "external": [
      "react"
    ]
  },
  "DateRangePicker": {
    "files": [
      "components/DateRangePicker/DateRangePicker.tsx",
      "components/DateRangePicker/index.ts"
    ],
    "internal": [
      "Button",
      "Calendar",
      "Input",
      "Popover",
      "Text"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "DaySchedule": {
    "files": [
      "components/DaySchedule/DaySchedule.tsx",
      "components/DaySchedule/index.ts"
    ],
    "internal": [
      "Text",
      "VisuallyHidden"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "DescriptionList": {
    "files": [
      "components/DescriptionList/DescriptionList.tsx",
      "components/DescriptionList/index.ts"
    ],
    "internal": [
      "Text"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "DiceRoller": {
    "files": [
      "components/DiceRoller/DiceRoller.tsx",
      "components/DiceRoller/index.ts"
    ],
    "internal": [
      "Text",
      "VisuallyHidden"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "DiffSummary": {
    "files": [
      "components/DiffSummary/DiffSummary.tsx",
      "components/DiffSummary/index.ts"
    ],
    "internal": [
      "Surface",
      "Tag",
      "Text"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "DiffView": {
    "files": [
      "components/DiffView/DiffView.tsx",
      "components/DiffView/index.ts"
    ],
    "internal": [
      "Surface",
      "Tag",
      "Text"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": []
  },
  "Divider": {
    "files": [
      "components/Divider/Divider.tsx",
      "components/Divider/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts"
    ],
    "external": []
  },
  "Dock": {
    "files": [
      "components/Dock/Dock.tsx",
      "components/Dock/index.ts"
    ],
    "internal": [
      "Text"
    ],
    "shared": [
      "lib/cn.ts",
      "lib/types.ts"
    ],
    "external": [
      "react"
    ]
  },
  "DonutChart": {
    "files": [
      "components/DonutChart/DonutChart.tsx",
      "components/DonutChart/index.ts"
    ],
    "internal": [
      "Legend",
      "Text",
      "VisuallyHidden"
    ],
    "shared": [
      "lib/chart.ts",
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "DotGlobe": {
    "files": [
      "components/DotGlobe/DotGlobe.tsx",
      "components/DotGlobe/index.ts"
    ],
    "internal": [
      "VisuallyHidden"
    ],
    "shared": [
      "lib/cn.ts",
      "lib/motion.ts"
    ],
    "external": [
      "react"
    ]
  },
  "Drawer": {
    "files": [
      "components/Drawer/Drawer.tsx",
      "components/Drawer/index.ts"
    ],
    "internal": [
      "FocusTrap",
      "IconButton",
      "Portal",
      "Text"
    ],
    "shared": [
      "components/internal/icons.tsx",
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "DropdownMenu": {
    "files": [
      "components/DropdownMenu/DropdownMenu.tsx",
      "components/DropdownMenu/index.ts"
    ],
    "internal": [
      "Button",
      "Menu",
      "Popover"
    ],
    "shared": [],
    "external": [
      "react"
    ]
  },
  "EmojiSlider": {
    "files": [
      "components/EmojiSlider/EmojiSlider.tsx",
      "components/EmojiSlider/index.ts"
    ],
    "internal": [
      "Text"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "EmptyState": {
    "files": [
      "components/EmptyState/EmptyState.tsx",
      "components/EmptyState/index.ts"
    ],
    "internal": [
      "IconTile",
      "Text"
    ],
    "shared": [
      "lib/cn.ts",
      "lib/types.ts"
    ],
    "external": [
      "react"
    ]
  },
  "ErrorState": {
    "files": [
      "components/ErrorState/ErrorState.tsx",
      "components/ErrorState/index.ts"
    ],
    "internal": [
      "EmptyState",
      "Text"
    ],
    "shared": [
      "components/internal/icons.tsx",
      "lib/types.ts"
    ],
    "external": [
      "react"
    ]
  },
  "ExpandableText": {
    "files": [
      "components/ExpandableText/ExpandableText.tsx",
      "components/ExpandableText/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "Field": {
    "files": [
      "components/Field/Field.tsx",
      "components/Field/index.ts"
    ],
    "internal": [
      "InlineMessage",
      "Label"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "Figure": {
    "files": [
      "components/Figure/Figure.tsx",
      "components/Figure/index.ts"
    ],
    "internal": [
      "Text"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "FileUpload": {
    "files": [
      "components/FileUpload/FileUpload.tsx",
      "components/FileUpload/index.ts"
    ],
    "internal": [
      "Button",
      "IconButton",
      "Progress",
      "Surface",
      "Text"
    ],
    "shared": [
      "components/internal/icons.tsx",
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "FilterBar": {
    "files": [
      "components/FilterBar/FilterBar.tsx",
      "components/FilterBar/index.ts"
    ],
    "internal": [
      "Button",
      "Chip",
      "Text"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "FlipBook": {
    "files": [
      "components/FlipBook/FlipBook.tsx",
      "components/FlipBook/index.ts"
    ],
    "internal": [
      "Text",
      "VisuallyHidden"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "FlipCard": {
    "files": [
      "components/FlipCard/FlipCard.tsx",
      "components/FlipCard/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "FocusTrap": {
    "files": [
      "components/FocusTrap/FocusTrap.tsx",
      "components/FocusTrap/index.ts"
    ],
    "internal": [],
    "shared": [],
    "external": [
      "react"
    ]
  },
  "Form": {
    "files": [
      "components/Form/Form.tsx",
      "components/Form/index.ts"
    ],
    "internal": [
      "Text"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "FunnelChart": {
    "files": [
      "components/FunnelChart/FunnelChart.tsx",
      "components/FunnelChart/index.ts"
    ],
    "internal": [
      "Text"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": []
  },
  "GlitchText": {
    "files": [
      "components/GlitchText/GlitchText.tsx",
      "components/GlitchText/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "GooeyLoader": {
    "files": [
      "components/GooeyLoader/GooeyLoader.tsx",
      "components/GooeyLoader/index.ts"
    ],
    "internal": [
      "VisuallyHidden"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "GradientText": {
    "files": [
      "components/GradientText/GradientText.tsx",
      "components/GradientText/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "GravityTags": {
    "files": [
      "components/GravityTags/GravityTags.tsx",
      "components/GravityTags/index.ts"
    ],
    "internal": [
      "VisuallyHidden"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "HoldToConfirm": {
    "files": [
      "components/HoldToConfirm/HoldToConfirm.tsx",
      "components/HoldToConfirm/index.ts"
    ],
    "internal": [
      "Text"
    ],
    "shared": [
      "lib/cn.ts",
      "lib/types.ts"
    ],
    "external": [
      "react"
    ]
  },
  "HoloCard": {
    "files": [
      "components/HoloCard/HoloCard.tsx",
      "components/HoloCard/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "HoverCard": {
    "files": [
      "components/HoverCard/HoverCard.tsx",
      "components/HoverCard/index.ts"
    ],
    "internal": [
      "Popover",
      "Portal",
      "Surface"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "IconButton": {
    "files": [
      "components/IconButton/IconButton.tsx",
      "components/IconButton/index.ts"
    ],
    "internal": [
      "Spinner"
    ],
    "shared": [
      "lib/cn.ts",
      "lib/types.ts"
    ],
    "external": [
      "react"
    ]
  },
  "IconTile": {
    "files": [
      "components/IconTile/IconTile.tsx",
      "components/IconTile/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts",
      "lib/types.ts"
    ],
    "external": []
  },
  "ImageCompare": {
    "files": [
      "components/ImageCompare/ImageCompare.tsx",
      "components/ImageCompare/index.ts"
    ],
    "internal": [
      "Text"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "ImportMapper": {
    "files": [
      "components/ImportMapper/ImportMapper.tsx",
      "components/ImportMapper/index.ts"
    ],
    "internal": [
      "Select",
      "Surface",
      "Tag",
      "Text"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "InlineEdit": {
    "files": [
      "components/InlineEdit/InlineEdit.tsx",
      "components/InlineEdit/index.ts"
    ],
    "internal": [
      "IconButton",
      "Input",
      "Text"
    ],
    "shared": [
      "components/internal/icons.tsx",
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "InlineMessage": {
    "files": [
      "components/InlineMessage/InlineMessage.tsx",
      "components/InlineMessage/index.ts"
    ],
    "internal": [
      "Text"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "Input": {
    "files": [
      "components/Input/Input.tsx",
      "components/Input/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "InputOTP": {
    "files": [
      "components/InputOTP/InputOTP.tsx",
      "components/InputOTP/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "JsonViewer": {
    "files": [
      "components/JsonViewer/JsonViewer.tsx",
      "components/JsonViewer/index.ts"
    ],
    "internal": [
      "Surface"
    ],
    "shared": [
      "components/internal/icons.tsx",
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "KanbanBoard": {
    "files": [
      "components/KanbanBoard/KanbanBoard.tsx",
      "components/KanbanBoard/index.ts"
    ],
    "internal": [
      "Badge",
      "Card",
      "Surface",
      "Text",
      "VisuallyHidden"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "Kbd": {
    "files": [
      "components/Kbd/Kbd.tsx",
      "components/Kbd/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "KineticText": {
    "files": [
      "components/KineticText/KineticText.tsx",
      "components/KineticText/index.ts"
    ],
    "internal": [
      "VisuallyHidden"
    ],
    "shared": [
      "lib/cn.ts",
      "lib/motion.ts"
    ],
    "external": []
  },
  "Knob": {
    "files": [
      "components/Knob/Knob.tsx",
      "components/Knob/index.ts"
    ],
    "internal": [
      "Text"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "Label": {
    "files": [
      "components/Label/Label.tsx",
      "components/Label/index.ts"
    ],
    "internal": [
      "Text"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "LayerStack": {
    "files": [
      "components/LayerStack/LayerStack.tsx",
      "components/LayerStack/index.ts"
    ],
    "internal": [
      "Text"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "Legend": {
    "files": [
      "components/Legend/Legend.tsx",
      "components/Legend/index.ts"
    ],
    "internal": [
      "Text"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": []
  },
  "Lightbox": {
    "files": [
      "components/Lightbox/Lightbox.tsx",
      "components/Lightbox/index.ts"
    ],
    "internal": [
      "FocusTrap",
      "IconButton",
      "Portal",
      "Presence",
      "Surface",
      "Text",
      "VisuallyHidden"
    ],
    "shared": [
      "components/internal/icons.tsx",
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "LineChart": {
    "files": [
      "components/LineChart/LineChart.tsx",
      "components/LineChart/index.ts"
    ],
    "internal": [
      "CartesianChart"
    ],
    "shared": [],
    "external": []
  },
  "LiquidGlass": {
    "files": [
      "components/LiquidGlass/LiquidGlass.tsx",
      "components/LiquidGlass/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "List": {
    "files": [
      "components/List/List.tsx",
      "components/List/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "ListItem": {
    "files": [
      "components/ListItem/ListItem.tsx",
      "components/ListItem/index.ts"
    ],
    "internal": [
      "Text"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "LiveChart": {
    "files": [
      "components/LiveChart/LiveChart.tsx",
      "components/LiveChart/index.ts"
    ],
    "internal": [
      "Text",
      "VisuallyHidden"
    ],
    "shared": [
      "lib/cn.ts",
      "lib/motion.ts"
    ],
    "external": [
      "react"
    ]
  },
  "LoadingOverlay": {
    "files": [
      "components/LoadingOverlay/LoadingOverlay.tsx",
      "components/LoadingOverlay/index.ts"
    ],
    "internal": [
      "Spinner",
      "Text"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": []
  },
  "MagicTabs": {
    "files": [
      "components/MagicTabs/MagicTabs.tsx",
      "components/MagicTabs/index.ts"
    ],
    "internal": [
      "Text"
    ],
    "shared": [
      "lib/cn.ts",
      "lib/types.ts"
    ],
    "external": [
      "react"
    ]
  },
  "MagneticButton": {
    "files": [
      "components/MagneticButton/MagneticButton.tsx",
      "components/MagneticButton/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts",
      "lib/motion.ts"
    ],
    "external": [
      "react"
    ]
  },
  "Marquee": {
    "files": [
      "components/Marquee/Marquee.tsx",
      "components/Marquee/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "MarqueeSelect": {
    "files": [
      "components/MarqueeSelect/MarqueeSelect.tsx",
      "components/MarqueeSelect/index.ts"
    ],
    "internal": [
      "VisuallyHidden"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "MaskedValue": {
    "files": [
      "components/MaskedValue/MaskedValue.tsx",
      "components/MaskedValue/index.ts"
    ],
    "internal": [
      "Text",
      "VisuallyHidden"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "MatrixRain": {
    "files": [
      "components/MatrixRain/MatrixRain.tsx",
      "components/MatrixRain/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts",
      "lib/motion.ts"
    ],
    "external": [
      "react"
    ]
  },
  "MentionInput": {
    "files": [
      "components/MentionInput/MentionInput.tsx",
      "components/MentionInput/index.ts"
    ],
    "internal": [
      "Avatar",
      "Surface",
      "Text"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "Menu": {
    "files": [
      "components/Menu/Menu.tsx",
      "components/Menu/index.ts"
    ],
    "internal": [
      "Divider",
      "Popover",
      "Text"
    ],
    "shared": [
      "lib/cn.ts",
      "lib/types.ts"
    ],
    "external": [
      "react"
    ]
  },
  "Meter": {
    "files": [
      "components/Meter/Meter.tsx",
      "components/Meter/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts"
    ],
    "external": []
  },
  "Metric": {
    "files": [
      "components/Metric/Metric.tsx",
      "components/Metric/index.ts"
    ],
    "internal": [
      "Badge",
      "Text"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "MetricSpotlight": {
    "files": [
      "components/MetricSpotlight/MetricSpotlight.tsx",
      "components/MetricSpotlight/index.ts"
    ],
    "internal": [
      "CountUp",
      "Metric",
      "Presence",
      "Sparkline",
      "Surface",
      "Text"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "MiniMap": {
    "files": [
      "components/MiniMap/MiniMap.tsx",
      "components/MiniMap/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "Modal": {
    "files": [
      "components/Modal/Modal.tsx",
      "components/Modal/index.ts"
    ],
    "internal": [
      "FocusTrap",
      "IconButton",
      "Portal",
      "Presence",
      "Surface",
      "Text"
    ],
    "shared": [
      "components/internal/icons.tsx",
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "MorphDialog": {
    "files": [
      "components/MorphDialog/MorphDialog.tsx",
      "components/MorphDialog/index.ts"
    ],
    "internal": [
      "FocusTrap",
      "IconButton",
      "Portal",
      "Text"
    ],
    "shared": [
      "lib/cn.ts",
      "lib/motion.ts",
      "lib/types.ts"
    ],
    "external": [
      "react"
    ]
  },
  "MultiSelect": {
    "files": [
      "components/MultiSelect/MultiSelect.tsx",
      "components/MultiSelect/index.ts"
    ],
    "internal": [
      "Checkbox",
      "Chip",
      "Popover",
      "Select",
      "Text"
    ],
    "shared": [
      "components/internal/icons.tsx",
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "Navbar": {
    "files": [
      "components/Navbar/Navbar.tsx",
      "components/Navbar/index.ts"
    ],
    "internal": [
      "Avatar",
      "IconButton",
      "SearchField",
      "SegmentedControl",
      "StatusDot",
      "Toolbar",
      "Wordmark"
    ],
    "shared": [
      "components/internal/icons.tsx",
      "lib/cn.ts",
      "lib/types.ts"
    ],
    "external": [
      "react"
    ]
  },
  "NeonSign": {
    "files": [
      "components/NeonSign/NeonSign.tsx",
      "components/NeonSign/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "NotificationCenter": {
    "files": [
      "components/NotificationCenter/NotificationCenter.tsx",
      "components/NotificationCenter/index.ts"
    ],
    "internal": [
      "Badge",
      "Button",
      "Divider",
      "Drawer",
      "EmptyState",
      "IconTile",
      "List",
      "ListItem",
      "StatusDot",
      "Tabs",
      "Text"
    ],
    "shared": [
      "lib/cn.ts",
      "lib/types.ts"
    ],
    "external": [
      "react"
    ]
  },
  "NumberInput": {
    "files": [
      "components/NumberInput/NumberInput.tsx",
      "components/NumberInput/index.ts"
    ],
    "internal": [
      "IconButton",
      "Input"
    ],
    "shared": [
      "components/internal/icons.tsx",
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "Odometer": {
    "files": [
      "components/Odometer/Odometer.tsx",
      "components/Odometer/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts"
    ],
    "external": []
  },
  "OrbitRing": {
    "files": [
      "components/OrbitRing/OrbitRing.tsx",
      "components/OrbitRing/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "PageHeader": {
    "files": [
      "components/PageHeader/PageHeader.tsx",
      "components/PageHeader/index.ts"
    ],
    "internal": [
      "Text"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "PageTransition": {
    "files": [
      "components/PageTransition/PageTransition.tsx",
      "components/PageTransition/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts",
      "lib/motion.ts"
    ],
    "external": [
      "react"
    ]
  },
  "Pagination": {
    "files": [
      "components/Pagination/Pagination.tsx",
      "components/Pagination/index.ts"
    ],
    "internal": [
      "IconButton",
      "Text"
    ],
    "shared": [
      "components/internal/icons.tsx",
      "lib/cn.ts"
    ],
    "external": []
  },
  "PanZoom": {
    "files": [
      "components/PanZoom/PanZoom.tsx",
      "components/PanZoom/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "Parallax": {
    "files": [
      "components/Parallax/Parallax.tsx",
      "components/Parallax/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts",
      "lib/motion.ts"
    ],
    "external": [
      "react"
    ]
  },
  "ParticleField": {
    "files": [
      "components/ParticleField/ParticleField.tsx",
      "components/ParticleField/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts",
      "lib/motion.ts"
    ],
    "external": [
      "react"
    ]
  },
  "PasswordInput": {
    "files": [
      "components/PasswordInput/PasswordInput.tsx",
      "components/PasswordInput/index.ts"
    ],
    "internal": [
      "IconButton",
      "Input"
    ],
    "shared": [
      "components/internal/icons.tsx"
    ],
    "external": [
      "react"
    ]
  },
  "PasswordStrength": {
    "files": [
      "components/PasswordStrength/PasswordStrength.tsx",
      "components/PasswordStrength/index.ts"
    ],
    "internal": [
      "Meter",
      "StatusDot",
      "Text",
      "VisuallyHidden"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": []
  },
  "PermissionGate": {
    "files": [
      "components/PermissionGate/PermissionGate.tsx",
      "components/PermissionGate/index.ts"
    ],
    "internal": [
      "Button",
      "Surface",
      "Text"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "PianoKeys": {
    "files": [
      "components/PianoKeys/PianoKeys.tsx",
      "components/PianoKeys/index.ts"
    ],
    "internal": [
      "Text"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "PinPad": {
    "files": [
      "components/PinPad/PinPad.tsx",
      "components/PinPad/index.ts"
    ],
    "internal": [
      "Text",
      "VisuallyHidden"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "PixelCanvas": {
    "files": [
      "components/PixelCanvas/PixelCanvas.tsx",
      "components/PixelCanvas/index.ts"
    ],
    "internal": [
      "Text",
      "VisuallyHidden"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "Popover": {
    "files": [
      "components/Popover/Popover.tsx",
      "components/Popover/index.ts",
      "components/Popover/usePopoverPosition.ts"
    ],
    "internal": [
      "Portal",
      "Surface"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "Portal": {
    "files": [
      "components/Portal/Portal.tsx",
      "components/Portal/index.ts"
    ],
    "internal": [],
    "shared": [],
    "external": [
      "react",
      "react-dom"
    ]
  },
  "Presence": {
    "files": [
      "components/Presence/Presence.tsx",
      "components/Presence/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "PresenceBar": {
    "files": [
      "components/PresenceBar/PresenceBar.tsx",
      "components/PresenceBar/index.ts"
    ],
    "internal": [
      "Avatar",
      "Text",
      "Tooltip",
      "VisuallyHidden"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "PresenceCursors": {
    "files": [
      "components/PresenceCursors/PresenceCursors.tsx",
      "components/PresenceCursors/index.ts"
    ],
    "internal": [
      "Text"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": []
  },
  "PressScale": {
    "files": [
      "components/PressScale/PressScale.tsx",
      "components/PressScale/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "Progress": {
    "files": [
      "components/Progress/Progress.tsx",
      "components/Progress/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts"
    ],
    "external": []
  },
  "ProgressChart": {
    "files": [
      "components/ProgressChart/ProgressChart.tsx",
      "components/ProgressChart/index.ts"
    ],
    "internal": [
      "Legend"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": []
  },
  "ProgressRing": {
    "files": [
      "components/ProgressRing/ProgressRing.tsx",
      "components/ProgressRing/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "PromoBanner": {
    "files": [
      "components/PromoBanner/PromoBanner.tsx",
      "components/PromoBanner/index.ts"
    ],
    "internal": [
      "Text"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "PullToRefresh": {
    "files": [
      "components/PullToRefresh/PullToRefresh.tsx",
      "components/PullToRefresh/index.ts"
    ],
    "internal": [
      "ProgressRing",
      "Spinner",
      "Text"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "QRCode": {
    "files": [
      "components/QRCode/QRCode.tsx",
      "components/QRCode/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "QuickActions": {
    "files": [
      "components/QuickActions/QuickActions.tsx",
      "components/QuickActions/index.ts"
    ],
    "internal": [
      "Kbd",
      "PressScale",
      "Ripple",
      "Text",
      "Tooltip"
    ],
    "shared": [
      "lib/cn.ts",
      "lib/types.ts"
    ],
    "external": [
      "react"
    ]
  },
  "RadarChart": {
    "files": [
      "components/RadarChart/RadarChart.tsx",
      "components/RadarChart/index.ts"
    ],
    "internal": [
      "Legend",
      "Text",
      "VisuallyHidden"
    ],
    "shared": [
      "lib/chart.ts",
      "lib/cn.ts",
      "lib/motion.ts"
    ],
    "external": [
      "react"
    ]
  },
  "RadialGauge": {
    "files": [
      "components/RadialGauge/RadialGauge.tsx",
      "components/RadialGauge/index.ts"
    ],
    "internal": [
      "ProgressRing",
      "Text"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": []
  },
  "RadialMenu": {
    "files": [
      "components/RadialMenu/RadialMenu.tsx",
      "components/RadialMenu/index.ts"
    ],
    "internal": [
      "Text"
    ],
    "shared": [
      "lib/cn.ts",
      "lib/types.ts"
    ],
    "external": [
      "react"
    ]
  },
  "Radio": {
    "files": [
      "components/Radio/Radio.tsx",
      "components/Radio/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "RadioGroup": {
    "files": [
      "components/RadioGroup/RadioGroup.tsx",
      "components/RadioGroup/index.ts"
    ],
    "internal": [
      "InlineMessage",
      "Radio",
      "Surface",
      "Text"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "RangeSlider": {
    "files": [
      "components/RangeSlider/RangeSlider.tsx",
      "components/RangeSlider/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts"
    ],
    "external": []
  },
  "RateLimitMeter": {
    "files": [
      "components/RateLimitMeter/RateLimitMeter.tsx",
      "components/RateLimitMeter/index.ts"
    ],
    "internal": [
      "Text"
    ],
    "shared": [
      "lib/cn.ts",
      "lib/time.ts"
    ],
    "external": [
      "react"
    ]
  },
  "Rating": {
    "files": [
      "components/Rating/Rating.tsx",
      "components/Rating/index.ts"
    ],
    "internal": [
      "VisuallyHidden"
    ],
    "shared": [
      "components/internal/icons.tsx",
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "ReactionBar": {
    "files": [
      "components/ReactionBar/ReactionBar.tsx",
      "components/ReactionBar/index.ts"
    ],
    "internal": [
      "Text"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "RelativeTime": {
    "files": [
      "components/RelativeTime/RelativeTime.tsx",
      "components/RelativeTime/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "RetryQueue": {
    "files": [
      "components/RetryQueue/RetryQueue.tsx",
      "components/RetryQueue/index.ts"
    ],
    "internal": [
      "Spinner",
      "StatusDot",
      "Text",
      "VisuallyHidden"
    ],
    "shared": [
      "lib/cn.ts",
      "lib/time.ts"
    ],
    "external": [
      "react"
    ]
  },
  "Reveal": {
    "files": [
      "components/Reveal/Reveal.tsx",
      "components/Reveal/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts",
      "lib/motion.ts"
    ],
    "external": [
      "react"
    ]
  },
  "Ripple": {
    "files": [
      "components/Ripple/Ripple.tsx",
      "components/Ripple/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "RippleSurface": {
    "files": [
      "components/RippleSurface/RippleSurface.tsx",
      "components/RippleSurface/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts",
      "lib/motion.ts"
    ],
    "external": [
      "react"
    ]
  },
  "RopeCursor": {
    "files": [
      "components/RopeCursor/RopeCursor.tsx",
      "components/RopeCursor/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts",
      "lib/motion.ts"
    ],
    "external": [
      "react"
    ]
  },
  "RotatingWord": {
    "files": [
      "components/RotatingWord/RotatingWord.tsx",
      "components/RotatingWord/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts",
      "lib/motion.ts"
    ],
    "external": [
      "react"
    ]
  },
  "SankeyFlow": {
    "files": [
      "components/SankeyFlow/SankeyFlow.tsx",
      "components/SankeyFlow/index.ts"
    ],
    "internal": [
      "VisuallyHidden"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "SaveIndicator": {
    "files": [
      "components/SaveIndicator/SaveIndicator.tsx",
      "components/SaveIndicator/index.ts"
    ],
    "internal": [
      "Spinner",
      "StatusDot",
      "Text"
    ],
    "shared": [
      "lib/cn.ts",
      "lib/time.ts"
    ],
    "external": []
  },
  "ScratchCard": {
    "files": [
      "components/ScratchCard/ScratchCard.tsx",
      "components/ScratchCard/index.ts"
    ],
    "internal": [
      "Text"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "ScrollList": {
    "files": [
      "components/ScrollList/ScrollList.tsx",
      "components/ScrollList/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "ScrollProgress": {
    "files": [
      "components/ScrollProgress/ScrollProgress.tsx",
      "components/ScrollProgress/index.ts"
    ],
    "internal": [
      "Text"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "ScrollVelocity": {
    "files": [
      "components/ScrollVelocity/ScrollVelocity.tsx",
      "components/ScrollVelocity/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts",
      "lib/motion.ts"
    ],
    "external": [
      "react"
    ]
  },
  "SearchField": {
    "files": [
      "components/SearchField/SearchField.tsx",
      "components/SearchField/index.ts"
    ],
    "internal": [
      "IconButton",
      "Input"
    ],
    "shared": [
      "components/internal/icons.tsx"
    ],
    "external": [
      "react"
    ]
  },
  "SegmentedControl": {
    "files": [
      "components/SegmentedControl/SegmentedControl.tsx",
      "components/SegmentedControl/index.ts"
    ],
    "internal": [
      "VisuallyHidden"
    ],
    "shared": [
      "lib/cn.ts",
      "lib/types.ts"
    ],
    "external": [
      "react"
    ]
  },
  "Select": {
    "files": [
      "components/Select/Select.tsx",
      "components/Select/index.ts"
    ],
    "internal": [
      "Popover",
      "Text"
    ],
    "shared": [
      "components/internal/icons.tsx",
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "SessionTimeout": {
    "files": [
      "components/SessionTimeout/SessionTimeout.tsx",
      "components/SessionTimeout/index.ts"
    ],
    "internal": [
      "Button",
      "FocusTrap",
      "Portal",
      "ProgressRing",
      "Text"
    ],
    "shared": [
      "lib/cn.ts",
      "lib/time.ts"
    ],
    "external": [
      "react"
    ]
  },
  "ShimmerButton": {
    "files": [
      "components/ShimmerButton/ShimmerButton.tsx",
      "components/ShimmerButton/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "ShortcutRecorder": {
    "files": [
      "components/ShortcutRecorder/ShortcutRecorder.tsx",
      "components/ShortcutRecorder/index.ts"
    ],
    "internal": [
      "Kbd",
      "Text"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "Sidebar": {
    "files": [
      "components/Sidebar/Sidebar.tsx",
      "components/Sidebar/index.ts"
    ],
    "internal": [
      "Badge",
      "Divider",
      "Text"
    ],
    "shared": [
      "lib/cn.ts",
      "lib/types.ts"
    ],
    "external": []
  },
  "SidebarRail": {
    "files": [
      "components/SidebarRail/SidebarRail.tsx",
      "components/SidebarRail/index.ts"
    ],
    "internal": [
      "IconButton",
      "Tooltip"
    ],
    "shared": [
      "lib/cn.ts",
      "lib/types.ts"
    ],
    "external": []
  },
  "SignaturePad": {
    "files": [
      "components/SignaturePad/SignaturePad.tsx",
      "components/SignaturePad/index.ts"
    ],
    "internal": [
      "Text"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "Skeleton": {
    "files": [
      "components/Skeleton/Skeleton.tsx",
      "components/Skeleton/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts"
    ],
    "external": []
  },
  "SkipLink": {
    "files": [
      "components/SkipLink/SkipLink.tsx",
      "components/SkipLink/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "Slider": {
    "files": [
      "components/Slider/Slider.tsx",
      "components/Slider/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "SlotReels": {
    "files": [
      "components/SlotReels/SlotReels.tsx",
      "components/SlotReels/index.ts"
    ],
    "internal": [
      "Text",
      "VisuallyHidden"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "SortableList": {
    "files": [
      "components/SortableList/SortableList.tsx",
      "components/SortableList/index.ts"
    ],
    "internal": [
      "VisuallyHidden"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "Sparkline": {
    "files": [
      "components/Sparkline/Sparkline.tsx",
      "components/Sparkline/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "Spinner": {
    "files": [
      "components/Spinner/Spinner.tsx",
      "components/Spinner/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts"
    ],
    "external": []
  },
  "SplitButton": {
    "files": [
      "components/SplitButton/SplitButton.tsx",
      "components/SplitButton/index.ts"
    ],
    "internal": [
      "Button",
      "Menu"
    ],
    "shared": [
      "components/internal/icons.tsx",
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "SplitFlap": {
    "files": [
      "components/SplitFlap/SplitFlap.tsx",
      "components/SplitFlap/index.ts"
    ],
    "internal": [
      "VisuallyHidden"
    ],
    "shared": [
      "lib/cn.ts",
      "lib/motion.ts"
    ],
    "external": [
      "react"
    ]
  },
  "SplitPane": {
    "files": [
      "components/SplitPane/SplitPane.tsx",
      "components/SplitPane/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "Spotlight": {
    "files": [
      "components/Spotlight/Spotlight.tsx",
      "components/Spotlight/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts",
      "lib/motion.ts"
    ],
    "external": [
      "react"
    ]
  },
  "StackedCards": {
    "files": [
      "components/StackedCards/StackedCards.tsx",
      "components/StackedCards/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts",
      "lib/motion.ts"
    ],
    "external": [
      "react"
    ]
  },
  "Stagger": {
    "files": [
      "components/Stagger/Stagger.tsx",
      "components/Stagger/index.ts"
    ],
    "internal": [
      "Reveal"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "StarField": {
    "files": [
      "components/StarField/StarField.tsx",
      "components/StarField/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts",
      "lib/motion.ts"
    ],
    "external": [
      "react"
    ]
  },
  "StatCard": {
    "files": [
      "components/StatCard/StatCard.tsx",
      "components/StatCard/index.ts"
    ],
    "internal": [
      "IconTile",
      "Meter",
      "Metric",
      "Surface",
      "Text"
    ],
    "shared": [
      "lib/cn.ts",
      "lib/types.ts"
    ],
    "external": [
      "react"
    ]
  },
  "StateView": {
    "files": [
      "components/StateView/StateView.tsx",
      "components/StateView/index.ts"
    ],
    "internal": [
      "EmptyState",
      "ErrorState"
    ],
    "shared": [
      "lib/types.ts"
    ],
    "external": [
      "react"
    ]
  },
  "StatusDot": {
    "files": [
      "components/StatusDot/StatusDot.tsx",
      "components/StatusDot/index.ts"
    ],
    "internal": [
      "VisuallyHidden"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": []
  },
  "StatusStrip": {
    "files": [
      "components/StatusStrip/StatusStrip.tsx",
      "components/StatusStrip/index.ts"
    ],
    "internal": [
      "Text",
      "Tooltip",
      "VisuallyHidden"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "Stepper": {
    "files": [
      "components/Stepper/Stepper.tsx",
      "components/Stepper/index.ts"
    ],
    "internal": [
      "Text"
    ],
    "shared": [
      "components/internal/icons.tsx",
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "StickerPeel": {
    "files": [
      "components/StickerPeel/StickerPeel.tsx",
      "components/StickerPeel/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "StoryProgress": {
    "files": [
      "components/StoryProgress/StoryProgress.tsx",
      "components/StoryProgress/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts",
      "lib/motion.ts"
    ],
    "external": [
      "react"
    ]
  },
  "StreakCounter": {
    "files": [
      "components/StreakCounter/StreakCounter.tsx",
      "components/StreakCounter/index.ts"
    ],
    "internal": [
      "Text",
      "VisuallyHidden"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "SuccessMark": {
    "files": [
      "components/SuccessMark/SuccessMark.tsx",
      "components/SuccessMark/index.ts"
    ],
    "internal": [
      "VisuallyHidden"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": []
  },
  "Surface": {
    "files": [
      "components/Surface/Surface.tsx",
      "components/Surface/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "SwipeDeck": {
    "files": [
      "components/SwipeDeck/SwipeDeck.tsx",
      "components/SwipeDeck/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "SwipeRow": {
    "files": [
      "components/SwipeRow/SwipeRow.tsx",
      "components/SwipeRow/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts",
      "lib/types.ts"
    ],
    "external": [
      "react"
    ]
  },
  "Switch": {
    "files": [
      "components/Switch/Switch.tsx",
      "components/Switch/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "TabBar": {
    "files": [
      "components/TabBar/TabBar.tsx",
      "components/TabBar/index.ts"
    ],
    "internal": [
      "StatusDot",
      "Text"
    ],
    "shared": [
      "lib/cn.ts",
      "lib/types.ts"
    ],
    "external": []
  },
  "Table": {
    "files": [
      "components/Table/Table.tsx",
      "components/Table/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "Tabs": {
    "files": [
      "components/Tabs/Tabs.tsx",
      "components/Tabs/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts",
      "lib/types.ts"
    ],
    "external": [
      "react"
    ]
  },
  "Tag": {
    "files": [
      "components/Tag/Tag.tsx",
      "components/Tag/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "TagInput": {
    "files": [
      "components/TagInput/TagInput.tsx",
      "components/TagInput/index.ts"
    ],
    "internal": [
      "Chip",
      "VisuallyHidden"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "Terminal": {
    "files": [
      "components/Terminal/Terminal.tsx",
      "components/Terminal/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "Text": {
    "files": [
      "components/Text/Text.tsx",
      "components/Text/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "TextReveal": {
    "files": [
      "components/TextReveal/TextReveal.tsx",
      "components/TextReveal/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts",
      "lib/motion.ts"
    ],
    "external": [
      "react"
    ]
  },
  "TextScramble": {
    "files": [
      "components/TextScramble/TextScramble.tsx",
      "components/TextScramble/index.ts"
    ],
    "internal": [
      "VisuallyHidden"
    ],
    "shared": [
      "lib/cn.ts",
      "lib/motion.ts"
    ],
    "external": [
      "react"
    ]
  },
  "Textarea": {
    "files": [
      "components/Textarea/Textarea.tsx",
      "components/Textarea/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "Ticker": {
    "files": [
      "components/Ticker/Ticker.tsx",
      "components/Ticker/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "TiltCard": {
    "files": [
      "components/TiltCard/TiltCard.tsx",
      "components/TiltCard/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts",
      "lib/motion.ts"
    ],
    "external": [
      "react"
    ]
  },
  "TimePicker": {
    "files": [
      "components/TimePicker/TimePicker.tsx",
      "components/TimePicker/index.ts"
    ],
    "internal": [
      "Input",
      "Popover",
      "Text"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "Timeline": {
    "files": [
      "components/Timeline/Timeline.tsx",
      "components/Timeline/index.ts"
    ],
    "internal": [
      "StatusDot",
      "Text"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "Toast": {
    "files": [
      "components/Toast/Toast.tsx",
      "components/Toast/index.ts"
    ],
    "internal": [
      "IconButton",
      "Portal",
      "Presence",
      "Text"
    ],
    "shared": [
      "components/internal/icons.tsx",
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "ToggleGroup": {
    "files": [
      "components/ToggleGroup/ToggleGroup.tsx",
      "components/ToggleGroup/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts",
      "lib/types.ts"
    ],
    "external": []
  },
  "Toolbar": {
    "files": [
      "components/Toolbar/Toolbar.tsx",
      "components/Toolbar/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "Tooltip": {
    "files": [
      "components/Tooltip/Tooltip.tsx",
      "components/Tooltip/index.ts"
    ],
    "internal": [
      "Popover",
      "Portal"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "TreeMap": {
    "files": [
      "components/TreeMap/TreeMap.tsx",
      "components/TreeMap/index.ts"
    ],
    "internal": [
      "Text",
      "VisuallyHidden"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "TreeView": {
    "files": [
      "components/TreeView/TreeView.tsx",
      "components/TreeView/index.ts"
    ],
    "internal": [
      "Text"
    ],
    "shared": [
      "components/internal/icons.tsx",
      "lib/cn.ts",
      "lib/types.ts"
    ],
    "external": [
      "react"
    ]
  },
  "Typewriter": {
    "files": [
      "components/Typewriter/Typewriter.tsx",
      "components/Typewriter/index.ts"
    ],
    "internal": [
      "VisuallyHidden"
    ],
    "shared": [
      "lib/cn.ts",
      "lib/motion.ts"
    ],
    "external": [
      "react"
    ]
  },
  "TypingIndicator": {
    "files": [
      "components/TypingIndicator/TypingIndicator.tsx",
      "components/TypingIndicator/index.ts"
    ],
    "internal": [
      "Text"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "UndoStack": {
    "files": [
      "components/UndoStack/UndoStack.tsx",
      "components/UndoStack/index.ts"
    ],
    "internal": [
      "Kbd",
      "Surface",
      "Text",
      "VisuallyHidden"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "ValidationSummary": {
    "files": [
      "components/ValidationSummary/ValidationSummary.tsx",
      "components/ValidationSummary/index.ts"
    ],
    "internal": [
      "Text"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "VibePoll": {
    "files": [
      "components/VibePoll/VibePoll.tsx",
      "components/VibePoll/index.ts"
    ],
    "internal": [
      "Text",
      "VisuallyHidden"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": []
  },
  "VirtualList": {
    "files": [
      "components/VirtualList/VirtualList.tsx",
      "components/VirtualList/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "VisuallyHidden": {
    "files": [
      "components/VisuallyHidden/VisuallyHidden.tsx",
      "components/VisuallyHidden/index.ts"
    ],
    "internal": [],
    "shared": [],
    "external": [
      "react"
    ]
  },
  "Waveform": {
    "files": [
      "components/Waveform/Waveform.tsx",
      "components/Waveform/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "Wordmark": {
    "files": [
      "components/Wordmark/Wordmark.tsx",
      "components/Wordmark/index.ts"
    ],
    "internal": [],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  },
  "XPBar": {
    "files": [
      "components/XPBar/XPBar.tsx",
      "components/XPBar/index.ts"
    ],
    "internal": [
      "Text",
      "VisuallyHidden"
    ],
    "shared": [
      "lib/cn.ts"
    ],
    "external": [
      "react"
    ]
  }
}

/** What each shared module itself needs. */
export const sharedDependencies: Record<string, string[]> = {
  "lib/cn.ts": [],
  "lib/types.ts": [],
  "components/internal/icons.tsx": [
    "lib/types.ts"
  ],
  "lib/time.ts": [],
  "lib/motion.ts": [],
  "lib/chart.ts": []
}

export interface ResolvedDependencies {
  /** Every component needed, including the one asked for, in copy order. */
  components: string[]
  /** Every shared module needed. */
  shared: string[]
  /** Every npm package needed. */
  external: string[]
  /** Every file to copy, in the order they should be written. */
  files: string[]
}

/**
 * The full set required to make one component compile somewhere else.
 *
 * Depth-first with the requested component last, so a concatenated paste reads
 * bottom-up: the things it is built from first, the thing you asked for at the
 * end.
 */
export function dependenciesOf(name: string): ResolvedDependencies {
  const seen = new Set<string>()
  const order: string[] = []

  const walk = (current: string) => {
    if (seen.has(current)) return
    seen.add(current)
    for (const dep of dependencies[current]?.internal ?? []) walk(dep)
    order.push(current)
  }
  walk(name)

  const shared = new Set<string>()
  const external = new Set<string>()
  for (const component of order) {
    const entry = dependencies[component]
    if (!entry) continue
    for (const path of entry.shared) {
      shared.add(path)
      for (const nested of sharedDependencies[path] ?? []) shared.add(nested)
    }
    for (const pkg of entry.external) external.add(pkg)
  }

  const sharedFiles = [...shared].sort()
  return {
    components: order,
    shared: sharedFiles,
    external: [...external].sort(),
    files: [...sharedFiles, ...order.flatMap((component) => dependencies[component].files)],
  }
}
