// GENERATED by scripts/generate-evidence.mjs - do not edit.
//
// Measured, never asserted: see the script for where each field comes from. A
// field that is absent means there is no evidence for it, not that it is false.

export interface ComponentEvidence {
  /** No module in the folder carries 'use client'. */
  serverSafe: boolean
  /** No hex literal in the folder: every colour is a token, so dark mode repaints it. */
  tokenColours: boolean
  /** Runs continuous motion. */
  animates: boolean
  /** Animates, and opts out under prefers-reduced-motion. */
  reducedMotion: boolean
  /** The interaction suite that drives it from the keyboard. */
  keyboardSuite?: string
  /** Its docs page passed axe in the last recorded run. */
  axe?: boolean
}

export const componentEvidence: Record<string, ComponentEvidence> = {
  "Accordion": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "AchievementPop": {
    "serverSafe": false,
    "tokenColours": false,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "ActionSheet": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ActivityFeed": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ActivityHeatmap": {
    "serverSafe": false,
    "tokenColours": false,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Alert": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "AlertDialog": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "AmountField": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "AnchorNav": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "AnimatedBeam": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "AnimatedNumber": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "AnnouncementBar": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ApiKeyManager": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "AppShell": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ApprovalChain": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "AreaChart": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "AsciiImage": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "AudioVisualizer": {
    "serverSafe": false,
    "tokenColours": false,
    "animates": true,
    "reducedMotion": false,
    "axe": true
  },
  "AuditTrail": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "AuroraSurface": {
    "serverSafe": true,
    "tokenColours": false,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "AuthCard": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Avatar": {
    "serverSafe": false,
    "tokenColours": false,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "AvatarGroup": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "BackButton": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Badge": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Banner": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "BarChart": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "BarList": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "BentoGrid": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "BillingToggle": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "BlobMorph": {
    "serverSafe": false,
    "tokenColours": false,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "BoidsFlock": {
    "serverSafe": false,
    "tokenColours": false,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "BorderBeam": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "Breadcrumb": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "BulkActionBar": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "keyboardSuite": "test/interaction/lists.test.tsx",
    "axe": true
  },
  "Button": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ButtonGroup": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Calendar": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Card": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "CardDeck": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Carousel": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "CartesianChart": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false
  },
  "CategoryBar": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ChangelogList": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ChartTooltip": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Checkbox": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "CheckboxGroup": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "CheckoutSummary": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Chip": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "CoachTour": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "CodeBlock": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Collapse": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Collapsible": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ColorPicker": {
    "serverSafe": false,
    "tokenColours": false,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Combobox": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "CommandPalette": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Confetti": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "ConfirmDialog": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ConnectionBanner": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ConsentManager": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ContextMenu": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "CookieBanner": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "CopyButton": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "keyboardSuite": "test/interaction/forms.test.tsx",
    "axe": true
  },
  "CountUp": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Countdown": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "keyboardSuite": "test/interaction/time.test.tsx",
    "axe": true
  },
  "CoverFlow": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "Cropper": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "CtaSection": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "CubeCarousel": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "CursorAura": {
    "serverSafe": false,
    "tokenColours": false,
    "animates": true,
    "reducedMotion": false,
    "axe": true
  },
  "DangerZone": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "DataExplorer": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "DataFreshness": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "DataTable": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "keyboardSuite": "test/interaction/data.test.tsx",
    "axe": true
  },
  "DatePicker": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "DateRangePicker": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "DaySchedule": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "DescriptionList": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "DiceRoller": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "DiffSummary": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "DiffView": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Divider": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Dock": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "DonutChart": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "DotGlobe": {
    "serverSafe": false,
    "tokenColours": false,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "Drawer": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "DropdownMenu": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "EmojiSlider": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "EmptyState": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ErrorState": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ExpandableText": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "keyboardSuite": "test/interaction/layout.test.tsx",
    "axe": true
  },
  "FeatureComparison": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "FeatureGrid": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "FeedbackWidget": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Field": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Figure": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "FileUpload": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "FilterBar": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "FilterBuilder": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "FlipBook": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "FlipCard": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "FocusTrap": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Form": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "FunnelChart": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "GlitchText": {
    "serverSafe": true,
    "tokenColours": false,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "GooeyLoader": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "GradientText": {
    "serverSafe": true,
    "tokenColours": false,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "GravityTags": {
    "serverSafe": false,
    "tokenColours": false,
    "animates": true,
    "reducedMotion": false,
    "axe": true
  },
  "HelpPanel": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "HeroSection": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "HoldToConfirm": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": true,
    "reducedMotion": false,
    "axe": true
  },
  "HoloCard": {
    "serverSafe": false,
    "tokenColours": false,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "HoverCard": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "IconButton": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "IconTile": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ImageCompare": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ImportMapper": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "InlineEdit": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "keyboardSuite": "test/interaction/forms.test.tsx",
    "axe": true
  },
  "InlineMessage": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Input": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "InputOTP": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "IntegrationCard": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "InviteMembers": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "InvoiceList": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "JsonViewer": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "KanbanBoard": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Kbd": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "KineticText": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Knob": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Label": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "LayerStack": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Legend": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Lightbox": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "keyboardSuite": "test/interaction/overlays.test.tsx",
    "axe": true
  },
  "LineChart": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "LiquidGlass": {
    "serverSafe": false,
    "tokenColours": false,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "List": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ListItem": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "LiveChart": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "LoadingOverlay": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "LogoCloud": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "MagicTabs": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "MagneticButton": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Marquee": {
    "serverSafe": true,
    "tokenColours": false,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "MarqueeSelect": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "MaskedValue": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "MatrixRain": {
    "serverSafe": false,
    "tokenColours": false,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "MemberList": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "MentionInput": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Menu": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Meter": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Metric": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "MetricSpotlight": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "MiniMap": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Modal": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "keyboardSuite": "test/interaction/overlays.test.tsx",
    "axe": true
  },
  "MorphDialog": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "MultiSelect": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Navbar": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "NeonSign": {
    "serverSafe": true,
    "tokenColours": false,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "NotificationCenter": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "NumberInput": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Odometer": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "OnboardingWizard": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "OrbitRing": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "PageHeader": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "PageTransition": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Pagination": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "PanZoom": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Parallax": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ParticleField": {
    "serverSafe": false,
    "tokenColours": false,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "PasswordInput": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "PasswordStrength": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "keyboardSuite": "test/interaction/forms.test.tsx",
    "axe": true
  },
  "PaymentMethodCard": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "PermissionGate": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "PianoKeys": {
    "serverSafe": false,
    "tokenColours": false,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "PinPad": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "PixelCanvas": {
    "serverSafe": false,
    "tokenColours": false,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "PlanSummary": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Popover": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Portal": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Presence": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "PresenceBar": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "PresenceCursors": {
    "serverSafe": true,
    "tokenColours": false,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "PressScale": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "PricingCard": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "PricingTable": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Progress": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "ProgressChart": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ProgressRing": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "PromoBanner": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "PullToRefresh": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "QRCode": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "QuickActions": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "RadarChart": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "RadialGauge": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "RadialMenu": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Radio": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "RadioGroup": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "RangeSlider": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "RateLimitMeter": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Rating": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ReactionBar": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "RelativeTime": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "keyboardSuite": "test/interaction/time.test.tsx",
    "axe": true
  },
  "RetryQueue": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Reveal": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Ripple": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "RippleSurface": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "RolePermissions": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "RopeCursor": {
    "serverSafe": false,
    "tokenColours": false,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "RotatingWord": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "SankeyFlow": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "SaveIndicator": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "SavedViews": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ScratchCard": {
    "serverSafe": false,
    "tokenColours": false,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ScrollList": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ScrollProgress": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ScrollVelocity": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "SearchField": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "SectionHeading": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "SegmentedControl": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "keyboardSuite": "test/interaction/controls.test.tsx",
    "axe": true
  },
  "Select": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "SessionList": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "SessionTimeout": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "SettingsSection": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "SetupChecklist": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ShimmerButton": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "ShortcutRecorder": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Sidebar": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "SidebarRail": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "SignaturePad": {
    "serverSafe": false,
    "tokenColours": false,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "SiteFooter": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "SiteHeader": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Skeleton": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "SkipLink": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Slider": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "SlotReels": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "SortableList": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Sparkline": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Spinner": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": true,
    "reducedMotion": false,
    "axe": true
  },
  "SplitButton": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "SplitFlap": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "SplitPane": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "keyboardSuite": "test/interaction/layout.test.tsx",
    "axe": true
  },
  "Spotlight": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "SsoSetup": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "StackedCards": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Stagger": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "StarField": {
    "serverSafe": false,
    "tokenColours": false,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "StatCard": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "StateView": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "StatusDot": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "StatusStrip": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Stepper": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "StickerPeel": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "StoryProgress": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "StreakCounter": {
    "serverSafe": true,
    "tokenColours": false,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "SuccessMark": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "Surface": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "SwipeDeck": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "SwipeRow": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Switch": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "TabBar": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Table": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Tabs": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "keyboardSuite": "test/interaction/controls.test.tsx",
    "axe": true
  },
  "Tag": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "TagInput": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Terminal": {
    "serverSafe": false,
    "tokenColours": false,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "TestimonialCard": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Text": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "TextReveal": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "TextScramble": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Textarea": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Ticker": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "TiltCard": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "TimePicker": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Timeline": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Toast": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ToggleGroup": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "keyboardSuite": "test/interaction/controls.test.tsx",
    "axe": true
  },
  "Toolbar": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Tooltip": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "TreeMap": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "TreeView": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "TwoFactorSetup": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Typewriter": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "TypingIndicator": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "UndoStack": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "UpgradePrompt": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "UsageMeter": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "UserMenu": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ValidationSummary": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "VibePoll": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "VirtualList": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "keyboardSuite": "test/interaction/lists.test.tsx",
    "axe": true
  },
  "VisuallyHidden": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Waveform": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "WebhookDeliveries": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "WebhookEndpoints": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Wordmark": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "WorkspaceSwitcher": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "XPBar": {
    "serverSafe": false,
    "tokenColours": false,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  }
}

/** Components the docs site's own shell and feature pages import. */
export const siteComponents: string[] = [
  "Alert",
  "Avatar",
  "Badge",
  "Banner",
  "BarList",
  "Button",
  "Card",
  "Checkbox",
  "Chip",
  "CodeBlock",
  "CommandPalette",
  "ConfirmDialog",
  "CopyButton",
  "Divider",
  "DonutChart",
  "Drawer",
  "EmptyState",
  "Field",
  "HoloCard",
  "IconButton",
  "IconTile",
  "InlineEdit",
  "InlineMessage",
  "Input",
  "IntegrationCard",
  "JsonViewer",
  "KanbanBoard",
  "Kbd",
  "Meter",
  "Metric",
  "PageHeader",
  "PasswordInput",
  "Popover",
  "Progress",
  "ProgressRing",
  "Radio",
  "Rating",
  "Reveal",
  "SaveIndicator",
  "SearchField",
  "SectionHeading",
  "SegmentedControl",
  "Skeleton",
  "Slider",
  "Spinner",
  "StatCard",
  "StatusDot",
  "Stepper",
  "Surface",
  "Switch",
  "Tabs",
  "Tag",
  "Terminal",
  "Text",
  "Textarea",
  "Tooltip",
  "VisuallyHidden"
]
