// GENERATED by scripts/generate-evidence.mjs - do not edit.
//
// Measured, never asserted: see the script for where each field comes from. A
// field that is absent means there is no evidence for it, not that it is false.

export interface ComponentEvidence {
  /** No module in the folder carries 'use client'. */
  serverSafe: boolean
  /** No hex literal in the folder: every colour is a token, so dark mode repaints it. */
  tokenColours: boolean
  /** Runs continuous motion. */
  animates: boolean
  /** Animates, and opts out under prefers-reduced-motion. */
  reducedMotion: boolean
  /** The interaction suite that drives it from the keyboard. */
  keyboardSuite?: string
  /** Its docs page passed axe in the last recorded run. */
  axe?: boolean
}

export const componentEvidence: Record<string, ComponentEvidence> = {
  "A11yInspector": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "AccessDeniedState": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "AccessExplainer": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "AccessRequests": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Accordion": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "AchievementPop": {
    "serverSafe": false,
    "tokenColours": false,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "ActionSheet": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ActivityFeed": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ActivityHeatmap": {
    "serverSafe": false,
    "tokenColours": false,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "AddToCalendar": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "AddressInput": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "AgendaList": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Alert": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "AlertDialog": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "AlphabetIndex": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "AmountField": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "AnchorNav": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "AnimatedBeam": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "AnimatedGrid": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "AnimatedList": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "AnimatedNumber": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "AnnouncementBar": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false
  },
  "ApiKeyManager": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "AppShell": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ApprovalChain": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "AreaChart": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ArticlePager": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "AsciiImage": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "AspectRatio": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "AttentionShake": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "AudioPlayer": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "AudioTrimmer": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "AudioVisualizer": {
    "serverSafe": false,
    "tokenColours": false,
    "animates": true,
    "reducedMotion": false,
    "axe": true
  },
  "AuditTrail": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "AuroraSurface": {
    "serverSafe": true,
    "tokenColours": false,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "AuthCard": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Avatar": {
    "serverSafe": false,
    "tokenColours": false,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "AvatarGroup": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "AvatarUpload": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "BackButton": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "BackToTop": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Badge": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Banner": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "BarChart": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "BarList": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "BeeswarmChart": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "BentoGrid": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "BillingToggle": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "BlobMorph": {
    "serverSafe": false,
    "tokenColours": false,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "BlurHashImage": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "BoidsFlock": {
    "serverSafe": false,
    "tokenColours": false,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "BorderBeam": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "BoxPlot": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "BrandingSettings": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Breadcrumb": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "BulkActionBar": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "BulletChart": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Button": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ButtonGroup": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Calendar": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "keyboardSuite": "test/interaction/blockers.test.tsx",
    "axe": true
  },
  "CallGrid": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "CameraCapture": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "CancellationFlow": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "CandlestickChart": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "CaptionEditor": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Card": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "CardDeck": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Carousel": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "CartesianChart": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false
  },
  "CascadeSelect": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "CategoryBar": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ChangelogList": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ChartTooltip": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ChatThread": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Checkbox": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "CheckboxGroup": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ChecklistPopover": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "CheckoutSummary": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Chip": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ChoiceCardGroup": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ChordDiagram": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ChoroplethMap": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "CircularText": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ClickHeatmap": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "CoachTour": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "CodeBlock": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "CodeEditor": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "CodeTabs": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "CohortRetention": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Collapse": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Collapsible": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ColorPicker": {
    "serverSafe": false,
    "tokenColours": false,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ColorSwatchPicker": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Combobox": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "CommandPalette": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "CommentThread": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "CommitGraph": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Confetti": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "ConfirmDialog": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ConfirmPopover": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ConnectionBanner": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ConsentManager": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Container": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ContextMenu": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "CookieBanner": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "CopyButton": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "CountUp": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Countdown": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "CoverFlow": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "CreditCardInput": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Cropper": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Crossword": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "CtaSection": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "CubeCarousel": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "CursorAura": {
    "serverSafe": false,
    "tokenColours": false,
    "animates": true,
    "reducedMotion": false,
    "axe": true
  },
  "DangerZone": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "DashboardGrid": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "DataExplorer": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "DataExportPanel": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "DataFreshness": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "DataProfile": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "DataTable": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "DatePicker": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "keyboardSuite": "test/interaction/blockers.test.tsx",
    "axe": true
  },
  "DateRangePicker": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "DateTimePicker": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "DaySchedule": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "DescriptionList": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "DiceRoller": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "DictationButton": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "DiffSummary": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "DiffView": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Divider": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Dock": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "DomainSetup": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "DonutChart": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "DotGlobe": {
    "serverSafe": false,
    "tokenColours": false,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "DownloadButton": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Drawer": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "DropOverlay": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "DropdownMenu": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "DumbbellChart": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "DurationInput": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "EasingEditor": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "EditableTable": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "EmailVerification": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "EmailViewer": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "EmojiPicker": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "EmojiSlider": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "EmptyState": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ErrorBoundary": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ErrorState": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "EventCalendar": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ExpandableText": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ExperimentResults": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "FaqSection": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "FeatureBeacon": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "FeatureComparison": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "FeatureFlags": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "FeatureGrid": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "FeedbackWidget": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Field": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Figure": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "FileList": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "FileUpload": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "FilterBar": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "FilterBuilder": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "FindInPage": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "FitText": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "FlipBook": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "FlipCard": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "FloatingPanel": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "FlowField": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "FocusTrap": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "FollowButton": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Form": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "FormulaEditor": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "FractalExplorer": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "FullscreenDialog": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "FunnelChart": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "GameOfLife": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "GanttChart": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "GlitchText": {
    "serverSafe": true,
    "tokenColours": false,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "GooeyLoader": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "GradientText": {
    "serverSafe": true,
    "tokenColours": false,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "GravityTags": {
    "serverSafe": false,
    "tokenColours": false,
    "animates": true,
    "reducedMotion": false,
    "axe": true
  },
  "Grid": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "HelpPanel": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "HeroSection": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "HexViewer": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "HighlightMatch": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Histogram": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "HoldToConfirm": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": true,
    "reducedMotion": false,
    "keyboardSuite": "test/interaction/regressions.test.tsx",
    "axe": true
  },
  "HoloCard": {
    "serverSafe": false,
    "tokenColours": false,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Hotkeys": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "HoverCard": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "IconButton": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "IconTile": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ImageAnnotator": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ImageCompare": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ImageDiff": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ImageGallery": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ImportMapper": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "IncidentTimeline": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "InfiniteScroll": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "InlineCompletion": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "InlineEdit": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "keyboardSuite": "test/interaction/forms.test.tsx",
    "axe": true
  },
  "InlineMessage": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Input": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "InputGroup": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "InputOTP": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "IntegrationCard": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "InviteMembers": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "InvoiceList": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "IpAllowlist": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Joystick": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "JsonViewer": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "KanbanBoard": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Kbd": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "KeyboardShortcutsDialog": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "KineticText": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Knob": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "KpiStrip": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Label": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "LanguageSwitcher": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "LayerStack": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "LazyMount": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Leaderboard": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Legend": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Lightbox": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "keyboardSuite": "test/interaction/overlays.test.tsx",
    "axe": true
  },
  "LikeButton": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "LikertScale": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "LineChart": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "LinkPreview": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "LiquidGlass": {
    "serverSafe": false,
    "tokenColours": false,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "List": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ListItem": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "LiveChart": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "LiveRegion": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "LoadingOverlay": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "LocaleSettings": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "LogViewer": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "LogoCloud": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "MagicTabs": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "MagneticButton": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Magnifier": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "MaintenanceNotice": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "MarkdownEditor": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "MarkerHighlight": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Marquee": {
    "serverSafe": true,
    "tokenColours": false,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "MarqueeSelect": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "MaskedValue": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Masonry": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "MasterDetail": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "MathFormula": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "MatrixHeatmap": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "MatrixRain": {
    "serverSafe": false,
    "tokenColours": false,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "MegaMenu": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "MemberList": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "MemoryGame": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "MentionInput": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Menu": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Menubar": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "MessageComposer": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Meteors": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Meter": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Metric": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "MetricSpotlight": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Metronome": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "MiddleTruncate": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Minesweeper": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "MiniMap": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Modal": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "keyboardSuite": "test/interaction/overlays.test.tsx",
    "axe": true
  },
  "MonthPicker": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "MorphDialog": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "MorphingText": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "MultiSelect": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "NaturalDateInput": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Navbar": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "NavigationProgress": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "NeonSign": {
    "serverSafe": true,
    "tokenColours": false,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "NetworkGraph": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "NewsletterSignup": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "NodeEditor": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "NotFoundState": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "NotificationCenter": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "NotificationPreferences": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "NpsSurvey": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "NumberInput": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "keyboardSuite": "test/interaction/blockers.test.tsx",
    "axe": true
  },
  "OAuthConsent": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Odometer": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "OnboardingWizard": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "OpenApiReference": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "OrbitRing": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "OrderTracker": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "OrgChart": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "PageHeader": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "PageTransition": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "PagedDocument": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Pagination": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "PanZoom": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "PanoramaViewer": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "Parallax": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ParallelCoordinates": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ParetoChart": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ParticleField": {
    "serverSafe": false,
    "tokenColours": false,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "PasskeyManager": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "PasswordInput": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "PasswordStrength": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "PatternLock": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "PaymentMethodCard": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "PermissionGate": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "PermissionPrompt": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "PhoneInput": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "PianoKeys": {
    "serverSafe": false,
    "tokenColours": false,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "PictureInPicture": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "PinPad": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": true,
    "reducedMotion": true,
    "keyboardSuite": "test/interaction/blockers.test.tsx",
    "axe": true
  },
  "PitchTuner": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "PivotTable": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "PixelCanvas": {
    "serverSafe": false,
    "tokenColours": false,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "PlanSummary": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Popover": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Portal": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Presence": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "PresenceBar": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "PresenceCursors": {
    "serverSafe": true,
    "tokenColours": false,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "PressScale": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "PricingCard": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "PricingTable": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "PriorityNav": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ProductCard": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ProductVariantPicker": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ProfileCard": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Progress": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "ProgressChart": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ProgressRing": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "PromoBanner": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "PromptDialog": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "PullToRefresh": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "QRCode": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "QuestionQueue": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "QuickActions": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "RadarChart": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "RadialBarChart": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "RadialGauge": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "RadialMenu": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Radio": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "RadioGroup": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "RangeSlider": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "RateLimitMeter": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Rating": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ReactionBar": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "ReadAloud": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Receipt": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "RecentItems": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "RecurrenceEditor": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ReferralCard": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "RelativeTime": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ReleaseNotesModal": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "RemoteSelections": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "RepeaterField": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ResizableBox": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "RetryQueue": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Reveal": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ReviewSummary": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "RichTextEditor": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Ripple": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "RippleSurface": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "RoadmapBoard": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "RolePermissions": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "RopeCursor": {
    "serverSafe": false,
    "tokenColours": false,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "RotatingWord": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "SankeyFlow": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "SaveIndicator": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "SavedViews": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ScatterChart": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "SchemaForm": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ScopedSearch": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ScratchCard": {
    "serverSafe": false,
    "tokenColours": false,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ScrollArea": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ScrollList": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false
  },
  "ScrollProgress": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ScrollSequence": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ScrollStory": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ScrollSync": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ScrollVelocity": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "SearchField": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "SearchableCheckboxList": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "SeatMap": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "SeatSelector": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "SectionHeading": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "SegmentedControl": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "keyboardSuite": "test/interaction/controls.test.tsx",
    "axe": true
  },
  "Select": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "SelectionToolbar": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "SequenceDiagram": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "SessionList": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "SessionTimeout": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "SettingsSection": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "SetupChecklist": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ShaderCanvas": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "ShareMenu": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "SharePermissions": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ShimmerButton": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "ShimmerText": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "ShortcutRecorder": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ShowMoreList": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Sidebar": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "SidebarRail": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Sidenotes": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "SignalStrength": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "SignaturePad": {
    "serverSafe": false,
    "tokenColours": false,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "SiteFooter": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "SiteHeader": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Skeleton": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "SkipLink": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Slider": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "SlidingPuzzle": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "SlopeChart": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "SlotReels": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "SnakeGame": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "SocialLoginButtons": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "SortableList": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "SortableTree": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Sparkline": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "SpatialNavigation": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "SpinWheel": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Spinner": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": true,
    "reducedMotion": false,
    "axe": true
  },
  "SplitButton": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "SplitFlap": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "SplitPane": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "keyboardSuite": "test/interaction/layout.test.tsx",
    "axe": true
  },
  "Spotlight": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "SsoSetup": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Stack": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "StackTrace": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "StackedCards": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Stagger": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "StarField": {
    "serverSafe": false,
    "tokenColours": false,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "StatCard": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "StateView": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "StatusDot": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "StatusStrip": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "StepLoader": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Stepper": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "StickerPeel": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Sticky": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "StoryProgress": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "StreakCounter": {
    "serverSafe": true,
    "tokenColours": false,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "StreamGraph": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "SuccessMark": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "Sudoku": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "SunburstChart": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Surface": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "SwipeDeck": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "SwipeRow": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "SwipeToConfirm": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "Switch": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "TabBar": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Table": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Tabs": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "keyboardSuite": "test/interaction/controls.test.tsx",
    "axe": true
  },
  "Tag": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "TagInput": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Terminal": {
    "serverSafe": false,
    "tokenColours": false,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "TestimonialCard": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Text": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "TextLink": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "TextReveal": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "TextScramble": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Textarea": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ThemeScope": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "TicTacToe": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Ticker": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "TiltCard": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "TimePicker": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "keyboardSuite": "test/interaction/blockers.test.tsx",
    "axe": true
  },
  "TimeRangePicker": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "TimeSlotPicker": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Timeline": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "TimezonePlanner": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Toast": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ToggleButton": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ToggleGroup": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Toggletip": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Toolbar": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Tooltip": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "TrackChanges": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "TranscriptView": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "TransferList": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "TreeMap": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "TreeSelect": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "TreeTable": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "TreeView": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "keyboardSuite": "test/interaction/blockers.test.tsx",
    "axe": true
  },
  "TrendDelta": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "TwoFactorSetup": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Typewriter": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "TypingIndicator": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "UndoStack": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "UnitInput": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "UnsavedChangesBar": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "UpdateAvailable": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "UpgradePrompt": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "UploadQueue": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "UsageMeter": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "UsagePricingCalculator": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "UserMenu": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "ValidationSummary": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "VennDiagram": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "VersionHistory": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "VersionSwitcher": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "VibePoll": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "VideoPlayer": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "VirtualList": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "VisionSimulator": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "VisuallyHidden": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "VoiceRecorder": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "VoronoiField": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "VoteButtons": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "WaterfallChart": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Waveform": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  },
  "WebVitals": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "WebhookDeliveries": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "WebhookEndpoints": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "WeekView": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "WeekdayPicker": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Whiteboard": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "WordCloud": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "Wordmark": {
    "serverSafe": true,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "WorkspaceSwitcher": {
    "serverSafe": false,
    "tokenColours": true,
    "animates": false,
    "reducedMotion": false,
    "axe": true
  },
  "XPBar": {
    "serverSafe": false,
    "tokenColours": false,
    "animates": true,
    "reducedMotion": true,
    "axe": true
  }
}

/** Components the docs site's own shell and feature pages import. */
export const siteComponents: string[] = [
  "Alert",
  "AnchorNav",
  "AreaChart",
  "Avatar",
  "AvatarGroup",
  "Badge",
  "Banner",
  "BarChart",
  "Button",
  "Card",
  "Checkbox",
  "Chip",
  "CodeBlock",
  "ColorPicker",
  "CommandPalette",
  "ConfirmDialog",
  "CopyButton",
  "Divider",
  "Drawer",
  "EmptyState",
  "Field",
  "HoloCard",
  "IconButton",
  "IconTile",
  "InlineEdit",
  "InlineMessage",
  "Input",
  "IntegrationCard",
  "JsonViewer",
  "Kbd",
  "Marquee",
  "Meter",
  "Metric",
  "PageHeader",
  "PasswordInput",
  "Popover",
  "Progress",
  "ProgressRing",
  "Radio",
  "Rating",
  "Reveal",
  "SaveIndicator",
  "SearchField",
  "SectionHeading",
  "SegmentedControl",
  "Select",
  "Skeleton",
  "Spinner",
  "StatCard",
  "StatusDot",
  "Stepper",
  "Surface",
  "Switch",
  "Table",
  "Tabs",
  "Tag",
  "Terminal",
  "Text",
  "Textarea",
  "ThemeScope",
  "Tooltip",
  "VisuallyHidden"
]
