// GENERATED by scripts/generate-mcp-docs.mjs - do not edit.
//
// What the MCP server exposes, read off the server's own tool definitions.

export interface McpToolArg {
  name: string
  type: string
  required: boolean
  description: string
}

export interface McpTool {
  name: string
  description: string
  args: McpToolArg[]
}

export interface McpResource {
  uri: string
  name: string
  description: string
  mimeType: string
}

export const mcpTools: McpTool[] = [
  {
    "name": "search_components",
    "description": "Find components by name, by group, or by what they do. Returns name, slug, group, section and a one-line summary. Start here when you know the job but not the name.",
    "args": [
      {
        "name": "query",
        "type": "string",
        "required": false,
        "description": "Free text: a name, or what it is for (\"drag\", \"chart\", \"empty state\")."
      },
      {
        "name": "group",
        "type": "string",
        "required": false,
        "description": "Optional group filter, e.g. \"Forms & Inputs\"."
      }
    ]
  },
  {
    "name": "get_component",
    "description": "Everything about one component: its summary, every prop with real type, default and description, the ARIA roles it renders, its gzipped size, and what it depends on. Accepts 'DataTable', 'data-table' or 'datatable'.",
    "args": [
      {
        "name": "name",
        "type": "string",
        "required": true,
        "description": "Component name or slug."
      }
    ]
  },
  {
    "name": "get_component_source",
    "description": "The real source of a component. With withDependencies, also returns every sibling component and shared module it imports, in the order they should be written — which is exactly what `klyv add` copies.",
    "args": [
      {
        "name": "name",
        "type": "string",
        "required": true,
        "description": "Component name or slug."
      },
      {
        "name": "withDependencies",
        "type": "boolean",
        "required": false,
        "description": "Include everything it imports. Default false."
      }
    ]
  },
  {
    "name": "list_blocks",
    "description": "Whole screens built only from library components — sign-in, signup, two-factor, an admin panel, an operations dashboard, settings, a profile, a landing section. Reach for one when the job is a page rather than a part.",
    "args": [
      {
        "name": "category",
        "type": "string",
        "required": false,
        "description": "Optional: \"Authentication\", \"Application\" or \"Marketing\"."
      }
    ]
  },
  {
    "name": "get_block",
    "description": "One block in full: what it is for, every library component it uses, the npm packages it needs, and its complete source — a working screen to adapt rather than write from nothing. Accepts the slug or the name: 'dashboard', 'Dashboard', 'two-factor'.",
    "args": [
      {
        "name": "name",
        "type": "string",
        "required": true,
        "description": "Block slug or name."
      }
    ]
  },
  {
    "name": "list_groups",
    "description": "The thirteen groups the library is organised by, with what each is for and how many components it holds.",
    "args": []
  },
  {
    "name": "get_design_tokens",
    "description": "The design tokens in W3C Design Tokens format: colour, radius, shadow and type, plus the dark-mode overrides. Use these values rather than inventing colours.",
    "args": [
      {
        "name": "group",
        "type": "string",
        "required": false,
        "description": "Optional: \"color\", \"radius\", \"shadow\" or \"font\"."
      }
    ]
  },
  {
    "name": "get_design_rules",
    "description": "How the design system works and the rules every component obeys: the accent derivation, the surface stack, the ink scale, dark mode, and the five house rules. Read this before writing UI with Klyv.",
    "args": []
  },
  {
    "name": "how_to_install",
    "description": "Install and setup: the package, the stylesheet, Tailwind users, peer dependencies, icons, server components.",
    "args": []
  }
]

export const mcpResources: McpResource[] = [
  {
    "uri": "klyv://catalog",
    "name": "Component catalogue",
    "description": "Every component with its group, section and summary.",
    "mimeType": "application/json"
  },
  {
    "uri": "klyv://blocks",
    "name": "Blocks",
    "description": "Every block — a whole screen — with the components it is built from.",
    "mimeType": "application/json"
  },
  {
    "uri": "klyv://tokens",
    "name": "Design tokens",
    "description": "Tokens in W3C Design Tokens format, including dark mode.",
    "mimeType": "application/json"
  },
  {
    "uri": "klyv://rules",
    "name": "Design rules",
    "description": "The design system and the rules every component obeys.",
    "mimeType": "text/markdown"
  },
  {
    "uri": "klyv://usage",
    "name": "Install and usage",
    "description": "How to install the package and set up the stylesheet.",
    "mimeType": "text/markdown"
  }
]

/** What the server can answer questions about, counted from the same data. */
export const mcpFacts = {
  "components": 522,
  "props": 4152,
  "tokens": 32,
  "darkOverrides": 18
}
