// GENERATED by scripts/generate-props.mjs - do not edit.
//
// Names, types, required-ness and defaults are read off the AST, so this file
// cannot disagree with the implementation. Descriptions come from the JSDoc on
// each member; where a prop has none, the page falls back to the prose written
// beside its examples.

export interface GeneratedProp {
  name: string
  /** The declared type, printed as written. */
  type: string
  required: boolean
  /** Read off the destructured parameter, not the type. */
  defaultValue?: string
  /** From the member's JSDoc, when it has one. */
  description?: string
}

export interface GeneratedProps {
  props: GeneratedProp[]
  /** What the props type is built on — native attributes, or another props type. */
  inherits?: string[]
}

/**
 * One JSON file per component under ./props, each its own chunk: a component
 * page downloads its own API and nobody else's. Together they are several
 * hundred kilobytes, which every page used to pay for one table.
 */
const MODULES = import.meta.glob<GeneratedProps>('./props/*.json', { import: 'default' })
const loaded = new Map<string, GeneratedProps | null>()

/** The API if it has already arrived; undefined when it has not been loaded yet. */
export function cachedProps(component: string): GeneratedProps | null | undefined {
  return loaded.get(component)
}

/** The API for one component, or null when it declares no props type. */
export async function loadProps(component: string): Promise<GeneratedProps | null> {
  const known = loaded.get(component)
  if (known !== undefined) return known
  const load = MODULES[`./props/${component}.json`]
  const api = load ? await load() : null
  loaded.set(component, api)
  return api
}
