// GENERATED by scripts/measure-size.mjs - do not edit.
//
// Measured on the built package, over each component's whole dependency set:
// what a bundler would add for that one import, minus anything it already has.
// Unminified, because minification is the consumer's build, not ours.

export interface ComponentSize {
  /** Bytes of built JavaScript, this component and everything it imports. */
  bytes: number
  /** The same, gzipped. */
  gzip: number
  /** How many modules that is. */
  files: number
  /** How many other components come with it. */
  dependencies: number
}

export const sizes: Record<string, ComponentSize> = {
  "A11yInspector": {
    "bytes": 22484,
    "gzip": 7198,
    "files": 14,
    "dependencies": 5
  },
  "AccessDeniedState": {
    "bytes": 16786,
    "gzip": 4947,
    "files": 15,
    "dependencies": 5
  },
  "AccessExplainer": {
    "bytes": 36849,
    "gzip": 10060,
    "files": 25,
    "dependencies": 8
  },
  "AccessRequests": {
    "bytes": 54657,
    "gzip": 13571,
    "files": 50,
    "dependencies": 20
  },
  "Accordion": {
    "bytes": 7332,
    "gzip": 2497,
    "files": 9,
    "dependencies": 3
  },
  "AchievementPop": {
    "bytes": 7654,
    "gzip": 2667,
    "files": 7,
    "dependencies": 2
  },
  "ActionSheet": {
    "bytes": 20784,
    "gzip": 5916,
    "files": 21,
    "dependencies": 7
  },
  "ActivityFeed": {
    "bytes": 18739,
    "gzip": 5302,
    "files": 21,
    "dependencies": 8
  },
  "ActivityHeatmap": {
    "bytes": 21701,
    "gzip": 6189,
    "files": 19,
    "dependencies": 6
  },
  "AddToCalendar": {
    "bytes": 29858,
    "gzip": 8865,
    "files": 21,
    "dependencies": 6
  },
  "AddressInput": {
    "bytes": 21565,
    "gzip": 5905,
    "files": 15,
    "dependencies": 5
  },
  "AgendaList": {
    "bytes": 9907,
    "gzip": 3258,
    "files": 7,
    "dependencies": 2
  },
  "Alert": {
    "bytes": 12379,
    "gzip": 3690,
    "files": 11,
    "dependencies": 3
  },
  "AlertDialog": {
    "bytes": 24325,
    "gzip": 6848,
    "files": 25,
    "dependencies": 9
  },
  "AlphabetIndex": {
    "bytes": 7439,
    "gzip": 2539,
    "files": 4,
    "dependencies": 0
  },
  "AmountField": {
    "bytes": 28053,
    "gzip": 7675,
    "files": 21,
    "dependencies": 6
  },
  "AnchorNav": {
    "bytes": 2787,
    "gzip": 1173,
    "files": 3,
    "dependencies": 0
  },
  "AnimatedBeam": {
    "bytes": 4354,
    "gzip": 1564,
    "files": 3,
    "dependencies": 0
  },
  "AnimatedGrid": {
    "bytes": 10436,
    "gzip": 3555,
    "files": 5,
    "dependencies": 0
  },
  "AnimatedList": {
    "bytes": 6901,
    "gzip": 2386,
    "files": 5,
    "dependencies": 0
  },
  "AnimatedNumber": {
    "bytes": 1801,
    "gzip": 794,
    "files": 3,
    "dependencies": 0
  },
  "AnnouncementBar": {
    "bytes": 15681,
    "gzip": 4490,
    "files": 13,
    "dependencies": 4
  },
  "AnsiOutput": {
    "bytes": 25421,
    "gzip": 7507,
    "files": 17,
    "dependencies": 5
  },
  "ApiKeyManager": {
    "bytes": 53938,
    "gzip": 13207,
    "files": 53,
    "dependencies": 22
  },
  "AppShell": {
    "bytes": 2537,
    "gzip": 1011,
    "files": 5,
    "dependencies": 1
  },
  "ApprovalChain": {
    "bytes": 14404,
    "gzip": 4401,
    "files": 18,
    "dependencies": 7
  },
  "AreaChart": {
    "bytes": 15751,
    "gzip": 4382,
    "files": 14,
    "dependencies": 5
  },
  "ArticlePager": {
    "bytes": 7038,
    "gzip": 2045,
    "files": 5,
    "dependencies": 0
  },
  "AsciiImage": {
    "bytes": 3813,
    "gzip": 1526,
    "files": 5,
    "dependencies": 1
  },
  "AspectRatio": {
    "bytes": 1496,
    "gzip": 695,
    "files": 3,
    "dependencies": 0
  },
  "AttentionShake": {
    "bytes": 4478,
    "gzip": 1718,
    "files": 4,
    "dependencies": 0
  },
  "AudioPlayer": {
    "bytes": 46161,
    "gzip": 11417,
    "files": 34,
    "dependencies": 13
  },
  "AudioTrimmer": {
    "bytes": 18873,
    "gzip": 6104,
    "files": 10,
    "dependencies": 3
  },
  "AudioVisualizer": {
    "bytes": 9812,
    "gzip": 3202,
    "files": 7,
    "dependencies": 2
  },
  "AuditTrail": {
    "bytes": 12621,
    "gzip": 3971,
    "files": 12,
    "dependencies": 4
  },
  "AuroraSurface": {
    "bytes": 3055,
    "gzip": 1330,
    "files": 3,
    "dependencies": 0
  },
  "AuthCard": {
    "bytes": 19276,
    "gzip": 5242,
    "files": 19,
    "dependencies": 7
  },
  "Avatar": {
    "bytes": 2149,
    "gzip": 1028,
    "files": 5,
    "dependencies": 1
  },
  "AvatarGroup": {
    "bytes": 3711,
    "gzip": 1383,
    "files": 7,
    "dependencies": 2
  },
  "AvatarUpload": {
    "bytes": 24115,
    "gzip": 6891,
    "files": 11,
    "dependencies": 3
  },
  "BackButton": {
    "bytes": 1725,
    "gzip": 835,
    "files": 3,
    "dependencies": 0
  },
  "BackToTop": {
    "bytes": 6150,
    "gzip": 2197,
    "files": 4,
    "dependencies": 0
  },
  "Badge": {
    "bytes": 927,
    "gzip": 508,
    "files": 3,
    "dependencies": 0
  },
  "Banner": {
    "bytes": 15332,
    "gzip": 4412,
    "files": 11,
    "dependencies": 3
  },
  "BarChart": {
    "bytes": 15345,
    "gzip": 4328,
    "files": 14,
    "dependencies": 5
  },
  "BarList": {
    "bytes": 4987,
    "gzip": 1854,
    "files": 6,
    "dependencies": 1
  },
  "BeeswarmChart": {
    "bytes": 20528,
    "gzip": 6229,
    "files": 11,
    "dependencies": 3
  },
  "BentoGrid": {
    "bytes": 1281,
    "gzip": 577,
    "files": 3,
    "dependencies": 0
  },
  "BillingToggle": {
    "bytes": 5469,
    "gzip": 1883,
    "files": 10,
    "dependencies": 3
  },
  "BlobMorph": {
    "bytes": 5737,
    "gzip": 2067,
    "files": 4,
    "dependencies": 0
  },
  "BlurHashImage": {
    "bytes": 6637,
    "gzip": 2487,
    "files": 3,
    "dependencies": 0
  },
  "BoidsFlock": {
    "bytes": 7852,
    "gzip": 2483,
    "files": 4,
    "dependencies": 0
  },
  "BorderBeam": {
    "bytes": 2427,
    "gzip": 1015,
    "files": 3,
    "dependencies": 0
  },
  "BoxPlot": {
    "bytes": 21612,
    "gzip": 6278,
    "files": 11,
    "dependencies": 3
  },
  "BpmDetector": {
    "bytes": 30877,
    "gzip": 9103,
    "files": 15,
    "dependencies": 5
  },
  "BrandingSettings": {
    "bytes": 48510,
    "gzip": 12562,
    "files": 30,
    "dependencies": 9
  },
  "Breadcrumb": {
    "bytes": 9423,
    "gzip": 2857,
    "files": 7,
    "dependencies": 1
  },
  "BulkActionBar": {
    "bytes": 8816,
    "gzip": 2923,
    "files": 13,
    "dependencies": 5
  },
  "BulletChart": {
    "bytes": 13759,
    "gzip": 4718,
    "files": 7,
    "dependencies": 1
  },
  "Button": {
    "bytes": 3080,
    "gzip": 1281,
    "files": 5,
    "dependencies": 1
  },
  "ButtonGroup": {
    "bytes": 1158,
    "gzip": 565,
    "files": 3,
    "dependencies": 0
  },
  "Calendar": {
    "bytes": 18756,
    "gzip": 5414,
    "files": 13,
    "dependencies": 4
  },
  "CallGrid": {
    "bytes": 9306,
    "gzip": 3187,
    "files": 7,
    "dependencies": 2
  },
  "CameraCapture": {
    "bytes": 35069,
    "gzip": 9708,
    "files": 23,
    "dependencies": 7
  },
  "CancellationFlow": {
    "bytes": 29986,
    "gzip": 7911,
    "files": 26,
    "dependencies": 10
  },
  "CandlestickChart": {
    "bytes": 20382,
    "gzip": 6090,
    "files": 11,
    "dependencies": 3
  },
  "CaptionEditor": {
    "bytes": 26536,
    "gzip": 7526,
    "files": 17,
    "dependencies": 6
  },
  "Card": {
    "bytes": 5425,
    "gzip": 1917,
    "files": 7,
    "dependencies": 2
  },
  "CardDeck": {
    "bytes": 1104,
    "gzip": 564,
    "files": 3,
    "dependencies": 0
  },
  "Carousel": {
    "bytes": 11499,
    "gzip": 3521,
    "files": 10,
    "dependencies": 2
  },
  "CartesianChart": {
    "bytes": 13722,
    "gzip": 3919,
    "files": 12,
    "dependencies": 4
  },
  "CascadeSelect": {
    "bytes": 26216,
    "gzip": 7257,
    "files": 17,
    "dependencies": 4
  },
  "CategoryBar": {
    "bytes": 8649,
    "gzip": 2923,
    "files": 8,
    "dependencies": 2
  },
  "ChangelogList": {
    "bytes": 9134,
    "gzip": 2844,
    "files": 10,
    "dependencies": 3
  },
  "ChartTooltip": {
    "bytes": 3983,
    "gzip": 1478,
    "files": 5,
    "dependencies": 1
  },
  "ChatThread": {
    "bytes": 19775,
    "gzip": 5793,
    "files": 15,
    "dependencies": 4
  },
  "Checkbox": {
    "bytes": 2786,
    "gzip": 1113,
    "files": 3,
    "dependencies": 0
  },
  "CheckboxGroup": {
    "bytes": 8648,
    "gzip": 2737,
    "files": 9,
    "dependencies": 3
  },
  "ChecklistPopover": {
    "bytes": 30691,
    "gzip": 7854,
    "files": 23,
    "dependencies": 7
  },
  "CheckoutSummary": {
    "bytes": 16905,
    "gzip": 5003,
    "files": 16,
    "dependencies": 6
  },
  "ChessBoard": {
    "bytes": 48647,
    "gzip": 12980,
    "files": 15,
    "dependencies": 5
  },
  "Chip": {
    "bytes": 2862,
    "gzip": 1070,
    "files": 5,
    "dependencies": 1
  },
  "ChladniPlate": {
    "bytes": 37836,
    "gzip": 10548,
    "files": 16,
    "dependencies": 4
  },
  "ChoiceCardGroup": {
    "bytes": 8473,
    "gzip": 2447,
    "files": 7,
    "dependencies": 2
  },
  "ChordDiagram": {
    "bytes": 18836,
    "gzip": 6142,
    "files": 11,
    "dependencies": 3
  },
  "ChoroplethMap": {
    "bytes": 19938,
    "gzip": 6312,
    "files": 11,
    "dependencies": 3
  },
  "CircularText": {
    "bytes": 5231,
    "gzip": 1913,
    "files": 4,
    "dependencies": 0
  },
  "ClickHeatmap": {
    "bytes": 20905,
    "gzip": 6792,
    "files": 10,
    "dependencies": 3
  },
  "ClothPanel": {
    "bytes": 37405,
    "gzip": 10114,
    "files": 5,
    "dependencies": 0
  },
  "CoachTour": {
    "bytes": 17877,
    "gzip": 5121,
    "files": 15,
    "dependencies": 5
  },
  "CodeBlock": {
    "bytes": 11138,
    "gzip": 3915,
    "files": 10,
    "dependencies": 3
  },
  "CodeEditor": {
    "bytes": 9123,
    "gzip": 3073,
    "files": 4,
    "dependencies": 0
  },
  "CodeTabs": {
    "bytes": 27460,
    "gzip": 7885,
    "files": 24,
    "dependencies": 9
  },
  "CohortRetention": {
    "bytes": 15654,
    "gzip": 4883,
    "files": 9,
    "dependencies": 2
  },
  "CollaborativeText": {
    "bytes": 9186,
    "gzip": 3116,
    "files": 6,
    "dependencies": 1
  },
  "Collapse": {
    "bytes": 1697,
    "gzip": 758,
    "files": 3,
    "dependencies": 0
  },
  "Collapsible": {
    "bytes": 6248,
    "gzip": 2209,
    "files": 7,
    "dependencies": 2
  },
  "ColorPicker": {
    "bytes": 20217,
    "gzip": 5890,
    "files": 17,
    "dependencies": 5
  },
  "ColorSwatchPicker": {
    "bytes": 12292,
    "gzip": 3800,
    "files": 6,
    "dependencies": 0
  },
  "Combobox": {
    "bytes": 31048,
    "gzip": 8001,
    "files": 21,
    "dependencies": 6
  },
  "CommandPalette": {
    "bytes": 26031,
    "gzip": 7132,
    "files": 23,
    "dependencies": 8
  },
  "CommentAnchors": {
    "bytes": 15345,
    "gzip": 4842,
    "files": 6,
    "dependencies": 1
  },
  "CommentThread": {
    "bytes": 24283,
    "gzip": 6806,
    "files": 21,
    "dependencies": 8
  },
  "CommitGraph": {
    "bytes": 15110,
    "gzip": 5079,
    "files": 7,
    "dependencies": 1
  },
  "Confetti": {
    "bytes": 3819,
    "gzip": 1503,
    "files": 4,
    "dependencies": 0
  },
  "ConfirmDialog": {
    "bytes": 27805,
    "gzip": 7607,
    "files": 29,
    "dependencies": 11
  },
  "ConfirmPopover": {
    "bytes": 19140,
    "gzip": 5617,
    "files": 19,
    "dependencies": 6
  },
  "ConnectionBanner": {
    "bytes": 8450,
    "gzip": 2843,
    "files": 8,
    "dependencies": 2
  },
  "ConsentManager": {
    "bytes": 11547,
    "gzip": 3571,
    "files": 13,
    "dependencies": 5
  },
  "Container": {
    "bytes": 1256,
    "gzip": 583,
    "files": 3,
    "dependencies": 0
  },
  "ContextMenu": {
    "bytes": 23166,
    "gzip": 5914,
    "files": 20,
    "dependencies": 6
  },
  "ContourPlot": {
    "bytes": 25621,
    "gzip": 8075,
    "files": 13,
    "dependencies": 4
  },
  "ControlChart": {
    "bytes": 28331,
    "gzip": 8189,
    "files": 11,
    "dependencies": 3
  },
  "CookieBanner": {
    "bytes": 9260,
    "gzip": 3053,
    "files": 11,
    "dependencies": 4
  },
  "CopyButton": {
    "bytes": 11886,
    "gzip": 3499,
    "files": 13,
    "dependencies": 4
  },
  "CountUp": {
    "bytes": 3042,
    "gzip": 1124,
    "files": 5,
    "dependencies": 1
  },
  "Countdown": {
    "bytes": 5323,
    "gzip": 2091,
    "files": 5,
    "dependencies": 1
  },
  "CoverFlow": {
    "bytes": 4171,
    "gzip": 1595,
    "files": 3,
    "dependencies": 0
  },
  "CreditCardInput": {
    "bytes": 7823,
    "gzip": 2631,
    "files": 3,
    "dependencies": 0
  },
  "CronEditor": {
    "bytes": 53463,
    "gzip": 15005,
    "files": 28,
    "dependencies": 9
  },
  "Cropper": {
    "bytes": 6659,
    "gzip": 2054,
    "files": 3,
    "dependencies": 0
  },
  "Crossword": {
    "bytes": 17719,
    "gzip": 5296,
    "files": 7,
    "dependencies": 2
  },
  "CspEvaluator": {
    "bytes": 19783,
    "gzip": 5927,
    "files": 6,
    "dependencies": 1
  },
  "CsvImport": {
    "bytes": 50370,
    "gzip": 13632,
    "files": 26,
    "dependencies": 8
  },
  "CtaSection": {
    "bytes": 3650,
    "gzip": 1274,
    "files": 4,
    "dependencies": 0
  },
  "CubeCarousel": {
    "bytes": 4226,
    "gzip": 1579,
    "files": 3,
    "dependencies": 0
  },
  "CurlConverter": {
    "bytes": 42407,
    "gzip": 11865,
    "files": 18,
    "dependencies": 6
  },
  "CursorAura": {
    "bytes": 3905,
    "gzip": 1517,
    "files": 3,
    "dependencies": 0
  },
  "DangerZone": {
    "bytes": 32077,
    "gzip": 8502,
    "files": 33,
    "dependencies": 13
  },
  "DashboardGrid": {
    "bytes": 19705,
    "gzip": 5545,
    "files": 11,
    "dependencies": 3
  },
  "DataExplorer": {
    "bytes": 45411,
    "gzip": 10789,
    "files": 45,
    "dependencies": 20
  },
  "DataExportPanel": {
    "bytes": 54985,
    "gzip": 13991,
    "files": 39,
    "dependencies": 14
  },
  "DataFreshness": {
    "bytes": 7898,
    "gzip": 2614,
    "files": 12,
    "dependencies": 4
  },
  "DataProfile": {
    "bytes": 14116,
    "gzip": 4512,
    "files": 7,
    "dependencies": 2
  },
  "DataTable": {
    "bytes": 25284,
    "gzip": 6760,
    "files": 21,
    "dependencies": 8
  },
  "DatePicker": {
    "bytes": 33513,
    "gzip": 9109,
    "files": 27,
    "dependencies": 9
  },
  "DateRangePicker": {
    "bytes": 37461,
    "gzip": 9930,
    "files": 29,
    "dependencies": 10
  },
  "DateTimePicker": {
    "bytes": 44389,
    "gzip": 11601,
    "files": 31,
    "dependencies": 11
  },
  "DaySchedule": {
    "bytes": 9159,
    "gzip": 2972,
    "files": 7,
    "dependencies": 2
  },
  "Dendrogram": {
    "bytes": 17020,
    "gzip": 5420,
    "files": 6,
    "dependencies": 1
  },
  "DescriptionList": {
    "bytes": 3705,
    "gzip": 1404,
    "files": 5,
    "dependencies": 1
  },
  "DiceRoller": {
    "bytes": 7367,
    "gzip": 2564,
    "files": 7,
    "dependencies": 2
  },
  "DictationButton": {
    "bytes": 8116,
    "gzip": 3021,
    "files": 5,
    "dependencies": 1
  },
  "DiffSummary": {
    "bytes": 7969,
    "gzip": 2475,
    "files": 9,
    "dependencies": 3
  },
  "DiffView": {
    "bytes": 7302,
    "gzip": 2374,
    "files": 9,
    "dependencies": 3
  },
  "Divider": {
    "bytes": 845,
    "gzip": 445,
    "files": 3,
    "dependencies": 0
  },
  "Dock": {
    "bytes": 7742,
    "gzip": 2671,
    "files": 6,
    "dependencies": 1
  },
  "DockLayout": {
    "bytes": 37353,
    "gzip": 10045,
    "files": 25,
    "dependencies": 8
  },
  "DocumentScanner": {
    "bytes": 27977,
    "gzip": 8102,
    "files": 11,
    "dependencies": 3
  },
  "DomainSetup": {
    "bytes": 42439,
    "gzip": 10969,
    "files": 42,
    "dependencies": 17
  },
  "DonutChart": {
    "bytes": 10336,
    "gzip": 3406,
    "files": 10,
    "dependencies": 3
  },
  "DotGlobe": {
    "bytes": 6596,
    "gzip": 2269,
    "files": 6,
    "dependencies": 1
  },
  "DownloadButton": {
    "bytes": 15733,
    "gzip": 4517,
    "files": 11,
    "dependencies": 3
  },
  "DraftRecovery": {
    "bytes": 12871,
    "gzip": 4174,
    "files": 8,
    "dependencies": 2
  },
  "Drawer": {
    "bytes": 17688,
    "gzip": 5332,
    "files": 17,
    "dependencies": 5
  },
  "DropOverlay": {
    "bytes": 14286,
    "gzip": 4588,
    "files": 12,
    "dependencies": 4
  },
  "DropdownMenu": {
    "bytes": 22651,
    "gzip": 6297,
    "files": 24,
    "dependencies": 8
  },
  "DumbbellChart": {
    "bytes": 20131,
    "gzip": 5911,
    "files": 13,
    "dependencies": 4
  },
  "DurationInput": {
    "bytes": 6857,
    "gzip": 2535,
    "files": 3,
    "dependencies": 0
  },
  "EasingEditor": {
    "bytes": 26990,
    "gzip": 7578,
    "files": 18,
    "dependencies": 6
  },
  "EditableTable": {
    "bytes": 10695,
    "gzip": 3107,
    "files": 5,
    "dependencies": 1
  },
  "EmailVerification": {
    "bytes": 22280,
    "gzip": 6428,
    "files": 17,
    "dependencies": 6
  },
  "EmailViewer": {
    "bytes": 19324,
    "gzip": 6374,
    "files": 13,
    "dependencies": 5
  },
  "EmojiPicker": {
    "bytes": 20461,
    "gzip": 7795,
    "files": 8,
    "dependencies": 1
  },
  "EmojiSlider": {
    "bytes": 7097,
    "gzip": 2446,
    "files": 5,
    "dependencies": 1
  },
  "EmptyState": {
    "bytes": 4713,
    "gzip": 1672,
    "files": 8,
    "dependencies": 2
  },
  "Equalizer": {
    "bytes": 26281,
    "gzip": 8277,
    "files": 10,
    "dependencies": 3
  },
  "ErrorBoundary": {
    "bytes": 8408,
    "gzip": 2976,
    "files": 9,
    "dependencies": 3
  },
  "ErrorBudget": {
    "bytes": 24933,
    "gzip": 7345,
    "files": 10,
    "dependencies": 3
  },
  "ErrorState": {
    "bytes": 10289,
    "gzip": 3024,
    "files": 11,
    "dependencies": 3
  },
  "EventCalendar": {
    "bytes": 43032,
    "gzip": 10996,
    "files": 27,
    "dependencies": 9
  },
  "EventHorizon": {
    "bytes": 12046,
    "gzip": 3649,
    "files": 5,
    "dependencies": 0
  },
  "ExifViewer": {
    "bytes": 30366,
    "gzip": 8814,
    "files": 18,
    "dependencies": 6
  },
  "ExpandableText": {
    "bytes": 2518,
    "gzip": 1066,
    "files": 4,
    "dependencies": 0
  },
  "ExpenseSplitter": {
    "bytes": 53017,
    "gzip": 13284,
    "files": 33,
    "dependencies": 12
  },
  "ExperimentResults": {
    "bytes": 22017,
    "gzip": 6768,
    "files": 12,
    "dependencies": 4
  },
  "FallingSand": {
    "bytes": 49924,
    "gzip": 14291,
    "files": 17,
    "dependencies": 5
  },
  "FaqSection": {
    "bytes": 28566,
    "gzip": 8058,
    "files": 26,
    "dependencies": 10
  },
  "FeatureBeacon": {
    "bytes": 20151,
    "gzip": 5831,
    "files": 19,
    "dependencies": 6
  },
  "FeatureComparison": {
    "bytes": 17769,
    "gzip": 4956,
    "files": 13,
    "dependencies": 4
  },
  "FeatureFlags": {
    "bytes": 37632,
    "gzip": 9768,
    "files": 38,
    "dependencies": 15
  },
  "FeatureGrid": {
    "bytes": 12808,
    "gzip": 3756,
    "files": 15,
    "dependencies": 5
  },
  "FeedbackWidget": {
    "bytes": 29139,
    "gzip": 8038,
    "files": 30,
    "dependencies": 11
  },
  "Ferrofluid": {
    "bytes": 41850,
    "gzip": 12081,
    "files": 10,
    "dependencies": 2
  },
  "Field": {
    "bytes": 5849,
    "gzip": 1947,
    "files": 9,
    "dependencies": 3
  },
  "Figure": {
    "bytes": 3556,
    "gzip": 1397,
    "files": 5,
    "dependencies": 1
  },
  "FileList": {
    "bytes": 34206,
    "gzip": 9357,
    "files": 31,
    "dependencies": 11
  },
  "FileUpload": {
    "bytes": 19825,
    "gzip": 5606,
    "files": 17,
    "dependencies": 6
  },
  "FilterBar": {
    "bytes": 9710,
    "gzip": 2971,
    "files": 13,
    "dependencies": 5
  },
  "FilterBuilder": {
    "bytes": 42232,
    "gzip": 10709,
    "files": 31,
    "dependencies": 11
  },
  "FindInPage": {
    "bytes": 19085,
    "gzip": 5963,
    "files": 11,
    "dependencies": 3
  },
  "FitText": {
    "bytes": 3447,
    "gzip": 1321,
    "files": 4,
    "dependencies": 0
  },
  "FlameGraph": {
    "bytes": 36251,
    "gzip": 10295,
    "files": 20,
    "dependencies": 7
  },
  "FlipBook": {
    "bytes": 8118,
    "gzip": 2574,
    "files": 7,
    "dependencies": 2
  },
  "FlipCard": {
    "bytes": 2253,
    "gzip": 891,
    "files": 3,
    "dependencies": 0
  },
  "FloatingPanel": {
    "bytes": 18425,
    "gzip": 5343,
    "files": 13,
    "dependencies": 4
  },
  "FlowDiagram": {
    "bytes": 33204,
    "gzip": 9716,
    "files": 12,
    "dependencies": 3
  },
  "FlowField": {
    "bytes": 7936,
    "gzip": 2631,
    "files": 4,
    "dependencies": 0
  },
  "FluidCanvas": {
    "bytes": 36624,
    "gzip": 10125,
    "files": 6,
    "dependencies": 0
  },
  "FocusTrap": {
    "bytes": 1924,
    "gzip": 808,
    "files": 2,
    "dependencies": 0
  },
  "FollowButton": {
    "bytes": 9809,
    "gzip": 2982,
    "files": 7,
    "dependencies": 1
  },
  "ForecastChart": {
    "bytes": 27017,
    "gzip": 8077,
    "files": 13,
    "dependencies": 4
  },
  "Form": {
    "bytes": 3968,
    "gzip": 1482,
    "files": 5,
    "dependencies": 1
  },
  "FormulaEditor": {
    "bytes": 18160,
    "gzip": 5992,
    "files": 3,
    "dependencies": 0
  },
  "FractalExplorer": {
    "bytes": 31613,
    "gzip": 8978,
    "files": 18,
    "dependencies": 6
  },
  "FullTextSearch": {
    "bytes": 22236,
    "gzip": 7005,
    "files": 8,
    "dependencies": 1
  },
  "FullscreenDialog": {
    "bytes": 31897,
    "gzip": 8350,
    "files": 31,
    "dependencies": 12
  },
  "FunnelChart": {
    "bytes": 4922,
    "gzip": 1753,
    "files": 5,
    "dependencies": 1
  },
  "FuzzyFinder": {
    "bytes": 18595,
    "gzip": 5654,
    "files": 8,
    "dependencies": 1
  },
  "Game2048": {
    "bytes": 26250,
    "gzip": 7465,
    "files": 13,
    "dependencies": 3
  },
  "GameOfLife": {
    "bytes": 18697,
    "gzip": 5560,
    "files": 12,
    "dependencies": 4
  },
  "GanttChart": {
    "bytes": 31288,
    "gzip": 8086,
    "files": 13,
    "dependencies": 4
  },
  "GeoCoordinateInput": {
    "bytes": 32842,
    "gzip": 9588,
    "files": 26,
    "dependencies": 10
  },
  "GifRecorder": {
    "bytes": 25184,
    "gzip": 7708,
    "files": 15,
    "dependencies": 5
  },
  "GlitchText": {
    "bytes": 2067,
    "gzip": 774,
    "files": 3,
    "dependencies": 0
  },
  "GooeyLoader": {
    "bytes": 2881,
    "gzip": 1142,
    "files": 5,
    "dependencies": 1
  },
  "GradientText": {
    "bytes": 1712,
    "gzip": 817,
    "files": 3,
    "dependencies": 0
  },
  "GravityTags": {
    "bytes": 7555,
    "gzip": 2585,
    "files": 6,
    "dependencies": 1
  },
  "Grid": {
    "bytes": 3733,
    "gzip": 1261,
    "files": 3,
    "dependencies": 0
  },
  "HelpPanel": {
    "bytes": 24974,
    "gzip": 6646,
    "files": 25,
    "dependencies": 10
  },
  "HeroSection": {
    "bytes": 11968,
    "gzip": 3572,
    "files": 10,
    "dependencies": 2
  },
  "HexViewer": {
    "bytes": 22005,
    "gzip": 6525,
    "files": 16,
    "dependencies": 6
  },
  "HexbinChart": {
    "bytes": 23649,
    "gzip": 7321,
    "files": 15,
    "dependencies": 5
  },
  "HighlightMatch": {
    "bytes": 2865,
    "gzip": 1234,
    "files": 3,
    "dependencies": 0
  },
  "Histogram": {
    "bytes": 19530,
    "gzip": 6025,
    "files": 11,
    "dependencies": 3
  },
  "HoldToConfirm": {
    "bytes": 7028,
    "gzip": 2419,
    "files": 6,
    "dependencies": 1
  },
  "HoloCard": {
    "bytes": 4384,
    "gzip": 1516,
    "files": 3,
    "dependencies": 0
  },
  "Hotkeys": {
    "bytes": 9726,
    "gzip": 3285,
    "files": 2,
    "dependencies": 0
  },
  "HoverCard": {
    "bytes": 13967,
    "gzip": 3871,
    "files": 13,
    "dependencies": 3
  },
  "IconButton": {
    "bytes": 3260,
    "gzip": 1321,
    "files": 6,
    "dependencies": 1
  },
  "IconTile": {
    "bytes": 1118,
    "gzip": 610,
    "files": 4,
    "dependencies": 0
  },
  "ImageAdjust": {
    "bytes": 28297,
    "gzip": 8298,
    "files": 16,
    "dependencies": 5
  },
  "ImageAnnotator": {
    "bytes": 18975,
    "gzip": 5361,
    "files": 13,
    "dependencies": 4
  },
  "ImageCompare": {
    "bytes": 7768,
    "gzip": 2556,
    "files": 5,
    "dependencies": 1
  },
  "ImageDiff": {
    "bytes": 19080,
    "gzip": 5943,
    "files": 15,
    "dependencies": 5
  },
  "ImageGallery": {
    "bytes": 28490,
    "gzip": 7730,
    "files": 25,
    "dependencies": 9
  },
  "ImportMapper": {
    "bytes": 30262,
    "gzip": 8249,
    "files": 21,
    "dependencies": 6
  },
  "IncidentTimeline": {
    "bytes": 9914,
    "gzip": 2935,
    "files": 12,
    "dependencies": 4
  },
  "InfiniteScroll": {
    "bytes": 9308,
    "gzip": 3152,
    "files": 9,
    "dependencies": 3
  },
  "InfiniteZoom": {
    "bytes": 22433,
    "gzip": 6640,
    "files": 10,
    "dependencies": 2
  },
  "InlineCompletion": {
    "bytes": 7094,
    "gzip": 2576,
    "files": 4,
    "dependencies": 0
  },
  "InlineEdit": {
    "bytes": 15537,
    "gzip": 4617,
    "files": 13,
    "dependencies": 4
  },
  "InlineMessage": {
    "bytes": 3642,
    "gzip": 1366,
    "files": 5,
    "dependencies": 1
  },
  "Input": {
    "bytes": 2161,
    "gzip": 956,
    "files": 3,
    "dependencies": 0
  },
  "InputGroup": {
    "bytes": 2952,
    "gzip": 1258,
    "files": 3,
    "dependencies": 0
  },
  "InputOTP": {
    "bytes": 3429,
    "gzip": 1312,
    "files": 3,
    "dependencies": 0
  },
  "IntegrationCard": {
    "bytes": 18146,
    "gzip": 4844,
    "files": 20,
    "dependencies": 7
  },
  "InviteMembers": {
    "bytes": 66157,
    "gzip": 16052,
    "files": 57,
    "dependencies": 23
  },
  "InvoiceList": {
    "bytes": 16106,
    "gzip": 4530,
    "files": 22,
    "dependencies": 8
  },
  "IpAllowlist": {
    "bytes": 43965,
    "gzip": 11391,
    "files": 37,
    "dependencies": 15
  },
  "IronFilings": {
    "bytes": 46137,
    "gzip": 12700,
    "files": 15,
    "dependencies": 4
  },
  "Joystick": {
    "bytes": 9678,
    "gzip": 3293,
    "files": 6,
    "dependencies": 1
  },
  "JsonDiff": {
    "bytes": 25916,
    "gzip": 7362,
    "files": 12,
    "dependencies": 3
  },
  "JsonQuery": {
    "bytes": 29177,
    "gzip": 8310,
    "files": 8,
    "dependencies": 1
  },
  "JsonViewer": {
    "bytes": 10521,
    "gzip": 3146,
    "files": 7,
    "dependencies": 1
  },
  "JustifiedText": {
    "bytes": 13738,
    "gzip": 4830,
    "files": 6,
    "dependencies": 0
  },
  "JwtInspector": {
    "bytes": 45526,
    "gzip": 12419,
    "files": 28,
    "dependencies": 9
  },
  "KanbanBoard": {
    "bytes": 11995,
    "gzip": 3348,
    "files": 13,
    "dependencies": 5
  },
  "KaplanMeierChart": {
    "bytes": 27814,
    "gzip": 8279,
    "files": 13,
    "dependencies": 4
  },
  "Kbd": {
    "bytes": 926,
    "gzip": 514,
    "files": 3,
    "dependencies": 0
  },
  "KeyboardShortcutsDialog": {
    "bytes": 30223,
    "gzip": 8518,
    "files": 27,
    "dependencies": 10
  },
  "KineticText": {
    "bytes": 3226,
    "gzip": 1246,
    "files": 6,
    "dependencies": 1
  },
  "Knob": {
    "bytes": 7951,
    "gzip": 2530,
    "files": 5,
    "dependencies": 1
  },
  "KpiStrip": {
    "bytes": 8454,
    "gzip": 2647,
    "files": 7,
    "dependencies": 2
  },
  "Label": {
    "bytes": 3347,
    "gzip": 1279,
    "files": 5,
    "dependencies": 1
  },
  "LanguageSwitcher": {
    "bytes": 23908,
    "gzip": 6524,
    "files": 15,
    "dependencies": 3
  },
  "LayerStack": {
    "bytes": 5899,
    "gzip": 2109,
    "files": 5,
    "dependencies": 1
  },
  "LazyMount": {
    "bytes": 2459,
    "gzip": 1027,
    "files": 3,
    "dependencies": 0
  },
  "Leaderboard": {
    "bytes": 8552,
    "gzip": 2614,
    "files": 7,
    "dependencies": 2
  },
  "Legend": {
    "bytes": 3800,
    "gzip": 1437,
    "files": 5,
    "dependencies": 1
  },
  "LightCaster": {
    "bytes": 24250,
    "gzip": 7004,
    "files": 5,
    "dependencies": 0
  },
  "Lightbox": {
    "bytes": 23836,
    "gzip": 6688,
    "files": 23,
    "dependencies": 8
  },
  "LikeButton": {
    "bytes": 6361,
    "gzip": 2411,
    "files": 4,
    "dependencies": 0
  },
  "LikertScale": {
    "bytes": 6623,
    "gzip": 2034,
    "files": 3,
    "dependencies": 0
  },
  "LineChart": {
    "bytes": 15479,
    "gzip": 4384,
    "files": 14,
    "dependencies": 5
  },
  "LinkPreview": {
    "bytes": 21096,
    "gzip": 5867,
    "files": 17,
    "dependencies": 5
  },
  "LiquidGlass": {
    "bytes": 4040,
    "gzip": 1475,
    "files": 3,
    "dependencies": 0
  },
  "List": {
    "bytes": 771,
    "gzip": 422,
    "files": 3,
    "dependencies": 0
  },
  "ListItem": {
    "bytes": 4226,
    "gzip": 1538,
    "files": 5,
    "dependencies": 1
  },
  "LiveChart": {
    "bytes": 10378,
    "gzip": 3404,
    "files": 8,
    "dependencies": 2
  },
  "LiveRegion": {
    "bytes": 2888,
    "gzip": 1028,
    "files": 2,
    "dependencies": 0
  },
  "LoadingOverlay": {
    "bytes": 4228,
    "gzip": 1562,
    "files": 7,
    "dependencies": 2
  },
  "LocaleSettings": {
    "bytes": 44856,
    "gzip": 11376,
    "files": 33,
    "dependencies": 12
  },
  "LogPatterns": {
    "bytes": 20767,
    "gzip": 6140,
    "files": 7,
    "dependencies": 1
  },
  "LogViewer": {
    "bytes": 18763,
    "gzip": 5444,
    "files": 10,
    "dependencies": 2
  },
  "LogoCloud": {
    "bytes": 5590,
    "gzip": 1941,
    "files": 7,
    "dependencies": 2
  },
  "LoudnessMeter": {
    "bytes": 31393,
    "gzip": 9110,
    "files": 13,
    "dependencies": 4
  },
  "MagicTabs": {
    "bytes": 9322,
    "gzip": 2930,
    "files": 7,
    "dependencies": 1
  },
  "MagneticButton": {
    "bytes": 3207,
    "gzip": 1233,
    "files": 4,
    "dependencies": 0
  },
  "Magnifier": {
    "bytes": 4093,
    "gzip": 1611,
    "files": 3,
    "dependencies": 0
  },
  "MaintenanceNotice": {
    "bytes": 15929,
    "gzip": 4884,
    "files": 11,
    "dependencies": 3
  },
  "MarkdownEditor": {
    "bytes": 18524,
    "gzip": 5616,
    "files": 7,
    "dependencies": 1
  },
  "MarkerHighlight": {
    "bytes": 4334,
    "gzip": 1763,
    "files": 4,
    "dependencies": 0
  },
  "Marquee": {
    "bytes": 1603,
    "gzip": 706,
    "files": 3,
    "dependencies": 0
  },
  "MarqueeSelect": {
    "bytes": 4503,
    "gzip": 1649,
    "files": 5,
    "dependencies": 1
  },
  "MaskedValue": {
    "bytes": 5651,
    "gzip": 2026,
    "files": 7,
    "dependencies": 2
  },
  "Masonry": {
    "bytes": 2962,
    "gzip": 1302,
    "files": 3,
    "dependencies": 0
  },
  "MasterDetail": {
    "bytes": 12680,
    "gzip": 3897,
    "files": 10,
    "dependencies": 2
  },
  "MathFormula": {
    "bytes": 16486,
    "gzip": 5702,
    "files": 3,
    "dependencies": 0
  },
  "MatrixHeatmap": {
    "bytes": 21837,
    "gzip": 6256,
    "files": 11,
    "dependencies": 3
  },
  "MatrixRain": {
    "bytes": 4833,
    "gzip": 1930,
    "files": 4,
    "dependencies": 0
  },
  "MeasureTool": {
    "bytes": 53404,
    "gzip": 13726,
    "files": 37,
    "dependencies": 14
  },
  "MegaMenu": {
    "bytes": 13210,
    "gzip": 3528,
    "files": 5,
    "dependencies": 0
  },
  "MemberList": {
    "bytes": 54170,
    "gzip": 13552,
    "files": 49,
    "dependencies": 19
  },
  "MemoryGame": {
    "bytes": 15175,
    "gzip": 4844,
    "files": 10,
    "dependencies": 3
  },
  "MentionInput": {
    "bytes": 12725,
    "gzip": 4263,
    "files": 12,
    "dependencies": 4
  },
  "Menu": {
    "bytes": 18459,
    "gzip": 5287,
    "files": 18,
    "dependencies": 5
  },
  "Menubar": {
    "bytes": 14604,
    "gzip": 3935,
    "files": 5,
    "dependencies": 0
  },
  "MessageComposer": {
    "bytes": 15111,
    "gzip": 4496,
    "files": 12,
    "dependencies": 3
  },
  "MessageFormat": {
    "bytes": 8763,
    "gzip": 2728,
    "files": 3,
    "dependencies": 0
  },
  "Meteors": {
    "bytes": 5876,
    "gzip": 2065,
    "files": 4,
    "dependencies": 0
  },
  "Meter": {
    "bytes": 1291,
    "gzip": 636,
    "files": 3,
    "dependencies": 0
  },
  "Metric": {
    "bytes": 4501,
    "gzip": 1585,
    "files": 7,
    "dependencies": 2
  },
  "MetricSpotlight": {
    "bytes": 16692,
    "gzip": 4856,
    "files": 19,
    "dependencies": 8
  },
  "Metronome": {
    "bytes": 46548,
    "gzip": 12025,
    "files": 34,
    "dependencies": 12
  },
  "MiddleTruncate": {
    "bytes": 4296,
    "gzip": 1654,
    "files": 4,
    "dependencies": 0
  },
  "MindMap": {
    "bytes": 20329,
    "gzip": 6337,
    "files": 4,
    "dependencies": 0
  },
  "Minesweeper": {
    "bytes": 17489,
    "gzip": 5192,
    "files": 12,
    "dependencies": 4
  },
  "MiniMap": {
    "bytes": 2875,
    "gzip": 1085,
    "files": 3,
    "dependencies": 0
  },
  "Modal": {
    "bytes": 21064,
    "gzip": 6162,
    "files": 21,
    "dependencies": 7
  },
  "ModelViewer": {
    "bytes": 24345,
    "gzip": 7892,
    "files": 11,
    "dependencies": 3
  },
  "MonthPicker": {
    "bytes": 13756,
    "gzip": 4229,
    "files": 9,
    "dependencies": 2
  },
  "MorphDialog": {
    "bytes": 18035,
    "gzip": 5506,
    "files": 17,
    "dependencies": 5
  },
  "MorphingText": {
    "bytes": 5731,
    "gzip": 1960,
    "files": 4,
    "dependencies": 0
  },
  "MultiSelect": {
    "bytes": 32461,
    "gzip": 8206,
    "files": 25,
    "dependencies": 8
  },
  "NaturalDateInput": {
    "bytes": 46290,
    "gzip": 12791,
    "files": 27,
    "dependencies": 9
  },
  "Navbar": {
    "bytes": 23457,
    "gzip": 6095,
    "files": 25,
    "dependencies": 10
  },
  "NavigationProgress": {
    "bytes": 4782,
    "gzip": 1776,
    "files": 4,
    "dependencies": 0
  },
  "NeonSign": {
    "bytes": 1704,
    "gzip": 771,
    "files": 3,
    "dependencies": 0
  },
  "NetworkGraph": {
    "bytes": 25311,
    "gzip": 7442,
    "files": 14,
    "dependencies": 4
  },
  "NewsletterSignup": {
    "bytes": 20261,
    "gzip": 5894,
    "files": 18,
    "dependencies": 7
  },
  "NodeEditor": {
    "bytes": 54007,
    "gzip": 13503,
    "files": 29,
    "dependencies": 10
  },
  "NotFoundState": {
    "bytes": 15213,
    "gzip": 4435,
    "files": 11,
    "dependencies": 3
  },
  "NotificationCenter": {
    "bytes": 34322,
    "gzip": 8879,
    "files": 39,
    "dependencies": 16
  },
  "NotificationPreferences": {
    "bytes": 38988,
    "gzip": 10145,
    "files": 31,
    "dependencies": 11
  },
  "NpsSurvey": {
    "bytes": 20404,
    "gzip": 5874,
    "files": 17,
    "dependencies": 6
  },
  "NumberInput": {
    "bytes": 12943,
    "gzip": 3786,
    "files": 11,
    "dependencies": 3
  },
  "OAuthConsent": {
    "bytes": 21734,
    "gzip": 6032,
    "files": 21,
    "dependencies": 8
  },
  "Odometer": {
    "bytes": 2466,
    "gzip": 998,
    "files": 3,
    "dependencies": 0
  },
  "OnboardingWizard": {
    "bytes": 20247,
    "gzip": 5566,
    "files": 17,
    "dependencies": 6
  },
  "OpenApiReference": {
    "bytes": 35911,
    "gzip": 9782,
    "files": 14,
    "dependencies": 4
  },
  "OrbitRing": {
    "bytes": 3158,
    "gzip": 1070,
    "files": 3,
    "dependencies": 0
  },
  "OrbitSandbox": {
    "bytes": 74353,
    "gzip": 19867,
    "files": 22,
    "dependencies": 7
  },
  "OrderTracker": {
    "bytes": 21886,
    "gzip": 6270,
    "files": 20,
    "dependencies": 7
  },
  "OrgChart": {
    "bytes": 25668,
    "gzip": 6992,
    "files": 15,
    "dependencies": 5
  },
  "PageHeader": {
    "bytes": 3909,
    "gzip": 1417,
    "files": 5,
    "dependencies": 1
  },
  "PageTransition": {
    "bytes": 2736,
    "gzip": 1067,
    "files": 4,
    "dependencies": 0
  },
  "PagedDocument": {
    "bytes": 14576,
    "gzip": 4467,
    "files": 13,
    "dependencies": 4
  },
  "Pagination": {
    "bytes": 13126,
    "gzip": 3948,
    "files": 11,
    "dependencies": 3
  },
  "PairwiseRanker": {
    "bytes": 14066,
    "gzip": 4198,
    "files": 11,
    "dependencies": 4
  },
  "PaletteExtractor": {
    "bytes": 36324,
    "gzip": 10154,
    "files": 25,
    "dependencies": 8
  },
  "PanZoom": {
    "bytes": 4795,
    "gzip": 1676,
    "files": 3,
    "dependencies": 0
  },
  "PanoramaViewer": {
    "bytes": 21508,
    "gzip": 6728,
    "files": 10,
    "dependencies": 2
  },
  "PaperMarbling": {
    "bytes": 40196,
    "gzip": 11327,
    "files": 17,
    "dependencies": 5
  },
  "Parallax": {
    "bytes": 2903,
    "gzip": 1113,
    "files": 4,
    "dependencies": 0
  },
  "ParallaxPortal": {
    "bytes": 13111,
    "gzip": 3944,
    "files": 4,
    "dependencies": 0
  },
  "ParallelCoordinates": {
    "bytes": 25812,
    "gzip": 7631,
    "files": 11,
    "dependencies": 3
  },
  "ParetoChart": {
    "bytes": 21502,
    "gzip": 6279,
    "files": 13,
    "dependencies": 4
  },
  "ParticleField": {
    "bytes": 6813,
    "gzip": 2223,
    "files": 4,
    "dependencies": 0
  },
  "PasskeyManager": {
    "bytes": 33913,
    "gzip": 9498,
    "files": 26,
    "dependencies": 9
  },
  "PasswordInput": {
    "bytes": 10741,
    "gzip": 3234,
    "files": 11,
    "dependencies": 3
  },
  "PasswordStrength": {
    "bytes": 7158,
    "gzip": 2335,
    "files": 11,
    "dependencies": 4
  },
  "PathEditor": {
    "bytes": 37837,
    "gzip": 10188,
    "files": 18,
    "dependencies": 6
  },
  "PatternLock": {
    "bytes": 9015,
    "gzip": 2988,
    "files": 3,
    "dependencies": 0
  },
  "PaymentMethodCard": {
    "bytes": 11371,
    "gzip": 3500,
    "files": 13,
    "dependencies": 5
  },
  "PeerLink": {
    "bytes": 34870,
    "gzip": 9432,
    "files": 24,
    "dependencies": 9
  },
  "PendulumWave": {
    "bytes": 52217,
    "gzip": 14339,
    "files": 20,
    "dependencies": 6
  },
  "PermissionGate": {
    "bytes": 8670,
    "gzip": 2930,
    "files": 11,
    "dependencies": 4
  },
  "PermissionPrompt": {
    "bytes": 13227,
    "gzip": 4341,
    "files": 7,
    "dependencies": 2
  },
  "PhoneInput": {
    "bytes": 12177,
    "gzip": 3789,
    "files": 5,
    "dependencies": 0
  },
  "PianoKeys": {
    "bytes": 9029,
    "gzip": 3096,
    "files": 5,
    "dependencies": 1
  },
  "PictureInPicture": {
    "bytes": 10358,
    "gzip": 3495,
    "files": 9,
    "dependencies": 3
  },
  "PinPad": {
    "bytes": 7282,
    "gzip": 2571,
    "files": 7,
    "dependencies": 2
  },
  "PitchTuner": {
    "bytes": 18395,
    "gzip": 5836,
    "files": 11,
    "dependencies": 4
  },
  "PivotTable": {
    "bytes": 38592,
    "gzip": 10274,
    "files": 25,
    "dependencies": 8
  },
  "PixelCanvas": {
    "bytes": 8941,
    "gzip": 3019,
    "files": 7,
    "dependencies": 2
  },
  "PlanSummary": {
    "bytes": 23029,
    "gzip": 6504,
    "files": 25,
    "dependencies": 9
  },
  "PopUpCard": {
    "bytes": 14576,
    "gzip": 4921,
    "files": 4,
    "dependencies": 0
  },
  "Popover": {
    "bytes": 11343,
    "gzip": 3533,
    "files": 11,
    "dependencies": 2
  },
  "Portal": {
    "bytes": 481,
    "gzip": 279,
    "files": 2,
    "dependencies": 0
  },
  "Presence": {
    "bytes": 1707,
    "gzip": 742,
    "files": 3,
    "dependencies": 0
  },
  "PresenceBar": {
    "bytes": 21983,
    "gzip": 6267,
    "files": 21,
    "dependencies": 7
  },
  "PresenceCursors": {
    "bytes": 6233,
    "gzip": 2281,
    "files": 6,
    "dependencies": 1
  },
  "PressScale": {
    "bytes": 1156,
    "gzip": 573,
    "files": 3,
    "dependencies": 0
  },
  "PricingCard": {
    "bytes": 16050,
    "gzip": 4515,
    "files": 16,
    "dependencies": 5
  },
  "PricingTable": {
    "bytes": 26424,
    "gzip": 7098,
    "files": 26,
    "dependencies": 10
  },
  "PriorityNav": {
    "bytes": 22161,
    "gzip": 6364,
    "files": 15,
    "dependencies": 3
  },
  "PrismLight": {
    "bytes": 47720,
    "gzip": 13747,
    "files": 12,
    "dependencies": 3
  },
  "ProductCard": {
    "bytes": 20834,
    "gzip": 6075,
    "files": 18,
    "dependencies": 6
  },
  "ProductVariantPicker": {
    "bytes": 9367,
    "gzip": 3029,
    "files": 3,
    "dependencies": 0
  },
  "ProfileCard": {
    "bytes": 9794,
    "gzip": 3175,
    "files": 12,
    "dependencies": 4
  },
  "Progress": {
    "bytes": 1499,
    "gzip": 699,
    "files": 3,
    "dependencies": 0
  },
  "ProgressChart": {
    "bytes": 5614,
    "gzip": 1930,
    "files": 7,
    "dependencies": 2
  },
  "ProgressRing": {
    "bytes": 2347,
    "gzip": 912,
    "files": 3,
    "dependencies": 0
  },
  "PromoBanner": {
    "bytes": 5092,
    "gzip": 1741,
    "files": 5,
    "dependencies": 1
  },
  "PromptDialog": {
    "bytes": 31491,
    "gzip": 8605,
    "files": 33,
    "dependencies": 13
  },
  "PullToRefresh": {
    "bytes": 9450,
    "gzip": 3015,
    "files": 9,
    "dependencies": 3
  },
  "QRCode": {
    "bytes": 2826,
    "gzip": 1121,
    "files": 3,
    "dependencies": 0
  },
  "QueryBar": {
    "bytes": 23948,
    "gzip": 6680,
    "files": 6,
    "dependencies": 0
  },
  "QuestionQueue": {
    "bytes": 49335,
    "gzip": 12496,
    "files": 41,
    "dependencies": 15
  },
  "QuickActions": {
    "bytes": 22648,
    "gzip": 6267,
    "files": 24,
    "dependencies": 8
  },
  "RadarChart": {
    "bytes": 13613,
    "gzip": 4201,
    "files": 11,
    "dependencies": 3
  },
  "RadialBarChart": {
    "bytes": 19386,
    "gzip": 5890,
    "files": 13,
    "dependencies": 4
  },
  "RadialGauge": {
    "bytes": 6064,
    "gzip": 1986,
    "files": 7,
    "dependencies": 2
  },
  "RadialMenu": {
    "bytes": 17968,
    "gzip": 5102,
    "files": 7,
    "dependencies": 1
  },
  "Radio": {
    "bytes": 1747,
    "gzip": 813,
    "files": 3,
    "dependencies": 0
  },
  "RadioGroup": {
    "bytes": 10017,
    "gzip": 3041,
    "files": 11,
    "dependencies": 4
  },
  "RainGlass": {
    "bytes": 37634,
    "gzip": 10673,
    "files": 6,
    "dependencies": 0
  },
  "RangeSlider": {
    "bytes": 2795,
    "gzip": 982,
    "files": 3,
    "dependencies": 0
  },
  "RankedChoiceResults": {
    "bytes": 15451,
    "gzip": 4430,
    "files": 8,
    "dependencies": 2
  },
  "RateLimitMeter": {
    "bytes": 7255,
    "gzip": 2556,
    "files": 6,
    "dependencies": 1
  },
  "Rating": {
    "bytes": 7960,
    "gzip": 2292,
    "files": 7,
    "dependencies": 1
  },
  "ReactionBar": {
    "bytes": 5706,
    "gzip": 2147,
    "files": 5,
    "dependencies": 1
  },
  "ReactionDiffusion": {
    "bytes": 30854,
    "gzip": 8946,
    "files": 6,
    "dependencies": 0
  },
  "ReadAloud": {
    "bytes": 34424,
    "gzip": 9566,
    "files": 23,
    "dependencies": 7
  },
  "ReadabilityMeter": {
    "bytes": 16203,
    "gzip": 5511,
    "files": 5,
    "dependencies": 1
  },
  "Receipt": {
    "bytes": 7175,
    "gzip": 2025,
    "files": 3,
    "dependencies": 0
  },
  "RecentItems": {
    "bytes": 17558,
    "gzip": 5193,
    "files": 10,
    "dependencies": 2
  },
  "RecordMerge": {
    "bytes": 29529,
    "gzip": 8367,
    "files": 14,
    "dependencies": 5
  },
  "RecurrenceEditor": {
    "bytes": 53940,
    "gzip": 13178,
    "files": 35,
    "dependencies": 13
  },
  "Redactor": {
    "bytes": 32947,
    "gzip": 9415,
    "files": 21,
    "dependencies": 8
  },
  "ReferralCard": {
    "bytes": 25661,
    "gzip": 7095,
    "files": 26,
    "dependencies": 10
  },
  "RegexTester": {
    "bytes": 33931,
    "gzip": 9476,
    "files": 8,
    "dependencies": 2
  },
  "RelativeTime": {
    "bytes": 2094,
    "gzip": 963,
    "files": 3,
    "dependencies": 0
  },
  "ReleaseNotesModal": {
    "bytes": 30826,
    "gzip": 8430,
    "files": 27,
    "dependencies": 10
  },
  "RemoteSelections": {
    "bytes": 9144,
    "gzip": 3105,
    "files": 4,
    "dependencies": 0
  },
  "RepeaterField": {
    "bytes": 16646,
    "gzip": 4834,
    "files": 11,
    "dependencies": 3
  },
  "ResizableBox": {
    "bytes": 6810,
    "gzip": 2104,
    "files": 3,
    "dependencies": 0
  },
  "ResourceScheduler": {
    "bytes": 26535,
    "gzip": 7474,
    "files": 9,
    "dependencies": 2
  },
  "RetryQueue": {
    "bytes": 11098,
    "gzip": 3211,
    "files": 12,
    "dependencies": 4
  },
  "Reveal": {
    "bytes": 2679,
    "gzip": 1089,
    "files": 4,
    "dependencies": 0
  },
  "ReviewSummary": {
    "bytes": 14920,
    "gzip": 4630,
    "files": 10,
    "dependencies": 2
  },
  "RichTextEditor": {
    "bytes": 46665,
    "gzip": 12650,
    "files": 33,
    "dependencies": 13
  },
  "Ripple": {
    "bytes": 1984,
    "gzip": 923,
    "files": 3,
    "dependencies": 0
  },
  "RippleSurface": {
    "bytes": 5094,
    "gzip": 1826,
    "files": 4,
    "dependencies": 0
  },
  "RoadmapBoard": {
    "bytes": 40980,
    "gzip": 10596,
    "files": 28,
    "dependencies": 9
  },
  "RolePermissions": {
    "bytes": 15305,
    "gzip": 4441,
    "files": 13,
    "dependencies": 4
  },
  "RopeCursor": {
    "bytes": 5925,
    "gzip": 2028,
    "files": 4,
    "dependencies": 0
  },
  "RotatingWord": {
    "bytes": 3285,
    "gzip": 1291,
    "files": 4,
    "dependencies": 0
  },
  "SankeyFlow": {
    "bytes": 8649,
    "gzip": 2438,
    "files": 5,
    "dependencies": 1
  },
  "SaveIndicator": {
    "bytes": 8452,
    "gzip": 2679,
    "files": 12,
    "dependencies": 4
  },
  "SavedViews": {
    "bytes": 33343,
    "gzip": 8803,
    "files": 33,
    "dependencies": 13
  },
  "ScatterChart": {
    "bytes": 22677,
    "gzip": 6657,
    "files": 13,
    "dependencies": 4
  },
  "SchemaForm": {
    "bytes": 54326,
    "gzip": 13695,
    "files": 37,
    "dependencies": 14
  },
  "ScopedSearch": {
    "bytes": 28769,
    "gzip": 7805,
    "files": 19,
    "dependencies": 5
  },
  "ScratchCard": {
    "bytes": 8220,
    "gzip": 2788,
    "files": 5,
    "dependencies": 1
  },
  "ScrollArea": {
    "bytes": 3519,
    "gzip": 1412,
    "files": 3,
    "dependencies": 0
  },
  "ScrollList": {
    "bytes": 3922,
    "gzip": 1508,
    "files": 5,
    "dependencies": 1
  },
  "ScrollProgress": {
    "bytes": 13084,
    "gzip": 3843,
    "files": 8,
    "dependencies": 2
  },
  "ScrollSequence": {
    "bytes": 9212,
    "gzip": 2971,
    "files": 4,
    "dependencies": 0
  },
  "ScrollStory": {
    "bytes": 9499,
    "gzip": 2811,
    "files": 6,
    "dependencies": 1
  },
  "ScrollSync": {
    "bytes": 4785,
    "gzip": 1767,
    "files": 3,
    "dependencies": 0
  },
  "ScrollVelocity": {
    "bytes": 3798,
    "gzip": 1423,
    "files": 4,
    "dependencies": 0
  },
  "SearchField": {
    "bytes": 11076,
    "gzip": 3331,
    "files": 11,
    "dependencies": 3
  },
  "SearchableCheckboxList": {
    "bytes": 18875,
    "gzip": 4922,
    "files": 11,
    "dependencies": 3
  },
  "SeatMap": {
    "bytes": 18555,
    "gzip": 5478,
    "files": 11,
    "dependencies": 4
  },
  "SeatSelector": {
    "bytes": 30682,
    "gzip": 8430,
    "files": 26,
    "dependencies": 10
  },
  "SectionHeading": {
    "bytes": 4857,
    "gzip": 1703,
    "files": 6,
    "dependencies": 1
  },
  "SegmentedControl": {
    "bytes": 3918,
    "gzip": 1534,
    "files": 6,
    "dependencies": 1
  },
  "Select": {
    "bytes": 23804,
    "gzip": 6686,
    "files": 17,
    "dependencies": 4
  },
  "SelectionToolbar": {
    "bytes": 10731,
    "gzip": 3298,
    "files": 8,
    "dependencies": 1
  },
  "SemverRange": {
    "bytes": 23025,
    "gzip": 6558,
    "files": 16,
    "dependencies": 6
  },
  "SequenceDiagram": {
    "bytes": 20331,
    "gzip": 6325,
    "files": 6,
    "dependencies": 1
  },
  "SessionList": {
    "bytes": 34674,
    "gzip": 9252,
    "files": 36,
    "dependencies": 14
  },
  "SessionTimeout": {
    "bytes": 18752,
    "gzip": 5680,
    "files": 18,
    "dependencies": 6
  },
  "SettingsSection": {
    "bytes": 10289,
    "gzip": 3263,
    "files": 11,
    "dependencies": 4
  },
  "SetupChecklist": {
    "bytes": 22367,
    "gzip": 5990,
    "files": 23,
    "dependencies": 9
  },
  "ShaderCanvas": {
    "bytes": 11561,
    "gzip": 3928,
    "files": 4,
    "dependencies": 0
  },
  "ShareMenu": {
    "bytes": 25189,
    "gzip": 7311,
    "files": 21,
    "dependencies": 6
  },
  "SharePermissions": {
    "bytes": 50624,
    "gzip": 12475,
    "files": 40,
    "dependencies": 15
  },
  "ShatterDismiss": {
    "bytes": 30802,
    "gzip": 8822,
    "files": 12,
    "dependencies": 2
  },
  "ShimmerButton": {
    "bytes": 4003,
    "gzip": 1562,
    "files": 3,
    "dependencies": 0
  },
  "ShimmerText": {
    "bytes": 1683,
    "gzip": 795,
    "files": 3,
    "dependencies": 0
  },
  "ShortcutRecorder": {
    "bytes": 7289,
    "gzip": 2601,
    "files": 7,
    "dependencies": 2
  },
  "ShowMoreList": {
    "bytes": 10262,
    "gzip": 3260,
    "files": 9,
    "dependencies": 2
  },
  "Sidebar": {
    "bytes": 6030,
    "gzip": 2041,
    "files": 10,
    "dependencies": 3
  },
  "SidebarRail": {
    "bytes": 18170,
    "gzip": 5137,
    "files": 20,
    "dependencies": 6
  },
  "Sidenotes": {
    "bytes": 8494,
    "gzip": 2750,
    "files": 4,
    "dependencies": 0
  },
  "SignalStrength": {
    "bytes": 2161,
    "gzip": 1009,
    "files": 3,
    "dependencies": 0
  },
  "SignaturePad": {
    "bytes": 8747,
    "gzip": 2851,
    "files": 5,
    "dependencies": 1
  },
  "SiteFooter": {
    "bytes": 14984,
    "gzip": 4066,
    "files": 9,
    "dependencies": 2
  },
  "SiteHeader": {
    "bytes": 9260,
    "gzip": 2676,
    "files": 5,
    "dependencies": 0
  },
  "Skeleton": {
    "bytes": 1474,
    "gzip": 684,
    "files": 3,
    "dependencies": 0
  },
  "SkipLink": {
    "bytes": 1112,
    "gzip": 562,
    "files": 3,
    "dependencies": 0
  },
  "SlaTimer": {
    "bytes": 10076,
    "gzip": 3490,
    "files": 4,
    "dependencies": 0
  },
  "SlideDeck": {
    "bytes": 21083,
    "gzip": 6664,
    "files": 9,
    "dependencies": 3
  },
  "Slider": {
    "bytes": 1717,
    "gzip": 732,
    "files": 3,
    "dependencies": 0
  },
  "SlidingPuzzle": {
    "bytes": 12305,
    "gzip": 4156,
    "files": 7,
    "dependencies": 2
  },
  "SlopeChart": {
    "bytes": 21061,
    "gzip": 6191,
    "files": 11,
    "dependencies": 3
  },
  "SlotReels": {
    "bytes": 7270,
    "gzip": 2546,
    "files": 7,
    "dependencies": 2
  },
  "SmartCrop": {
    "bytes": 26782,
    "gzip": 7887,
    "files": 16,
    "dependencies": 5
  },
  "SnakeGame": {
    "bytes": 21747,
    "gzip": 6450,
    "files": 15,
    "dependencies": 5
  },
  "SnapGuides": {
    "bytes": 15028,
    "gzip": 5002,
    "files": 4,
    "dependencies": 0
  },
  "SnowDrift": {
    "bytes": 41528,
    "gzip": 12092,
    "files": 10,
    "dependencies": 2
  },
  "SocialLoginButtons": {
    "bytes": 7099,
    "gzip": 2765,
    "files": 7,
    "dependencies": 2
  },
  "Solitaire": {
    "bytes": 30937,
    "gzip": 8632,
    "files": 13,
    "dependencies": 4
  },
  "SortableList": {
    "bytes": 6440,
    "gzip": 2166,
    "files": 5,
    "dependencies": 1
  },
  "SortableTree": {
    "bytes": 21808,
    "gzip": 5994,
    "files": 9,
    "dependencies": 2
  },
  "SpacedRepetition": {
    "bytes": 15113,
    "gzip": 4699,
    "files": 7,
    "dependencies": 2
  },
  "Sparkline": {
    "bytes": 2718,
    "gzip": 1106,
    "files": 3,
    "dependencies": 0
  },
  "SpatialNavigation": {
    "bytes": 4287,
    "gzip": 1727,
    "files": 2,
    "dependencies": 0
  },
  "SpinWheel": {
    "bytes": 13066,
    "gzip": 4331,
    "files": 10,
    "dependencies": 3
  },
  "Spinner": {
    "bytes": 991,
    "gzip": 531,
    "files": 3,
    "dependencies": 0
  },
  "SplitButton": {
    "bytes": 27467,
    "gzip": 7504,
    "files": 25,
    "dependencies": 8
  },
  "SplitFlap": {
    "bytes": 4090,
    "gzip": 1619,
    "files": 6,
    "dependencies": 1
  },
  "SplitPane": {
    "bytes": 4373,
    "gzip": 1530,
    "files": 3,
    "dependencies": 0
  },
  "Spotlight": {
    "bytes": 3185,
    "gzip": 1260,
    "files": 4,
    "dependencies": 0
  },
  "SqlBuilder": {
    "bytes": 67992,
    "gzip": 16273,
    "files": 39,
    "dependencies": 15
  },
  "SsoSetup": {
    "bytes": 45169,
    "gzip": 11559,
    "files": 41,
    "dependencies": 16
  },
  "Stack": {
    "bytes": 3263,
    "gzip": 1207,
    "files": 3,
    "dependencies": 0
  },
  "StackTrace": {
    "bytes": 24862,
    "gzip": 7246,
    "files": 17,
    "dependencies": 6
  },
  "StackedCards": {
    "bytes": 4489,
    "gzip": 1594,
    "files": 4,
    "dependencies": 0
  },
  "Stagger": {
    "bytes": 3306,
    "gzip": 1241,
    "files": 6,
    "dependencies": 1
  },
  "StarField": {
    "bytes": 5776,
    "gzip": 1895,
    "files": 4,
    "dependencies": 0
  },
  "StatCard": {
    "bytes": 9220,
    "gzip": 2833,
    "files": 16,
    "dependencies": 6
  },
  "StateView": {
    "bytes": 11818,
    "gzip": 3342,
    "files": 13,
    "dependencies": 4
  },
  "StatusDot": {
    "bytes": 1479,
    "gzip": 668,
    "files": 5,
    "dependencies": 1
  },
  "StatusStrip": {
    "bytes": 17047,
    "gzip": 5330,
    "files": 11,
    "dependencies": 3
  },
  "StepLoader": {
    "bytes": 19323,
    "gzip": 5397,
    "files": 13,
    "dependencies": 4
  },
  "Stepper": {
    "bytes": 10870,
    "gzip": 3149,
    "files": 7,
    "dependencies": 1
  },
  "StickerPeel": {
    "bytes": 5472,
    "gzip": 1840,
    "files": 3,
    "dependencies": 0
  },
  "Sticky": {
    "bytes": 2463,
    "gzip": 1084,
    "files": 3,
    "dependencies": 0
  },
  "StoryProgress": {
    "bytes": 4295,
    "gzip": 1616,
    "files": 4,
    "dependencies": 0
  },
  "StreakCounter": {
    "bytes": 6491,
    "gzip": 2242,
    "files": 7,
    "dependencies": 2
  },
  "StreamGraph": {
    "bytes": 22458,
    "gzip": 6698,
    "files": 11,
    "dependencies": 3
  },
  "StrokeGestures": {
    "bytes": 23441,
    "gzip": 6747,
    "files": 11,
    "dependencies": 3
  },
  "SuccessMark": {
    "bytes": 2138,
    "gzip": 885,
    "files": 5,
    "dependencies": 1
  },
  "Sudoku": {
    "bytes": 22257,
    "gzip": 6486,
    "files": 12,
    "dependencies": 4
  },
  "SunburstChart": {
    "bytes": 27874,
    "gzip": 8227,
    "files": 13,
    "dependencies": 3
  },
  "Surface": {
    "bytes": 1880,
    "gzip": 910,
    "files": 3,
    "dependencies": 0
  },
  "SwipeDeck": {
    "bytes": 5938,
    "gzip": 1850,
    "files": 3,
    "dependencies": 0
  },
  "SwipeRow": {
    "bytes": 3802,
    "gzip": 1483,
    "files": 4,
    "dependencies": 0
  },
  "SwipeToConfirm": {
    "bytes": 14739,
    "gzip": 4128,
    "files": 8,
    "dependencies": 1
  },
  "Switch": {
    "bytes": 1683,
    "gzip": 792,
    "files": 3,
    "dependencies": 0
  },
  "TabBar": {
    "bytes": 5783,
    "gzip": 1996,
    "files": 10,
    "dependencies": 3
  },
  "TabCoordinator": {
    "bytes": 17297,
    "gzip": 5051,
    "files": 11,
    "dependencies": 4
  },
  "Table": {
    "bytes": 2638,
    "gzip": 1011,
    "files": 3,
    "dependencies": 0
  },
  "Tabs": {
    "bytes": 4248,
    "gzip": 1615,
    "files": 4,
    "dependencies": 0
  },
  "Tag": {
    "bytes": 1147,
    "gzip": 613,
    "files": 3,
    "dependencies": 0
  },
  "TagInput": {
    "bytes": 5863,
    "gzip": 1954,
    "files": 7,
    "dependencies": 2
  },
  "Terminal": {
    "bytes": 6669,
    "gzip": 2144,
    "files": 3,
    "dependencies": 0
  },
  "Tesseract": {
    "bytes": 51368,
    "gzip": 14179,
    "files": 19,
    "dependencies": 6
  },
  "TestimonialCard": {
    "bytes": 12678,
    "gzip": 4002,
    "files": 13,
    "dependencies": 4
  },
  "Text": {
    "bytes": 2667,
    "gzip": 1093,
    "files": 3,
    "dependencies": 0
  },
  "TextLink": {
    "bytes": 7304,
    "gzip": 2392,
    "files": 5,
    "dependencies": 0
  },
  "TextReveal": {
    "bytes": 4126,
    "gzip": 1520,
    "files": 4,
    "dependencies": 0
  },
  "TextScramble": {
    "bytes": 3452,
    "gzip": 1315,
    "files": 6,
    "dependencies": 1
  },
  "Textarea": {
    "bytes": 1307,
    "gzip": 669,
    "files": 3,
    "dependencies": 0
  },
  "ThemeScope": {
    "bytes": 1732,
    "gzip": 715,
    "files": 3,
    "dependencies": 0
  },
  "ThreeWayMerge": {
    "bytes": 28680,
    "gzip": 7924,
    "files": 19,
    "dependencies": 7
  },
  "TicTacToe": {
    "bytes": 15199,
    "gzip": 4676,
    "files": 12,
    "dependencies": 4
  },
  "Ticker": {
    "bytes": 2011,
    "gzip": 903,
    "files": 3,
    "dependencies": 0
  },
  "TiltCard": {
    "bytes": 3280,
    "gzip": 1260,
    "files": 4,
    "dependencies": 0
  },
  "TimePicker": {
    "bytes": 18766,
    "gzip": 5677,
    "files": 17,
    "dependencies": 5
  },
  "TimeRangePicker": {
    "bytes": 23867,
    "gzip": 6894,
    "files": 21,
    "dependencies": 7
  },
  "TimeSeriesExplorer": {
    "bytes": 43001,
    "gzip": 11835,
    "files": 21,
    "dependencies": 7
  },
  "TimeSlotPicker": {
    "bytes": 7285,
    "gzip": 2453,
    "files": 3,
    "dependencies": 0
  },
  "Timeline": {
    "bytes": 5088,
    "gzip": 1708,
    "files": 9,
    "dependencies": 3
  },
  "TimezonePlanner": {
    "bytes": 47425,
    "gzip": 12504,
    "files": 31,
    "dependencies": 11
  },
  "Toast": {
    "bytes": 16053,
    "gzip": 4872,
    "files": 15,
    "dependencies": 5
  },
  "ToggleButton": {
    "bytes": 5089,
    "gzip": 1795,
    "files": 10,
    "dependencies": 3
  },
  "ToggleGroup": {
    "bytes": 2345,
    "gzip": 1006,
    "files": 4,
    "dependencies": 0
  },
  "Toggletip": {
    "bytes": 14002,
    "gzip": 4227,
    "files": 14,
    "dependencies": 3
  },
  "Toolbar": {
    "bytes": 1813,
    "gzip": 851,
    "files": 3,
    "dependencies": 0
  },
  "Tooltip": {
    "bytes": 13864,
    "gzip": 3974,
    "files": 13,
    "dependencies": 3
  },
  "TournamentBracket": {
    "bytes": 18004,
    "gzip": 5774,
    "files": 4,
    "dependencies": 0
  },
  "TraceWaterfall": {
    "bytes": 31361,
    "gzip": 8942,
    "files": 14,
    "dependencies": 4
  },
  "TrackChanges": {
    "bytes": 13175,
    "gzip": 4155,
    "files": 7,
    "dependencies": 2
  },
  "TranscriptView": {
    "bytes": 23432,
    "gzip": 6479,
    "files": 16,
    "dependencies": 5
  },
  "TransferList": {
    "bytes": 17070,
    "gzip": 4856,
    "files": 7,
    "dependencies": 1
  },
  "TransformBox": {
    "bytes": 12876,
    "gzip": 4233,
    "files": 4,
    "dependencies": 0
  },
  "TreeMap": {
    "bytes": 8710,
    "gzip": 2944,
    "files": 7,
    "dependencies": 2
  },
  "TreeSelect": {
    "bytes": 32053,
    "gzip": 8426,
    "files": 17,
    "dependencies": 4
  },
  "TreeTable": {
    "bytes": 15913,
    "gzip": 4663,
    "files": 9,
    "dependencies": 2
  },
  "TreeView": {
    "bytes": 12207,
    "gzip": 3715,
    "files": 7,
    "dependencies": 1
  },
  "TrendDelta": {
    "bytes": 3234,
    "gzip": 1332,
    "files": 3,
    "dependencies": 0
  },
  "TwoFactorSetup": {
    "bytes": 30702,
    "gzip": 8004,
    "files": 27,
    "dependencies": 11
  },
  "Typewriter": {
    "bytes": 4749,
    "gzip": 1782,
    "files": 6,
    "dependencies": 1
  },
  "TypingIndicator": {
    "bytes": 4534,
    "gzip": 1660,
    "files": 5,
    "dependencies": 1
  },
  "UndoStack": {
    "bytes": 10484,
    "gzip": 3230,
    "files": 11,
    "dependencies": 4
  },
  "UnitInput": {
    "bytes": 10689,
    "gzip": 3240,
    "files": 5,
    "dependencies": 0
  },
  "UnsavedChangesBar": {
    "bytes": 25861,
    "gzip": 7128,
    "files": 25,
    "dependencies": 9
  },
  "UpdateAvailable": {
    "bytes": 17093,
    "gzip": 4959,
    "files": 13,
    "dependencies": 4
  },
  "UpgradePrompt": {
    "bytes": 16683,
    "gzip": 4642,
    "files": 14,
    "dependencies": 4
  },
  "UploadQueue": {
    "bytes": 23727,
    "gzip": 6169,
    "files": 15,
    "dependencies": 5
  },
  "UrlState": {
    "bytes": 7279,
    "gzip": 2607,
    "files": 3,
    "dependencies": 0
  },
  "UsageMeter": {
    "bytes": 13177,
    "gzip": 4087,
    "files": 14,
    "dependencies": 5
  },
  "UsagePricingCalculator": {
    "bytes": 32639,
    "gzip": 8736,
    "files": 28,
    "dependencies": 11
  },
  "UserMenu": {
    "bytes": 27305,
    "gzip": 7710,
    "files": 26,
    "dependencies": 8
  },
  "ValidationSummary": {
    "bytes": 4916,
    "gzip": 1853,
    "files": 5,
    "dependencies": 1
  },
  "VennDiagram": {
    "bytes": 21482,
    "gzip": 6813,
    "files": 11,
    "dependencies": 3
  },
  "VersionHistory": {
    "bytes": 31495,
    "gzip": 8799,
    "files": 28,
    "dependencies": 10
  },
  "VersionSwitcher": {
    "bytes": 22974,
    "gzip": 6383,
    "files": 17,
    "dependencies": 4
  },
  "VibePoll": {
    "bytes": 6368,
    "gzip": 2260,
    "files": 7,
    "dependencies": 2
  },
  "VideoPlayer": {
    "bytes": 37015,
    "gzip": 9803,
    "files": 30,
    "dependencies": 11
  },
  "ViolinPlot": {
    "bytes": 22755,
    "gzip": 6889,
    "files": 11,
    "dependencies": 3
  },
  "VirtualList": {
    "bytes": 2140,
    "gzip": 900,
    "files": 3,
    "dependencies": 0
  },
  "VisionSimulator": {
    "bytes": 27019,
    "gzip": 7657,
    "files": 19,
    "dependencies": 5
  },
  "VisuallyHidden": {
    "bytes": 229,
    "gzip": 190,
    "files": 2,
    "dependencies": 0
  },
  "VoiceRecorder": {
    "bytes": 47679,
    "gzip": 12573,
    "files": 33,
    "dependencies": 12
  },
  "VoronoiField": {
    "bytes": 9466,
    "gzip": 2969,
    "files": 4,
    "dependencies": 0
  },
  "VoteButtons": {
    "bytes": 4228,
    "gzip": 1658,
    "files": 3,
    "dependencies": 0
  },
  "VoxelTerrain": {
    "bytes": 47588,
    "gzip": 13704,
    "files": 17,
    "dependencies": 5
  },
  "WaterfallChart": {
    "bytes": 20127,
    "gzip": 6009,
    "files": 13,
    "dependencies": 4
  },
  "Waveform": {
    "bytes": 2489,
    "gzip": 1112,
    "files": 3,
    "dependencies": 0
  },
  "WebVitals": {
    "bytes": 13812,
    "gzip": 4504,
    "files": 9,
    "dependencies": 3
  },
  "WebhookDeliveries": {
    "bytes": 30989,
    "gzip": 8726,
    "files": 25,
    "dependencies": 9
  },
  "WebhookEndpoints": {
    "bytes": 40886,
    "gzip": 10371,
    "files": 43,
    "dependencies": 17
  },
  "WeekView": {
    "bytes": 19503,
    "gzip": 5667,
    "files": 9,
    "dependencies": 2
  },
  "WeekdayPicker": {
    "bytes": 5251,
    "gzip": 2024,
    "files": 3,
    "dependencies": 0
  },
  "Whiteboard": {
    "bytes": 53676,
    "gzip": 14263,
    "files": 30,
    "dependencies": 11
  },
  "WordCloud": {
    "bytes": 17479,
    "gzip": 5874,
    "files": 11,
    "dependencies": 3
  },
  "WordGuess": {
    "bytes": 26115,
    "gzip": 9353,
    "files": 10,
    "dependencies": 3
  },
  "Wordmark": {
    "bytes": 1704,
    "gzip": 778,
    "files": 3,
    "dependencies": 0
  },
  "WorkspaceSwitcher": {
    "bytes": 33244,
    "gzip": 8929,
    "files": 28,
    "dependencies": 9
  },
  "XPBar": {
    "bytes": 7259,
    "gzip": 2472,
    "files": 7,
    "dependencies": 2
  },
  "ZipBrowser": {
    "bytes": 25692,
    "gzip": 8080,
    "files": 12,
    "dependencies": 3
  }
}

export function sizeOf(component: string): ComponentSize | undefined {
  return sizes[component]
}

/** The whole package, once, plus the extremes. */
export const library = {
  "gzip": 1153040,
  "modules": 686,
  "median": 4155,
  "lightest": {
    "name": "VisuallyHidden",
    "gzip": 190
  },
  "heaviest": {
    "name": "OrbitSandbox",
    "gzip": 19867
  }
}
