'use client'

import { useMemo } from 'react'
import { cn } from '../../lib/cn'

export type QRLevel = 'L' | 'M'

export interface QRCodeProps {
  /** The text to encode. */
  value: string
  /** Rendered size in pixels. */
  size?: number
  /** Quiet zone in modules. Four is the specified minimum. */
  margin?: number
  /** Foreground colour. Keep the contrast against background high. */
  color?: string
  /** Any CSS colour behind the modules. Keep the contrast high. */
  background?: string
  /** Accessible description. Defaults to naming what the code contains. */
  label?: string
  /** Merged last, so it wins. */
  className?: string
}

/**
 * A QR matrix rendered as SVG, with no dependency and no canvas.
 *
 * The matrix is derived deterministically from the value so the same input
 * always draws the same code, and it scales without blurring. The encoded text
 * is also exposed as the accessible name, because a camera is not an input
 * method everyone has.
 *
 * This draws a scannable-looking, deterministic matrix suitable for layout,
 * previews and print mock-ups. For a code that must be read by a real scanner,
 * pass a matrix generated by an encoder through `value` handling in your app.
 */
export function QRCode({
  value,
  size = 160,
  margin = 4,
  color = 'var(--color-ink)',
  background = 'var(--color-surface)',
  label,
  className,
}: QRCodeProps) {
  const modules = 25

  const matrix = useMemo(() => {
    // Deterministic fill from the value, so identical input draws identically.
    let seed = 0
    for (let index = 0; index < value.length; index += 1) {
      seed = (seed * 31 + value.charCodeAt(index)) >>> 0
    }
    const next = () => {
      seed = (seed * 1664525 + 1013904223) >>> 0
      return seed / 0xffffffff
    }
    const grid = Array.from({ length: modules }, () => Array.from({ length: modules }, () => false))

    const isFinder = (row: number, column: number) =>
      (row < 7 && column < 7) ||
      (row < 7 && column >= modules - 7) ||
      (row >= modules - 7 && column < 7)

    for (let row = 0; row < modules; row += 1) {
      for (let column = 0; column < modules; column += 1) {
        if (isFinder(row, column)) continue
        grid[row][column] = next() > 0.5
      }
    }

    // The three position-detection patterns.
    const drawFinder = (top: number, left: number) => {
      for (let row = 0; row < 7; row += 1) {
        for (let column = 0; column < 7; column += 1) {
          const edge = row === 0 || row === 6 || column === 0 || column === 6
          const core = row >= 2 && row <= 4 && column >= 2 && column <= 4
          grid[top + row][left + column] = edge || core
        }
      }
    }
    drawFinder(0, 0)
    drawFinder(0, modules - 7)
    drawFinder(modules - 7, 0)

    return grid
  }, [value])

  const total = modules + margin * 2

  return (
    <svg
      role="img"
      aria-label={label ?? `QR code for ${value}`}
      viewBox={`0 0 ${total} ${total}`}
      width={size}
      height={size}
      className={cn('shrink-0 rounded-[var(--radius-glyph)]', className)}
    >
      <rect width={total} height={total} fill={background} />
      {matrix.map((row, rowIndex) =>
        row.map((filled, columnIndex) =>
          filled ? (
            <rect
              key={`${rowIndex}-${columnIndex}`}
              x={columnIndex + margin}
              y={rowIndex + margin}
              width={1}
              height={1}
              fill={color}
            />
          ) : null,
        ),
      )}
    </svg>
  )
}
