// Weighs each component: its own files, plus everything it drags in.
//
// Runs against the built package rather than the source, because what a
// consumer pays for is the compiled module, and it resolves the dependency
// graph so the figure is what actually lands in a bundle — not the size of one
// file that imports eight others.
import { readFileSync, writeFileSync, existsSync, readdirSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { gzipSync } from 'node:zlib'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const DIST = join(ROOT, 'dist')

if (!existsSync(DIST)) {
  console.error('measure-size: no dist/. Run `npm run build:js` first.')
  process.exit(1)
}

const meta = JSON.parse(readFileSync(join(ROOT, 'data', 'components.json'), 'utf8'))
const { components, shared } = meta

/** The transitive file set, mirroring what the CLI and the docs both resolve. */
function filesFor(name) {
  const seen = new Set()
  const order = []
  const walk = (current) => {
    if (seen.has(current)) return
    seen.add(current)
    for (const dep of components[current]?.internal ?? []) walk(dep)
    order.push(current)
  }
  walk(name)

  const sharedFiles = new Set()
  for (const component of order) {
    for (const path of components[component].shared) {
      sharedFiles.add(path)
      for (const nested of shared[path] ?? []) sharedFiles.add(nested)
    }
  }

  return {
    dependencies: order.length - 1,
    files: [...sharedFiles, ...order.flatMap((component) => components[component].files)],
  }
}

/** Source path -> built path. `.tsx` and `.ts` both compile to `.js`. */
const built = (path) => join(DIST, path.replace(/\.tsx?$/, '.js'))

const sizes = {}
let measured = 0
let skipped = 0

// Every module on its own, by source path: what lets a page add up any set of
// components exactly, counting a module the set shares only once.
const modules = {}
const weigh = (file) => {
  if (file in modules) return
  const full = built(file)
  if (!existsSync(full)) return
  const raw = readFileSync(full)
  modules[file] = { bytes: raw.length, gzip: gzipSync(raw, { level: 9 }).length }
}

for (const name of Object.keys(components).sort()) {
  const { files, dependencies } = filesFor(name)
  const chunks = []
  let found = 0

  for (const file of files) {
    weigh(file)
    const full = built(file)
    // Barrels are pure re-exports; Rollup folds them away, and their absence
    // from the build is the correct outcome rather than a missing measurement.
    if (!existsSync(full)) continue
    chunks.push(readFileSync(full))
    found += 1
  }

  if (found === 0) {
    skipped += 1
    continue
  }

  const raw = Buffer.concat(chunks)
  sizes[name] = {
    bytes: raw.length,
    gzip: gzipSync(raw, { level: 9 }).length,
    files: files.length,
    dependencies,
  }
  measured += 1
}

const output = `// GENERATED by scripts/measure-size.mjs - do not edit.
//
// Measured on the built package, over each component's whole dependency set:
// what a bundler would add for that one import, minus anything it already has.
// Unminified, because minification is the consumer's build, not ours.

export interface ComponentSize {
  /** Bytes of built JavaScript, this component and everything it imports. */
  bytes: number
  /** The same, gzipped. */
  gzip: number
  /** How many modules that is. */
  files: number
  /** How many other components come with it. */
  dependencies: number
}

export const sizes: Record<string, ComponentSize> = ${JSON.stringify(sizes, null, 2)}

export function sizeOf(component: string): ComponentSize | undefined {
  return sizes[component]
}
`

// Every module in the build, once: the ceiling, for someone who imports all
// of it. A real bundle of one app will be far smaller; this is the worst case.
const allModules = []
const walkDist = (dir) => {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name)
    if (entry.isDirectory()) walkDist(full)
    else if (entry.name.endsWith('.js')) allModules.push(readFileSync(full))
  }
}
walkDist(DIST)
const everything = Buffer.concat(allModules)
const ranked = Object.entries(sizes).sort((a, b) => a[1].gzip - b[1].gzip)
const library = {
  gzip: gzipSync(everything, { level: 9 }).length,
  modules: allModules.length,
  median: median(Object.values(sizes).map((entry) => entry.gzip)),
  lightest: { name: ranked[0][0], gzip: ranked[0][1].gzip },
  heaviest: { name: ranked[ranked.length - 1][0], gzip: ranked[ranked.length - 1][1].gzip },
}

writeFileSync(
  join(ROOT, 'data', 'sizes.json'),
  `${JSON.stringify({ components: sizes, library }, null, 2)}
`,
)

writeFileSync(
  join(ROOT, 'src', 'site', 'data', 'sizes.ts'),
  output +
    `
/** The whole package, once, plus the extremes. */
export const library = ${JSON.stringify(library, null, 2)}
`,
)

const sortedModules = Object.fromEntries(Object.keys(modules).sort().map((file) => [file, modules[file]]))
writeFileSync(
  join(ROOT, 'src', 'site', 'data', 'module-sizes.ts'),
  `// GENERATED by scripts/measure-size.mjs - do not edit.
//
// Each built module on its own, by source path, so a set of components can be
// weighed exactly: resolve each one's files with \`dependenciesOf\`, take the
// union, and add these up. \`gzip\` is each module compressed alone, so a sum
// of them is an upper bound — one bundle compresses better than its parts.
// Its own file, so only the page that adds sets up downloads it.

export interface ModuleSize {
  bytes: number
  gzip: number
}

export const moduleSizes: Record<string, ModuleSize> = ${JSON.stringify(sortedModules)}
`,
)

const total = Object.values(sizes).reduce((sum, entry) => sum + entry.gzip, 0)
const heaviest = Object.entries(sizes)
  .sort((a, b) => b[1].gzip - a[1].gzip)
  .slice(0, 3)
  .map(([name, entry]) => `${name} ${(entry.gzip / 1024).toFixed(1)}kB`)

console.log(
  `sizes: ${measured} components measured` +
    (skipped ? `, ${skipped} skipped (not in dist)` : '') +
    `; median ${median(Object.values(sizes).map((entry) => entry.gzip))} B gzip` +
    `; heaviest ${heaviest.join(', ')}`,
)

function median(values) {
  const sorted = [...values].sort((a, b) => a - b)
  return sorted[Math.floor(sorted.length / 2)]
}
